CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `term_id` bigint;
CREATE OR REPLACE PROPERTY `is_root` bigint;
CREATE OR REPLACE PROPERTY `go_id` string;
CREATE OR REPLACE PROPERTY `term_type` string;
CREATE OR REPLACE CONCEPT `term` (`go_id` string, `is_root` bigint, `name` string, `term_id` bigint, `term_type` string, PRIMARY KEY (`term_id`), LABEL (`name`), CONSTRAINT `has_part` MULTIREFERENCE `term` INVERSEOF `part of`  TRANSITIVE(5), CONSTRAINT `has_sub_term` MULTIREFERENCE `term` INVERSEOF `has_parent_term`  TRANSITIVE(5), CONSTRAINT `occurs_in` MULTIREFERENCE `term` INVERSEOF `has_occurring`  TRANSITIVE(3), CONSTRAINT `regulates` MULTIREFERENCE `term` INVERSEOF `regulated_by`  TRANSITIVE(3)) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `root_term`  INHERITS (`term`) FROM timbr.`term` WHERE `is_root` = 1;
CREATE OR REPLACE CONCEPT `molecular_function`  INHERITS (`term`) FROM timbr.`term` WHERE `term_type` = 'molecular_function';
CREATE OR REPLACE CONCEPT `cellular_component`  INHERITS (`term`) FROM timbr.`term` WHERE `term_type` = 'cellular_component';
CREATE OR REPLACE CONCEPT `biological_process`  INHERITS (`term`) FROM timbr.`term` WHERE `term_type` = 'biological_process';
CREATE OR REPLACE CONCEPT `transporter_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 3939;
CREATE OR REPLACE CONCEPT `translation_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 22700;
CREATE OR REPLACE CONCEPT `transcription_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38612;
CREATE OR REPLACE CONCEPT `toxin_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 34994;
CREATE OR REPLACE CONCEPT `structural_molecule_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 3923;
CREATE OR REPLACE CONCEPT `small_molecule_sensor_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38725;
CREATE OR REPLACE CONCEPT `rna_folding_chaperone`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 39035;
CREATE OR REPLACE CONCEPT `protein_tag`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 14644;
CREATE OR REPLACE CONCEPT `protein_serine_threonine_kinase_inhibitor_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 13657;
CREATE OR REPLACE CONCEPT `protein_folding_chaperone`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 21932;
CREATE OR REPLACE CONCEPT `protein_containing_complex_stabilizing_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 39116;
CREATE OR REPLACE CONCEPT `protein_containing_complex_destabilizing_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 39115;
CREATE OR REPLACE CONCEPT `pore_forming_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 39250;
CREATE OR REPLACE CONCEPT `nutrient_reservoir_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 23130;
CREATE OR REPLACE CONCEPT `molecular_transducer_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 28984;
CREATE OR REPLACE CONCEPT `molecular_template_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38868;
CREATE OR REPLACE CONCEPT `molecular_sequestering_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38733;
CREATE OR REPLACE CONCEPT `molecular_function_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 36035;
CREATE OR REPLACE CONCEPT `molecular_carrier_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38608;
CREATE OR REPLACE CONCEPT `molecular_adaptor_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 28985;
CREATE OR REPLACE CONCEPT `membrane_destabilizing_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 39251;
CREATE OR REPLACE CONCEPT `general_transcription_initiation_factor_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38665;
CREATE OR REPLACE CONCEPT `fusogenic_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 38893;
CREATE OR REPLACE CONCEPT `eukaryotic_elongation_factor_2_kinase_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 20457;
CREATE OR REPLACE CONCEPT `cytoskeletal_motor_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 2696;
CREATE OR REPLACE CONCEPT `cyclin_dependent_protein_serine_threonine_kinase_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 10280;
CREATE OR REPLACE CONCEPT `catalytic_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 2745;
CREATE OR REPLACE CONCEPT `cargo_receptor_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 19573;
CREATE OR REPLACE CONCEPT `camp_dependent_protein_kinase_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 6524;
CREATE OR REPLACE CONCEPT `calcium_dependent_protein_kinase_regulator_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 8630;
CREATE OR REPLACE CONCEPT `binding`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 4091;
CREATE OR REPLACE CONCEPT `atp_dependent_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 39006;
CREATE OR REPLACE CONCEPT `antioxidant_activity`  INHERITS (`molecular_function`) FROM timbr.`molecular_function` WHERE `term_id` = 10039;
CREATE OR REPLACE CONCEPT `virion_component`  INHERITS (`cellular_component`) FROM timbr.`cellular_component` WHERE `term_id` = 22134;
CREATE OR REPLACE CONCEPT `protein_containing_complex`  INHERITS (`cellular_component`) FROM timbr.`cellular_component` WHERE `term_id` = 16157;
CREATE OR REPLACE CONCEPT `cellular_anatomical_entity`  INHERITS (`cellular_component`) FROM timbr.`cellular_component` WHERE `term_id` = 38225;
CREATE OR REPLACE CONCEPT `viral_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 9883;
CREATE OR REPLACE CONCEPT `signaling`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 13369;
CREATE OR REPLACE CONCEPT `rhythmic_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 25721;
CREATE OR REPLACE CONCEPT `response_to_stimulus`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 26973;
CREATE OR REPLACE CONCEPT `reproductive_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 13234;
CREATE OR REPLACE CONCEPT `reproduction`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 4;
CREATE OR REPLACE CONCEPT `pigmentation`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 21271;
CREATE OR REPLACE CONCEPT `multicellular_organismal_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 15705;
CREATE OR REPLACE CONCEPT `metabolic_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 6132;
CREATE OR REPLACE CONCEPT `locomotion`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 19984;
CREATE OR REPLACE CONCEPT `localization`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 27252;
CREATE OR REPLACE CONCEPT `immune_system_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 1641;
CREATE OR REPLACE CONCEPT `homeostatic_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 20490;
CREATE OR REPLACE CONCEPT `growth`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 19980;
CREATE OR REPLACE CONCEPT `developmental_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 15706;
CREATE OR REPLACE CONCEPT `detoxification`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 36017;
CREATE OR REPLACE CONCEPT `cellular_process`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 7803;
CREATE OR REPLACE CONCEPT `biological_regulation`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 31039;
CREATE OR REPLACE CONCEPT `biological_process_involved_in_intraspecies_interaction_between_organisms`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 27735;
CREATE OR REPLACE CONCEPT `biological_process_involved_in_interspecies_interaction_between_organisms`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 22130;
CREATE OR REPLACE CONCEPT `biological_phase`  INHERITS (`biological_process`) FROM timbr.`biological_process` WHERE `term_id` = 22513;