CREATE OR REPLACE PROPERTY `earning_end_date` timestamp;
CREATE OR REPLACE PROPERTY `claim_reported_date` timestamp;
CREATE OR REPLACE PROPERTY `coverage_part_code` string;
CREATE OR REPLACE PROPERTY `status_code` string;
CREATE OR REPLACE PROPERTY `coverage_description` string;
CREATE OR REPLACE PROPERTY `lossreserveamount` integer;
CREATE OR REPLACE PROPERTY `premiumamount` integer;
CREATE OR REPLACE PROPERTY `policy_amount` decimal;
CREATE OR REPLACE PROPERTY `claim_identifier` integer;
CREATE OR REPLACE PROPERTY `amount_type_code` string;
CREATE OR REPLACE PROPERTY `premiumperiod` string;
CREATE OR REPLACE PROPERTY `expiration_date` timestamp;
CREATE OR REPLACE PROPERTY `catastrophe_identifier` integer;
CREATE OR REPLACE PROPERTY `company_claim_number` string;
CREATE OR REPLACE PROPERTY `occurrence_identifier` integer;
CREATE OR REPLACE PROPERTY `coverage_identifier` integer;
CREATE OR REPLACE PROPERTY `policy_number` string;
CREATE OR REPLACE PROPERTY `geographic_location_identifier` integer;
CREATE OR REPLACE PROPERTY `entry_into_claims_made_program_date` timestamp;
CREATE OR REPLACE PROPERTY `event_date` timestamp;
CREATE OR REPLACE PROPERTY `claims_made_date` timestamp;
CREATE OR REPLACE PROPERTY `claim_offer_identifier` integer;
CREATE OR REPLACE PROPERTY `effective_date` timestamp;
CREATE OR REPLACE PROPERTY `policyholderid` integer;
CREATE OR REPLACE PROPERTY `insurance_type_code` string;
CREATE OR REPLACE PROPERTY `expensepaymentamount` integer;
CREATE OR REPLACE PROPERTY `earning_begin_date` timestamp;
CREATE OR REPLACE PROPERTY `policy_amount_identifier` bigint;
CREATE OR REPLACE PROPERTY `claim_close_date` timestamp;
CREATE OR REPLACE PROPERTY `policy_coverage_detail_identifier` integer;
CREATE OR REPLACE PROPERTY `claim_amount_identifier` bigint;
CREATE OR REPLACE PROPERTY `claim_amount` decimal;
CREATE OR REPLACE PROPERTY `insurable_object_identifier` integer;
CREATE OR REPLACE PROPERTY `claim_reopen_date` timestamp;
CREATE OR REPLACE PROPERTY `coverage_inclusion_exclusion_code` string;
CREATE OR REPLACE PROPERTY `claim_open_date` timestamp;
CREATE OR REPLACE PROPERTY `claim_status_code` string;
CREATE OR REPLACE PROPERTY `losspaymentamount` integer;
CREATE OR REPLACE PROPERTY `policy_identifier` integer;
CREATE OR REPLACE PROPERTY `claim_description` string;
CREATE OR REPLACE PROPERTY `expensereserveamount` integer;
CREATE OR REPLACE PROPERTY `premiumamountmonthly` integer;
CREATE OR REPLACE PROPERTY `company_subclaim_number` string;
CREATE OR REPLACE CONCEPT `premium` (`premiumperiod` string, `premiumamount` integer, `premiumamountmonthly` integer, `policy_amount_identifier` bigint, PRIMARY KEY (`policy_amount_identifier`), CONSTRAINT `of_policy_amount` FOREIGN KEY (`policy_amount_identifier`) REFERENCES `policy_amount` (`policy_amount_identifier`) INVERSEOF `has_premium` ) INHERITS (`thing`) DESCRIPTION 'This concept represents the premium associated with an insurance policy, identified by the policy amount identifier.' WITH TAGS (`icon` = 'fa-star');
CREATE OR REPLACE CONCEPT `policy_holder` (`policy_number` string, `policyholderid` integer, PRIMARY KEY (`policyholderid`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user');
CREATE OR REPLACE CONCEPT `policy_coverage_detail` (`effective_date` timestamp, `coverage_part_code` string, `coverage_inclusion_exclusion_code` string, `coverage_identifier` integer, `insurable_object_identifier` integer, `policy_coverage_detail_identifier` integer, `coverage_description` string, `expiration_date` timestamp, `policy_identifier` integer, PRIMARY KEY (`policy_coverage_detail_identifier`), CONSTRAINT `of_claim_coverage` FOREIGN KEY (`policy_coverage_detail_identifier`) REFERENCES `claim_coverage` (`policy_coverage_detail_identifier`) INVERSEOF `has_policy_coverage_detail` , CONSTRAINT `has_policy_amount` FOREIGN KEY (`policy_coverage_detail_identifier`) REFERENCES `policy_amount` (`policy_coverage_detail_identifier`) INVERSEOF `of_policy_coverage_detail` ) INHERITS (`thing`) DESCRIPTION 'This concept represents the detailed aspects of policy coverage, including its effective and expiration dates, coverage parts, descriptions, and inclusion or exclusion codes.' WITH TAGS (`icon` = 'fa-check-to-slot');
CREATE OR REPLACE CONCEPT `policy_amount` (`earning_end_date` timestamp, `geographic_location_identifier` integer, `earning_begin_date` timestamp, `effective_date` timestamp, `insurance_type_code` string, `amount_type_code` string, `insurable_object_identifier` integer, `policy_coverage_detail_identifier` integer, `policy_amount` decimal, `policy_amount_identifier` bigint, `policy_identifier` integer, PRIMARY KEY (`policy_amount_identifier`), CONSTRAINT `of_policy` FOREIGN KEY (`policy_identifier`) REFERENCES `policy` (`policy_identifier`) INVERSEOF `has_policy_amount` ) INHERITS (`thing`) DESCRIPTION 'This concept represents the financial aspects of an insurance policy, including the policy amount, types, effective dates, and related insurance details.' WITH TAGS (`icon` = 'fa-funnel-dollar');
CREATE OR REPLACE CONCEPT `policy` (`geographic_location_identifier` integer, `effective_date` timestamp, `policy_number` string, `status_code` string, `expiration_date` timestamp, `policy_identifier` integer, PRIMARY KEY (`policy_identifier`), CONSTRAINT `has_agent` FOREIGN KEY (`policy_identifier`) REFERENCES `agent` (`policy_identifier`) INVERSEOF `of_policy` , CONSTRAINT `has_policy_holder` FOREIGN KEY (`policy_number`) REFERENCES `policy_holder` (`policy_number`) INVERSEOF `of_policy` , CONSTRAINT `has_policy_coverage_detail` FOREIGN KEY (`policy_identifier`) REFERENCES `policy_coverage_detail` (`policy_identifier`) INVERSEOF `of_policy` ) INHERITS (`thing`) DESCRIPTION 'This concept represents an insurance policy, detailing its identifier, effective and expiration dates, policy number, status, and associated geographic location.' WITH TAGS (`icon` = 'fa-scroll');
CREATE OR REPLACE CONCEPT `loss_reserve` (`claim_amount_identifier` bigint, `lossreserveamount` integer, PRIMARY KEY (`claim_amount_identifier`)) INHERITS (`thing`) DESCRIPTION 'This concept represents the reserve funds set aside for a loss amount related to an insurance claim, identified by the claim amount identifier.' WITH TAGS (`icon` = 'fa-life-ring');
CREATE OR REPLACE CONCEPT `loss_payment` (`losspaymentamount` integer, `claim_amount_identifier` bigint, PRIMARY KEY (`claim_amount_identifier`)) INHERITS (`thing`) DESCRIPTION 'This concept represents the payment of a loss amount associated with an insurance claim, identified by the claim amount identifier.' WITH TAGS (`icon` = 'fa-circle-chevron-down');
CREATE OR REPLACE CONCEPT `expense_reserve` (`expensereserveamount` integer, `claim_amount_identifier` bigint, PRIMARY KEY (`claim_amount_identifier`)) INHERITS (`thing`) DESCRIPTION 'This concept represents the reserve funds allocated for expenses related to an insurance claim, identified by the claim amount identifier.' WITH TAGS (`icon` = 'fa-institution');
CREATE OR REPLACE CONCEPT `expense_payment` (`claim_amount_identifier` bigint, `expensepaymentamount` integer, PRIMARY KEY (`claim_amount_identifier`)) INHERITS (`thing`) DESCRIPTION 'This concept represents the payment made for expenses related to an insurance claim, identified by the claim amount identifier.' WITH TAGS (`icon` = 'fa-wallet');
CREATE OR REPLACE CONCEPT `claim_coverage` (`claim_identifier` integer, `effective_date` timestamp, `policy_coverage_detail_identifier` integer, PRIMARY KEY (`claim_identifier`)) INHERITS (`thing`) DESCRIPTION 'This concept represents the coverage details of an insurance claim, linking the claim to specific policy coverage details and their effective dates.' WITH TAGS (`icon` = 'fa-shield-halved');
CREATE OR REPLACE CONCEPT `claim_amount` (`claim_identifier` integer, `claim_amount` decimal, `claim_offer_identifier` integer, `insurance_type_code` string, `event_date` timestamp, `amount_type_code` string, `claim_amount_identifier` bigint, PRIMARY KEY (`claim_amount_identifier`), CONSTRAINT `has_loss_reserve` FOREIGN KEY (`claim_amount_identifier`) REFERENCES `loss_reserve` (`claim_amount_identifier`) INVERSEOF `of_claim_amount` , CONSTRAINT `has_loss_payment` FOREIGN KEY (`claim_amount_identifier`) REFERENCES `loss_payment` (`claim_amount_identifier`) INVERSEOF `of_claim_amount` , CONSTRAINT `has_expense_payment` FOREIGN KEY (`claim_amount_identifier`) REFERENCES `expense_payment` (`claim_amount_identifier`) INVERSEOF `of_claim_amount` , CONSTRAINT `has_expense_reserve` FOREIGN KEY (`claim_amount_identifier`) REFERENCES `expense_reserve` (`claim_amount_identifier`) INVERSEOF `of_claim_amount` ) INHERITS (`thing`) DESCRIPTION 'This concept represents the amount details associated with an insurance claim, including the type and value of the claim amount.' WITH TAGS (`icon` = 'fa-money-bill-1-wave');
CREATE OR REPLACE CONCEPT `claim` (`company_subclaim_number` string, `entry_into_claims_made_program_date` timestamp, `insurable_object_identifier` integer, `claim_status_code` string, `claim_identifier` integer, `claim_open_date` timestamp, `company_claim_number` string, `catastrophe_identifier` integer, `occurrence_identifier` integer, `claim_reopen_date` timestamp, `claim_close_date` timestamp, `claim_reported_date` timestamp, `claim_description` string, `claims_made_date` timestamp, PRIMARY KEY (`claim_identifier`), CONSTRAINT `has_claim_coverage` FOREIGN KEY (`claim_identifier`) REFERENCES `claim_coverage` (`claim_identifier`) INVERSEOF `of_claim` , CONSTRAINT `has_catastrophe` FOREIGN KEY (`catastrophe_identifier`) REFERENCES `catastrophe` (`catastrophe_identifier`) INVERSEOF `of_claim` , CONSTRAINT `has_claim_amount` FOREIGN KEY (`claim_identifier`) REFERENCES `claim_amount` (`claim_identifier`) INVERSEOF `of_claim` , CONSTRAINT `has_policy_coverage_detail` FOREIGN KEY (`insurable_object_identifier`) REFERENCES `policy_coverage_detail` (`insurable_object_identifier`) INVERSEOF `of_claim` ) INHERITS (`thing`) DESCRIPTION 'This concept represents an insurance claim with details about the claim, the policyholder, and related information.' WITH TAGS (`icon` = 'fa-clipboard-check');
CREATE OR REPLACE CONCEPT `catastrophe` (`catastrophe_identifier` integer) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-warning');
CREATE OR REPLACE CONCEPT `agent` (`policy_identifier` integer) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-tie');