CREATE OR REPLACE PROPERTY `profession` MULTIVALUE string;
CREATE OR REPLACE PROPERTY `isadult` bigint;
CREATE OR REPLACE PROPERTY `deathyear` string;
CREATE OR REPLACE PROPERTY `birthyear` string;
CREATE OR REPLACE PROPERTY `nconst` string;
CREATE OR REPLACE PROPERTY `runtimeminutes` bigint;
CREATE OR REPLACE PROPERTY `media_genre` MULTIVALUE string;
CREATE OR REPLACE PROPERTY `primary_title` MULTIVALUE string;
CREATE OR REPLACE PROPERTY `numvotes` bigint;
CREATE OR REPLACE PROPERTY `primarytitle` string;
CREATE OR REPLACE PROPERTY `averagerating` float;
CREATE OR REPLACE PROPERTY `originaltitle` string;
CREATE OR REPLACE PROPERTY `titletype` string;
CREATE OR REPLACE PROPERTY `genres` MULTIVALUE string;
CREATE OR REPLACE PROPERTY `tconst` string;
CREATE OR REPLACE PROPERTY `primaryprofession` string;
CREATE OR REPLACE PROPERTY `primaryname` string;
CREATE OR REPLACE PROPERTY `startyear` bigint;
CREATE OR REPLACE PROPERTY `endyear` bigint;
CREATE OR REPLACE CONCEPT `rating` (`averagerating` float, `numvotes` bigint, `tconst` string, PRIMARY KEY (`tconst`), LABEL (`averagerating`), CONSTRAINT `primary_title` MULTIVALUE string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-medal');
CREATE OR REPLACE CONCEPT `media` (`primarytitle` string, `startyear` bigint, `isadult` bigint, `titletype` string, `originaltitle` string, `tconst` string, `runtimeminutes` bigint, `endyear` bigint, PRIMARY KEY (`tconst`), LABEL (`primarytitle`), CONSTRAINT `genres` MULTIVALUE string, CONSTRAINT `has_rating` FOREIGN KEY (`tconst`) REFERENCES `rating` (`tconst`) INVERSEOF `rating_of` ) INHERITS (`thing`) DESCRIPTION 'title_basics' WITH TAGS (`icon` = 'fa-television');
CREATE OR REPLACE CONCEPT `crew` (`primaryname` string, `birthyear` string, `deathyear` string, `tconst` string, `primaryprofession` string, `nconst` string, PRIMARY KEY (`nconst`), LABEL (`primaryname`), CONSTRAINT `profession` MULTIVALUE string, CONSTRAINT `known_with` MULTIREFERENCE `media` INVERSEOF `has_crew` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user');
CREATE OR REPLACE CONCEPT `video_game`  INHERITS (`media`) FROM dtimbr.`media` WHERE `titletype` = 'videoGame';
CREATE OR REPLACE CONCEPT `video`  INHERITS (`media`) FROM dtimbr.`media` WHERE `titletype` = 'video';
CREATE OR REPLACE CONCEPT `television`  INHERITS (`media`);
CREATE OR REPLACE CONCEPT `movie`  INHERITS (`media`) FROM dtimbr.`media` WHERE `titletype` IN ('movie', 'short', 'tvShort', 'tvMovie');
CREATE OR REPLACE CONCEPT `television_special`  INHERITS (`television`) FROM dtimbr.`media` WHERE `titletype` = 'tvSpecial';
CREATE OR REPLACE CONCEPT `television_movie`  INHERITS (`movie`, `television`) FROM dtimbr.`movie` WHERE `titletype` = 'tvMovie';
CREATE OR REPLACE CONCEPT `television_episode`  INHERITS (`television`) FROM dtimbr.`media` WHERE `titletype` = 'tvEpisode';
CREATE OR REPLACE CONCEPT `series` ( CONSTRAINT `has_episode` MULTIREFERENCE `television_episode` INVERSEOF `episode_of` ) INHERITS (`television`);
CREATE OR REPLACE CONCEPT `television_series`  INHERITS (`series`) FROM dtimbr.`media` WHERE `titletype` = 'tvSeries';
CREATE OR REPLACE CONCEPT `television_mini_series`  INHERITS (`series`) FROM timbr.`media` WHERE `titletype` = 'tvMiniSeries';
CREATE OR REPLACE CONCEPT `theater_movie`  INHERITS (`movie`) FROM timbr.`movie` WHERE `titletype` = 'movie';
CREATE OR REPLACE CONCEPT `television_movie`  INHERITS (`movie`, `television`) FROM dtimbr.`movie` WHERE `titletype` = 'tvMovie';
CREATE OR REPLACE CONCEPT `short_theater_movie`  INHERITS (`movie`) FROM timbr.`movie` WHERE `titletype` = 'short';
CREATE OR REPLACE CONCEPT `horror_movie`  INHERITS (`movie`) FROM timbr.`movie` WHERE `titletype` IN ('movie', 'short', 'tvShort', 'tvMovie');
CREATE OR REPLACE CONCEPT `drama_movie`  INHERITS (`movie`) FROM timbr.`movie` WHERE `titletype` IN ('movie', 'short', 'tvShort', 'tvMovie');
CREATE OR REPLACE CONCEPT `adventure_movie`  INHERITS (`movie`) FROM timbr.`movie` WHERE `titletype` IN ('movie', 'short', 'tvShort', 'tvMovie');
CREATE OR REPLACE CONCEPT `action_movie`  INHERITS (`movie`) FROM timbr.`movie` WHERE `titletype` IN ('movie', 'short', 'tvShort', 'tvMovie');
CREATE OR REPLACE CONCEPT `writer`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` = 'writer';
CREATE OR REPLACE CONCEPT `producer`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` = 'producer';
CREATE OR REPLACE CONCEPT `music_department`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` = 'music_department';
CREATE OR REPLACE CONCEPT `director`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` = 'director';
CREATE OR REPLACE CONCEPT `camera_department`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` = 'camera_department';
CREATE OR REPLACE CONCEPT `assistant_director`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` = 'assistant_director';
CREATE OR REPLACE CONCEPT `actor`  INHERITS (`crew`) FROM timbr.`crew` WHERE `primaryprofession` LIKE '%actor%' OR `primaryprofession` LIKE '%actress%';