CREATE OR REPLACE PROPERTY `end_date` date;
CREATE OR REPLACE PROPERTY `sale_id` integer;
CREATE OR REPLACE PROPERTY `supply_id` integer;
CREATE OR REPLACE PROPERTY `year` integer;
CREATE OR REPLACE PROPERTY `appointment_id` integer;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `feedback_id` integer;
CREATE OR REPLACE PROPERTY `recall_id` integer;
CREATE OR REPLACE PROPERTY `dealership_id` integer;
CREATE OR REPLACE PROPERTY `line_id` integer;
CREATE OR REPLACE PROPERTY `resolution` string;
CREATE OR REPLACE PROPERTY `capacity` integer;
CREATE OR REPLACE PROPERTY `manufacturer` string;
CREATE OR REPLACE PROPERTY `objective` string;
CREATE OR REPLACE PROPERTY `warranty_id` integer;
CREATE OR REPLACE PROPERTY `campaign_name` string;
CREATE OR REPLACE PROPERTY `sale_date` date;
CREATE OR REPLACE PROPERTY `service_date` date;
CREATE OR REPLACE PROPERTY `model` string;
CREATE OR REPLACE PROPERTY `vin` string;
CREATE OR REPLACE PROPERTY `coverage_details` string;
CREATE OR REPLACE PROPERTY `date_received` date;
CREATE OR REPLACE PROPERTY `part_id` integer;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `make` string;
CREATE OR REPLACE PROPERTY `vehicle_id` integer;
CREATE OR REPLACE PROPERTY `campaign_id` integer;
CREATE OR REPLACE PROPERTY `email` string;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `issue_description` string;
CREATE OR REPLACE PROPERTY `quantity` integer;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `recall_date` date;
CREATE OR REPLACE PROPERTY `feedback_text` string;
CREATE OR REPLACE PROPERTY `sale_price` decimal;
CREATE OR REPLACE PROPERTY `delivery_date` date;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `part_number` string;
CREATE OR REPLACE PROPERTY `location` string;
CREATE OR REPLACE PROPERTY `phone_number` string;
CREATE OR REPLACE PROPERTY `customer_id` integer;
CREATE OR REPLACE PROPERTY `order_id` integer;
CREATE OR REPLACE PROPERTY `supplier_id` integer;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE CONCEPT `warranty` (`end_date` date, `vehicle_id` integer, `warranty_id` integer, `coverage_details` string, `start_date` date, PRIMARY KEY (`warranty_id`), LABEL (`coverage_details`), CONSTRAINT `warranty_for_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`) INVERSEOF `~warranty_for_vehicle` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-shield-halved');
CREATE OR REPLACE CONCEPT `vehicle_sale` (`dealership_id` integer, `sale_date` date, `sale_id` integer, `sale_price` decimal, `vehicle_id` integer, PRIMARY KEY (`sale_id`), LABEL (`sale_id`), CONSTRAINT `sale_of_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`) INVERSEOF `~sale_of_vehicle` , CONSTRAINT `vehicle_sold_at_dealership` FOREIGN KEY (`dealership_id`) REFERENCES `sales_dealership` (`dealership_id`) INVERSEOF `~vehicle_sold_at_dealership` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-handshake');
CREATE OR REPLACE CONCEPT `vehicle` (`year` integer, `vin` string, `make` string, `vehicle_id` integer, `model` string, PRIMARY KEY (`vehicle_id`), LABEL (`model`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-car-side');
CREATE OR REPLACE CONCEPT `supplier` (`supplier_id` integer, `location` string, `name` string, PRIMARY KEY (`supplier_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-warehouse');
CREATE OR REPLACE CONCEPT `service_appointment` (`description` string, `service_date` date, `customer_id` integer, `appointment_id` integer, `vehicle_id` integer, PRIMARY KEY (`appointment_id`), LABEL (`service_date`), CONSTRAINT `vehicle_owned_by_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) INVERSEOF `~vehicle_owned_by_customer` , CONSTRAINT `service_for_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`) INVERSEOF `~service_for_vehicle` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-calendar-days');
CREATE OR REPLACE CONCEPT `sales_dealership` (`dealership_id` integer, `location` string, `name` string, PRIMARY KEY (`dealership_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-store-alt');
CREATE OR REPLACE CONCEPT `recall` (`recall_date` date, `recall_id` integer, `issue_description` string, `resolution` string, `part_id` integer, PRIMARY KEY (`recall_id`), LABEL (`issue_description`), CONSTRAINT `recall_for_part` FOREIGN KEY (`part_id`) REFERENCES `part` (`part_id`) INVERSEOF `~recall_for_part` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-warning');
CREATE OR REPLACE CONCEPT `production_order` (`line_id` integer, `status` string, `end_date` date, `vehicle_id` integer, `order_id` integer, `start_date` date, PRIMARY KEY (`order_id`), LABEL (`order_id`), CONSTRAINT `production_for_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`) INVERSEOF `~production_for_vehicle` , CONSTRAINT `production_on_line` FOREIGN KEY (`line_id`) REFERENCES `assembly_line` (`line_id`) INVERSEOF `~production_on_line` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-clipboard-list');
CREATE OR REPLACE CONCEPT `part_supply` (`quantity` integer, `supplier_id` integer, `delivery_date` date, `supply_id` integer, `part_id` integer, PRIMARY KEY (`supply_id`), LABEL (`supply_id`), CONSTRAINT `part_from_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`supplier_id`) INVERSEOF `~part_from_supplier` , CONSTRAINT `supply_for_part` FOREIGN KEY (`part_id`) REFERENCES `part` (`part_id`) INVERSEOF `~supply_for_part` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-truck-moving');
CREATE OR REPLACE CONCEPT `part` (`manufacturer` string, `vehicle_id` integer, `part_number` string, `name` string, `part_id` integer, PRIMARY KEY (`part_id`), LABEL (`name`), CONSTRAINT `part_for_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`) INVERSEOF `~part_for_vehicle` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-cog');
CREATE OR REPLACE CONCEPT `marketing_campaign` (`objective` string, `end_date` date, `campaign_name` string, `start_date` date, `campaign_id` integer, PRIMARY KEY (`campaign_id`), LABEL (`campaign_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bullhorn');
CREATE OR REPLACE CONCEPT `customer_feedback` (`feedback_id` integer, `customer_id` integer, `vehicle_id` integer, `date_received` date, `feedback_text` string, PRIMARY KEY (`feedback_id`), LABEL (`feedback_text`), CONSTRAINT `feedback_for_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`vehicle_id`) INVERSEOF `~feedback_for_vehicle` , CONSTRAINT `feedback_from_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) INVERSEOF `~feedback_from_customer` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-thumbs-up');
CREATE OR REPLACE CONCEPT `customer` (`phone_number` string, `last_name` string, `customer_id` integer, `email` string, `first_name` string, PRIMARY KEY (`customer_id`), LABEL (`first_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user');
CREATE OR REPLACE CONCEPT `assembly_line` (`line_id` integer, `capacity` integer, `location` string, PRIMARY KEY (`line_id`), LABEL (`location`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-grip-lines');