CREATE OR REPLACE PROPERTY `intervention_type` string;
CREATE OR REPLACE PROPERTY `reason` string;
CREATE OR REPLACE PROPERTY `biospec_description` string;
CREATE OR REPLACE PROPERTY `baseline_population` string;
CREATE OR REPLACE PROPERTY `lead_sponsor` string;
CREATE OR REPLACE PROPERTY `oversight` string;
CREATE OR REPLACE PROPERTY `default_assessment` string;
CREATE OR REPLACE PROPERTY `event_date_description` string;
CREATE OR REPLACE PROPERTY `state` string;
CREATE OR REPLACE PROPERTY `last_modified` date;
CREATE OR REPLACE PROPERTY `maximum_age` string;
CREATE OR REPLACE PROPERTY `number_of_nsae_subjects` integer;
CREATE OR REPLACE PROPERTY `p_value_description` string;
CREATE OR REPLACE PROPERTY `agreement` string;
CREATE OR REPLACE PROPERTY `result_group_id` integer;
CREATE OR REPLACE PROPERTY `last_update_posted_date` date;
CREATE OR REPLACE PROPERTY `design_group_id` integer;
CREATE OR REPLACE PROPERTY `document_date` date;
CREATE OR REPLACE PROPERTY `lead_or_collaborator` string;
CREATE OR REPLACE PROPERTY `population` string;
CREATE OR REPLACE PROPERTY `mesh_term` string;
CREATE OR REPLACE PROPERTY `responsible_party_organization` string;
CREATE OR REPLACE PROPERTY `param_value_num` decimal;
CREATE OR REPLACE PROPERTY `study_type` string;
CREATE OR REPLACE PROPERTY `dispersion_value` string;
CREATE OR REPLACE PROPERTY `p_completion_year` string;
CREATE OR REPLACE PROPERTY `observational_model` string;
CREATE OR REPLACE PROPERTY `device` string;
CREATE OR REPLACE PROPERTY `ci_upper_limit_na_comment` string;
CREATE OR REPLACE PROPERTY `is_us_export` boolean;
CREATE OR REPLACE PROPERTY `param_value` string;
CREATE OR REPLACE PROPERTY `primary_completion_month_year` string;
CREATE OR REPLACE PROPERTY `role` string;
CREATE OR REPLACE PROPERTY `time_perspective` string;
CREATE OR REPLACE PROPERTY `has_us_facility` boolean;
CREATE OR REPLACE PROPERTY `overall_status` string;
CREATE OR REPLACE PROPERTY `is_fda_regulated_drug` boolean;
CREATE OR REPLACE PROPERTY `results_first_posted_date` date;
CREATE OR REPLACE PROPERTY `subjects_at_risk` integer;
CREATE OR REPLACE PROPERTY `updated_at` date;
CREATE OR REPLACE PROPERTY `ipd_time_frame` string;
CREATE OR REPLACE PROPERTY `has_dmc` boolean;
CREATE OR REPLACE PROPERTY `term` string;
CREATE OR REPLACE PROPERTY `collaborator_names` string;
CREATE OR REPLACE PROPERTY `is_ppsd` boolean;
CREATE OR REPLACE PROPERTY `p_comp_yr` string;
CREATE OR REPLACE PROPERTY `email` string;
CREATE OR REPLACE PROPERTY `genetic` string;
CREATE OR REPLACE PROPERTY `minimum_age_unit` string;
CREATE OR REPLACE PROPERTY `verification_month_year` string;
CREATE OR REPLACE PROPERTY `enrollment_type` string;
CREATE OR REPLACE PROPERTY `gender_description` string;
CREATE OR REPLACE PROPERTY `procedure` string;
CREATE OR REPLACE PROPERTY `investigator_masked` boolean;
CREATE OR REPLACE PROPERTY `t2result_imp` string;
CREATE OR REPLACE PROPERTY `default_vocab` string;
CREATE OR REPLACE PROPERTY `received_year` string;
CREATE OR REPLACE PROPERTY `non_inferiority_type` string;
CREATE OR REPLACE PROPERTY `other_analysis_description` string;
CREATE OR REPLACE PROPERTY `completion_date_type` string;
CREATE OR REPLACE PROPERTY `plan_to_share_ipd_description` string;
CREATE OR REPLACE PROPERTY `country` string;
CREATE OR REPLACE PROPERTY `pi_employee` string;
CREATE OR REPLACE PROPERTY `ci_n_sides` string;
CREATE OR REPLACE PROPERTY `firstreceived_results_dt` string;
CREATE OR REPLACE PROPERTY `last_update_submitted_date` date;
CREATE OR REPLACE PROPERTY `outcomes_assessor_masked` boolean;
CREATE OR REPLACE PROPERTY `ci_lower_limit` decimal;
CREATE OR REPLACE PROPERTY `group_type` string;
CREATE OR REPLACE PROPERTY `source` string;
CREATE OR REPLACE PROPERTY `document_id` string;
CREATE OR REPLACE PROPERTY `last_update_submitted_qc_date` date;
CREATE OR REPLACE PROPERTY `masking_description` string;
CREATE OR REPLACE PROPERTY `assessment` string;
CREATE OR REPLACE PROPERTY `official_title` string;
CREATE OR REPLACE PROPERTY `affiliation` string;
CREATE OR REPLACE PROPERTY `t2result` string;
CREATE OR REPLACE PROPERTY `event_date` date;
CREATE OR REPLACE PROPERTY `sponsor_name` string;
CREATE OR REPLACE PROPERTY `results` string;
CREATE OR REPLACE PROPERTY `number_of_arms` integer;
CREATE OR REPLACE PROPERTY `number_of_primary_outcomes_to_measure` integer;
CREATE OR REPLACE PROPERTY `nct_id` string;
CREATE OR REPLACE PROPERTY `count` integer;
CREATE OR REPLACE PROPERTY `dispersion_upper_limit` decimal;
CREATE OR REPLACE PROPERTY `param_type` string;
CREATE OR REPLACE PROPERTY `measure` string;
CREATE OR REPLACE PROPERTY `anticipated_posting_month_year` string;
CREATE OR REPLACE PROPERTY `healthy_volunteers` string;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `outcome_type` string;
CREATE OR REPLACE PROPERTY `start_month` string;
CREATE OR REPLACE PROPERTY `verification_month` string;
CREATE OR REPLACE PROPERTY `intervg1` string;
CREATE OR REPLACE PROPERTY `organ_system` string;
CREATE OR REPLACE PROPERTY `resultsreceived_month` string;
CREATE OR REPLACE PROPERTY `subcategory` string;
CREATE OR REPLACE PROPERTY `dispersion_value_num` decimal;
CREATE OR REPLACE PROPERTY `registered_in_calendar_year` integer;
CREATE OR REPLACE PROPERTY `plan_to_share_ipd` string;
CREATE OR REPLACE PROPERTY `brief_title` string;
CREATE OR REPLACE PROPERTY `event_count` integer;
CREATE OR REPLACE PROPERTY `downcase_name` string;
CREATE OR REPLACE PROPERTY `number_of_sae_subjects` integer;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `study_first_posted_date` date;
CREATE OR REPLACE PROPERTY `title` string;
CREATE OR REPLACE PROPERTY `p_value_modifier` float;
CREATE OR REPLACE PROPERTY `sampling_method` string;
CREATE OR REPLACE PROPERTY `primary_completion_date` date;
CREATE OR REPLACE PROPERTY `behavioral` string;
CREATE OR REPLACE PROPERTY `scope` string;
CREATE OR REPLACE PROPERTY `vocab` string;
CREATE OR REPLACE PROPERTY `has_protocol` boolean;
CREATE OR REPLACE PROPERTY `estimate_description` string;
CREATE OR REPLACE PROPERTY `completion_month_year` string;
CREATE OR REPLACE PROPERTY `outcome_id` integer;
CREATE OR REPLACE PROPERTY `allocation` string;
CREATE OR REPLACE PROPERTY `citation` string;
CREATE OR REPLACE PROPERTY `has_icf` boolean;
CREATE OR REPLACE PROPERTY `disposition_first_submitted_qc_date` date;
CREATE OR REPLACE PROPERTY `why_stopped` string;
CREATE OR REPLACE PROPERTY `disposition_first_posted_date` date;
CREATE OR REPLACE PROPERTY `completion_month` string;
CREATE OR REPLACE PROPERTY `otherint` string;
CREATE OR REPLACE PROPERTY `adverse_event_term` string;
CREATE OR REPLACE PROPERTY `minimum_age_num` integer;
CREATE OR REPLACE PROPERTY `comment` string;
CREATE OR REPLACE PROPERTY `number_of_facilities` integer;
CREATE OR REPLACE PROPERTY `mntopcom` string;
CREATE OR REPLACE PROPERTY `caregiver_masked` boolean;
CREATE OR REPLACE PROPERTY `criteria` string;
CREATE OR REPLACE PROPERTY `study_first_submitted_qc_date` date;
CREATE OR REPLACE PROPERTY `delayed` string;
CREATE OR REPLACE PROPERTY `disposition_first_submitted_date` date;
CREATE OR REPLACE PROPERTY `number_of_groups` integer;
CREATE OR REPLACE PROPERTY `resultsreceived_year` string;
CREATE OR REPLACE PROPERTY `frequency_threshold` integer;
CREATE OR REPLACE PROPERTY `were_results_reported` boolean;
CREATE OR REPLACE PROPERTY `delayed12` string;
CREATE OR REPLACE PROPERTY `event_type` string;
CREATE OR REPLACE PROPERTY `nlm_download_date` date;
CREATE OR REPLACE PROPERTY `recruitment_details` string;
CREATE OR REPLACE PROPERTY `id` integer;
CREATE OR REPLACE PROPERTY `results12` string;
CREATE OR REPLACE PROPERTY `phase` string;
CREATE OR REPLACE PROPERTY `zip` string;
CREATE OR REPLACE PROPERTY `number_of_secondary_outcomes_to_measure` integer;
CREATE OR REPLACE PROPERTY `period` string;
CREATE OR REPLACE PROPERTY `method` string;
CREATE OR REPLACE PROPERTY `p_comp_mn` string;
CREATE OR REPLACE PROPERTY `ci_upper_limit` decimal;
CREATE OR REPLACE PROPERTY `agency_classc` string;
CREATE OR REPLACE PROPERTY `classification` string;
CREATE OR REPLACE PROPERTY `grouping` string;
CREATE OR REPLACE PROPERTY `results_first_submitted_qc_date` date;
CREATE OR REPLACE PROPERTY `has_sap` boolean;
CREATE OR REPLACE PROPERTY `expanded_access_type_individual` boolean;
CREATE OR REPLACE PROPERTY `phone` string;
CREATE OR REPLACE PROPERTY `qualifier` string;
CREATE OR REPLACE PROPERTY `biological` string;
CREATE OR REPLACE PROPERTY `start_month_year` string;
CREATE OR REPLACE PROPERTY `dietsup` string;
CREATE OR REPLACE PROPERTY `maximum_age_num` integer;
CREATE OR REPLACE PROPERTY `study_first_submitted_date` date;
CREATE OR REPLACE PROPERTY `downcase_preferred_name` string;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE PROPERTY `responsible_party_type` string;
CREATE OR REPLACE PROPERTY `gender` string;
CREATE OR REPLACE PROPERTY `city` string;
CREATE OR REPLACE PROPERTY `method_description` string;
CREATE OR REPLACE PROPERTY `created_at` date;
CREATE OR REPLACE PROPERTY `expanded_access_type_intermediate` boolean;
CREATE OR REPLACE PROPERTY `phasec` string;
CREATE OR REPLACE PROPERTY `start_date_type` string;
CREATE OR REPLACE PROPERTY `dispersion_lower_limit` decimal;
CREATE OR REPLACE PROPERTY `subject_masked` boolean;
CREATE OR REPLACE PROPERTY `minimum_age` string;
CREATE OR REPLACE PROPERTY `anticipated_posting_date` date;
CREATE OR REPLACE PROPERTY `biospec_retention` string;
CREATE OR REPLACE PROPERTY `id_type` string;
CREATE OR REPLACE PROPERTY `event` string;
CREATE OR REPLACE PROPERTY `expanded_access_type_treatment` boolean;
CREATE OR REPLACE PROPERTY `results_first_submitted_date` date;
CREATE OR REPLACE PROPERTY `id_value` string;
CREATE OR REPLACE PROPERTY `document_type` string;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `limitations_and_caveats` string;
CREATE OR REPLACE PROPERTY `p_value` float;
CREATE OR REPLACE PROPERTY `funding` string;
CREATE OR REPLACE PROPERTY `masking` string;
CREATE OR REPLACE PROPERTY `acronym` string;
CREATE OR REPLACE PROPERTY `heading` string;
CREATE OR REPLACE PROPERTY `non_inferiority_description` string;
CREATE OR REPLACE PROPERTY `units_analyze` string;
CREATE OR REPLACE PROPERTY `t2resmod` string;
CREATE OR REPLACE PROPERTY `reference_type` string;
CREATE OR REPLACE PROPERTY `url` string;
CREATE OR REPLACE PROPERTY `removed` boolean;
CREATE OR REPLACE PROPERTY `ipd_url` string;
CREATE OR REPLACE PROPERTY `organization` string;
CREATE OR REPLACE PROPERTY `completion_date` date;
CREATE OR REPLACE PROPERTY `primary_completion_date_type` string;
CREATE OR REPLACE PROPERTY `verification_date` date;
CREATE OR REPLACE PROPERTY `intervention_id` integer;
CREATE OR REPLACE PROPERTY `maximum_age_unit` string;
CREATE OR REPLACE PROPERTY `time_frame` string;
CREATE OR REPLACE PROPERTY `nlm_download_date_description` string;
CREATE OR REPLACE PROPERTY `us_coderc` string;
CREATE OR REPLACE PROPERTY `drug` string;
CREATE OR REPLACE PROPERTY `explanation_of_na` string;
CREATE OR REPLACE PROPERTY `completion_year` string;
CREATE OR REPLACE PROPERTY `overall_statusc` string;
CREATE OR REPLACE PROPERTY `facility_id` integer;
CREATE OR REPLACE PROPERTY `is_unapproved_device` boolean;
CREATE OR REPLACE PROPERTY `has_expanded_access` boolean;
CREATE OR REPLACE PROPERTY `intervention_model_description` string;
CREATE OR REPLACE PROPERTY `mn2delay` string;
CREATE OR REPLACE PROPERTY `primary_purpose` string;
CREATE OR REPLACE PROPERTY `ctgov_group_code` string;
CREATE OR REPLACE PROPERTY `number_of_other_outcomes_to_measure` integer;
CREATE OR REPLACE PROPERTY `max_age_in_years` float;
CREATE OR REPLACE PROPERTY `is_fda_regulated_device` boolean;
CREATE OR REPLACE PROPERTY `outcome_analysis_id` integer;
CREATE OR REPLACE PROPERTY `last_known_status` string;
CREATE OR REPLACE PROPERTY `preferred_name` string;
CREATE OR REPLACE PROPERTY `gender_based` boolean;
CREATE OR REPLACE PROPERTY `min_age_in_years` float;
CREATE OR REPLACE PROPERTY `pre_assignment_details` string;
CREATE OR REPLACE PROPERTY `p_completion_month` string;
CREATE OR REPLACE PROPERTY `start_year` string;
CREATE OR REPLACE PROPERTY `units` string;
CREATE OR REPLACE PROPERTY `contact_type` string;
CREATE OR REPLACE PROPERTY `dispersion_type` string;
CREATE OR REPLACE PROPERTY `verification_year` string;
CREATE OR REPLACE PROPERTY `has_single_facility` boolean;
CREATE OR REPLACE PROPERTY `actual_duration` integer;
CREATE OR REPLACE PROPERTY `result_type` string;
CREATE OR REPLACE PROPERTY `agency_class` string;
CREATE OR REPLACE PROPERTY `subjects_affected` integer;
CREATE OR REPLACE PROPERTY `months_to_report_results` integer;
CREATE OR REPLACE PROPERTY `ipd_access_criteria` string;
CREATE OR REPLACE PROPERTY `pmid` string;
CREATE OR REPLACE PROPERTY `downcase_mesh_term` string;
CREATE OR REPLACE PROPERTY `enrollment` integer;
CREATE OR REPLACE PROPERTY `target_duration` string;
CREATE OR REPLACE PROPERTY `dr_received_dt` string;
CREATE OR REPLACE PROPERTY `groups_description` string;
CREATE OR REPLACE PROPERTY `radiation` string;
CREATE OR REPLACE PROPERTY `intervention_model` string;
CREATE OR REPLACE PROPERTY `category` string;
CREATE OR REPLACE PROPERTY `ci_percent` decimal;
CREATE OR REPLACE PROPERTY `term_type` string;
CREATE OR REPLACE PROPERTY `tree_number` string;
CREATE OR REPLACE CONCEPT `tagged_terms` (`id` integer, `term` string, `term_type` string, PRIMARY KEY (`id`)) INHERITS (`thing`) DESCRIPTION 'Table of terms determined to be nephrology-related by a team of Duke clinicians. The source of the terms is the 2010 MeSH thesaurus as well as free-string terms/phrases used to identify interventional studies registered in ClinicalTrials.gov between 2007 and 2010.';
CREATE OR REPLACE CONCEPT `study_references` (`citation` string, `id` integer, `reference_type` string, `nct_id` string, `pmid` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_study_references` ) INHERITS (`thing`) DESCRIPTION 'Citations to publications related to the study protocol and/or results. Includes PubMed Unique Identifier (PMID) and/or full bibliographic citation. ';
CREATE OR REPLACE CONCEPT `studies` (`number_of_groups` integer, `is_fda_regulated_drug` boolean, `disposition_first_submitted_date` date, `study_first_submitted_qc_date` date, `start_month_year` string, `disposition_first_submitted_qc_date` date, `acronym` string, `enrollment` integer, `created_at` date, `biospec_retention` string, `completion_date_type` string, `updated_at` date, `last_update_submitted_qc_date` date, `verification_month_year` string, `nct_id` string, `primary_completion_month_year` string, `phase` string, `official_title` string, `plan_to_share_ipd_description` string, `primary_completion_date` date, `plan_to_share_ipd` string, `disposition_first_posted_date` date, `primary_completion_date_type` string, `biospec_description` string, `study_first_posted_date` date, `start_date_type` string, `why_stopped` string, `has_dmc` boolean, `completion_month_year` string, `expanded_access_type_individual` boolean, `expanded_access_type_intermediate` boolean, `nlm_download_date_description` string, `ipd_url` string, `has_expanded_access` boolean, `is_ppsd` boolean, `completion_date` date, `ipd_time_frame` string, `last_update_posted_date` date, `overall_status` string, `results_first_submitted_date` date, `study_first_submitted_date` date, `enrollment_type` string, `number_of_arms` integer, `start_date` date, `study_type` string, `last_update_submitted_date` date, `limitations_and_caveats` string, `target_duration` string, `verification_date` date, `ipd_access_criteria` string, `baseline_population` string, `is_unapproved_device` boolean, `results_first_submitted_qc_date` date, `expanded_access_type_treatment` boolean, `is_fda_regulated_device` boolean, `source` string, `last_known_status` string, `results_first_posted_date` date, `brief_title` string, `is_us_export` boolean, PRIMARY KEY (`nct_id`)) INHERITS (`thing`) DESCRIPTION 'Basic info about study, including study title, date study registered with ClinicalTrials.gov, date results first posted to ClinicalTrials.gov, dates for study start and completion, phase of study, enrollment status, planned or actual enrollment, number of study arms/groups, etc.';
CREATE OR REPLACE CONCEPT `sponsors` (`id` integer, `nct_id` string, `name` string, `agency_class` string, `lead_or_collaborator` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_sponsors` ) INHERITS (`thing`) DESCRIPTION 'Name of study sponsors and collaborators. The sponsor is the entity or individual initiating the study. Collaborators are other organizations providing support, including funding, design, implementation, data analysis, and reporting.';
CREATE OR REPLACE CONCEPT `result_groups` (`result_type` string, `description` string, `ctgov_group_code` string, `id` integer, `title` string, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_result_groups` ) INHERITS (`thing`) DESCRIPTION 'Consolidated, aggregate list of group titles/descriptions used for reporting summary results information.';
CREATE OR REPLACE CONCEPT `result_contacts` (`phone` string, `id` integer, `organization` string, `nct_id` string, `email` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_` ) INHERITS (`thing`) DESCRIPTION 'Point of contact for scientific information about the clinical study results information. ';
CREATE OR REPLACE CONCEPT `result_agreements` (`id` integer, `nct_id` string, `pi_employee` string, `agreement` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_result_agreements` ) INHERITS (`thing`) DESCRIPTION 'Info about whether an agreement exists between the sponsor & the principal investigators (PIs) that restricts the PIs ability to discuss study results at scientific meetings or other public or private forums, or to publish info concerning the study in scientific or academic journals after the study is completed.';
CREATE OR REPLACE CONCEPT `responsible_parties` (`id` integer, `organization` string, `affiliation` string, `title` string, `nct_id` string, `responsible_party_type` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_responsible_parties` ) INHERITS (`thing`) DESCRIPTION 'People who have access to and control over the data from the study, have the right to publish study results, and have the ability to meet all of the requirements for the submission of study information. ';
CREATE OR REPLACE CONCEPT `reported_events` (`vocab` string, `default_vocab` string, `ctgov_group_code` string, `time_frame` string, `id` integer, `result_group_id` integer, `adverse_event_term` string, `event_type` string, `nct_id` string, `frequency_threshold` integer, `default_assessment` string, `description` string, `event_count` integer, `organ_system` string, `assessment` string, `subjects_at_risk` integer, `subjects_affected` integer, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_reported_events` , CONSTRAINT `of_result_groups` FOREIGN KEY (`result_group_id`) REFERENCES `result_groups` (`id`) INVERSEOF `rel_result_groups_reported_events` ) INHERITS (`thing`) DESCRIPTION 'summary information about reported adverse events (any untoward or unfavorable medical occurrence to participants, including abnormal physical exams, laboratory findings, symptoms, or diseases), including serious adverse events, other adverse events, and mortality.';
CREATE OR REPLACE CONCEPT `provided_documents` (`document_date` date, `has_sap` boolean, `document_type` string, `id` integer, `has_icf` boolean, `url` string, `has_protocol` boolean, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_provided_documents` ) INHERITS (`thing`) DESCRIPTION 'The full study protocol and statistical analysis plan must be uploaded as part of results information submission, for studies with a Primary Completion Date on or after January 18, 2017. The protocol and statistical analysis plan may be optionally uploaded before results information submission and updated with new versions, as needed. Informed consent forms may optionally be uploaded at any time. ';
CREATE OR REPLACE CONCEPT `pending_results` (`id` integer, `event` string, `event_date_description` string, `nct_id` string, `event_date` date, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_pending_results` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `participant_flows` (`recruitment_details` string, `id` integer, `nct_id` string, `pre_assignment_details` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_participant_flows` ) INHERITS (`thing`) DESCRIPTION 'Recruitment information relevant to the recruitment process & pre-assignment details (ie. significant events in the study that occur after participant enrollment, but prior to assignment of participants).  Information about participant flow that applies to all milestones.';
CREATE OR REPLACE CONCEPT `overall_officials` (`id` integer, `role` string, `affiliation` string, `nct_id` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_overall_officials` ) INHERITS (`thing`) DESCRIPTION 'People responsible for the overall scientific leadership of the protocol including the principal investigator.';
CREATE OR REPLACE CONCEPT `outcome_measurements` (`units` string, `category` string, `param_value` string, `ctgov_group_code` string, `id` integer, `dispersion_value_num` decimal, `outcome_id` integer, `result_group_id` integer, `param_value_num` decimal, `nct_id` string, `explanation_of_na` string, `dispersion_lower_limit` decimal, `dispersion_upper_limit` decimal, `description` string, `title` string, `dispersion_value` string, `param_type` string, `dispersion_type` string, `classification` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_outcome_measurements` , CONSTRAINT `of_outcomes` FOREIGN KEY (`outcome_id`) REFERENCES `outcomes` (`id`) INVERSEOF `rel_outcomes_outcome_measurements` , CONSTRAINT `of_result_groups` FOREIGN KEY (`result_group_id`) REFERENCES `result_groups` (`id`) INVERSEOF `rel_result_groups_outcome_measurements` ) INHERITS (`thing`) DESCRIPTION 'summary data for primary and secondary outcome measures for each study group. Includes parameter estimates and measures of dispersion/precision.';
CREATE OR REPLACE CONCEPT `outcome_counts` (`count` integer, `units` string, `ctgov_group_code` string, `id` integer, `outcome_id` integer, `result_group_id` integer, `scope` string, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_outcome_counts` , CONSTRAINT `of_outcomes` FOREIGN KEY (`outcome_id`) REFERENCES `outcomes` (`id`) INVERSEOF `rel_outcomes_outcome_counts` , CONSTRAINT `of_result_groups` FOREIGN KEY (`result_group_id`) REFERENCES `result_groups` (`id`) INVERSEOF `rel_result_groups_outcome_counts` ) INHERITS (`thing`) DESCRIPTION 'sample size included in analysis for each outcome for each study group; usually participants but can represent other units of measure such as eyes lesions, etc.';
CREATE OR REPLACE CONCEPT `outcome_analysis_groups` (`ctgov_group_code` string, `id` integer, `result_group_id` integer, `outcome_analysis_id` integer, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_outcome_analysis_groups` , CONSTRAINT `of_outcomes` FOREIGN KEY (`outcome_analysis_id`) REFERENCES `outcomes` (`id`) INVERSEOF `rel_outcomes_outcome_analysis_groups` , CONSTRAINT `of_result_groups` FOREIGN KEY (`result_group_id`) REFERENCES `result_groups` (`id`) INVERSEOF `rel_result_groups_outcome_analysis_groups` ) INHERITS (`thing`) DESCRIPTION 'Identifies the comparison groups that were involved with each outcome analysis';
CREATE OR REPLACE CONCEPT `outcome_analyses` (`method_description` string, `method` string, `param_value` string, `id` integer, `non_inferiority_description` string, `other_analysis_description` string, `outcome_id` integer, `ci_n_sides` string, `groups_description` string, `ci_percent` decimal, `ci_upper_limit_na_comment` string, `nct_id` string, `p_value_description` string, `ci_lower_limit` decimal, `p_value` float, `non_inferiority_type` string, `ci_upper_limit` decimal, `estimate_description` string, `dispersion_value` string, `param_type` string, `dispersion_type` string, `p_value_modifier` float, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_outcome_analyses` , CONSTRAINT `of_outcomes` FOREIGN KEY (`outcome_id`) REFERENCES `outcomes` (`id`) INVERSEOF `rel_outcomes_outcome_analyses` ) INHERITS (`thing`) DESCRIPTION 'Results of scientifically appropriate statistical analyses performed on primary and secondary study outcomes. Includes results for treatment effect estimates, confidence intervals and othe rmeasures of dispersion, and p-values.';
CREATE OR REPLACE CONCEPT `outcomes` (`units` string, `time_frame` string, `id` integer, `anticipated_posting_month_year` string, `nct_id` string, `description` string, `title` string, `population` string, `outcome_type` string, `units_analyze` string, `param_type` string, `dispersion_type` string, `anticipated_posting_date` date, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_outcomes` ) INHERITS (`thing`) DESCRIPTION 'Descriptions of outcomes, or observation that were measured to determine patterns of diseases or traits, or associations with exposures, risk factors, or treatment. Includes information such as time frame, population and units.  (Specific measurement results are stored in the Outcome_Measurements table.)';
CREATE OR REPLACE CONCEPT `oncology_studies`  INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `milestones` (`description` string, `count` integer, `ctgov_group_code` string, `id` integer, `result_group_id` integer, `title` string, `period` string, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_milestones` , CONSTRAINT `rel_milestones_result_groups` FOREIGN KEY (`result_group_id`) REFERENCES `result_groups` (`id`) INVERSEOF `rel_result_groups_milestones` ) INHERITS (`thing`) DESCRIPTION 'Information summarizing the progress of participants through each stage of a study, including the number of participants who started and completed the trial. Enumeration of participants not completing the study is included in the Drop_Withdrawals table.';
CREATE OR REPLACE CONCEPT `mesh_terms` (`description` string, `mesh_term` string, `id` integer, `tree_number` string, `qualifier` string, `downcase_mesh_term` string, PRIMARY KEY (`id`)) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `mesh_headings` (`heading` string, `id` integer, `subcategory` string, `qualifier` string, PRIMARY KEY (`id`)) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `mental_health_studies`  INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `links` (`description` string, `id` integer, `url` string, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_links` ) INHERITS (`thing`) DESCRIPTION 'Web site directly relevant to the protocol.  (ie, links to educational, research, government, and other non-profit Web pages)';
CREATE OR REPLACE CONCEPT `keywords` (`downcase_name` string, `id` integer, `nct_id` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_keywords` ) INHERITS (`thing`) DESCRIPTION 'Provides words or phrases that best describe the protocol. Keywords help users find studies in the database. Can include NLMs Medical Subject Heading (MeSH)-controlled vocabulary terms.';
CREATE OR REPLACE CONCEPT `ipd_information_types` (`id` integer, `nct_id` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_ipd_information_types` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `intervention_other_names` (`id` integer, `nct_id` string, `name` string, `intervention_id` integer, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_intervention_other_names` ) INHERITS (`thing`) DESCRIPTION 'Terns or phrases that are synonymous with an intervention.  (Each row is linked to one of the interventions associated with the study.)';
CREATE OR REPLACE CONCEPT `interventions` (`description` string, `id` integer, `intervention_type` string, `nct_id` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_interventions` ) INHERITS (`thing`) DESCRIPTION 'The interventions or exposures (including drugs, medical devices, procedures, vaccines, and other products) of interest to the study, or associated with study arms/groups.';
CREATE OR REPLACE CONCEPT `id_information` (`id` integer, `id_type` string, `id_value` string, `nct_id` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_id_information` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `facility_investigators` (`id` integer, `facility_id` integer, `role` string, `nct_id` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_facility_investigators` , CONSTRAINT `of_facility` FOREIGN KEY (`facility_id`) REFERENCES `facilities` (`id`) INVERSEOF `rel_facilities_facility_investigators` ) INHERITS (`thing`) DESCRIPTION 'Names of the investigators at each study facility.  Facility investigator information is available if the facility status (Facilities.Status) is ‘Recruiting’ or ‘Not yet recruiting’, and if the data provider has provided such information. Investigator information is removed from the publicly available content at ClinicalTrials.gov when the facility is no longer recruiting, or when the overall study status (Studies.Overall_status) changes to indicate that the study has completed recruitment.';
CREATE OR REPLACE CONCEPT `facility_contacts` (`phone` string, `id` integer, `contact_type` string, `facility_id` integer, `nct_id` string, `email` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_facility_contacts` , CONSTRAINT `of_facility` FOREIGN KEY (`facility_id`) REFERENCES `facilities` (`id`) INVERSEOF `rel_facilities_facility_contacts` ) INHERITS (`thing`) DESCRIPTION 'Contact information for people responsible for the study at each facility. (primary and backup)  Facility contact information is available if the facility status (Facilities.Status) is ‘Recruiting’ or ‘Not yet recruiting’, and if the data provider has provided such information. Contact information is removed from the publicly available content at ClinicalTrials.gov when the facility is no longer recruiting, or when the overall study status (Studies.Overall_status) changes to indicate that the study has completed recruitment.';
CREATE OR REPLACE CONCEPT `facilities` (`state` string, `id` integer, `status` string, `nct_id` string, `zip` string, `city` string, `country` string, `name` string, PRIMARY KEY (`id`), CONSTRAINT `of_studies` FOREIGN KEY (`nct_id`) REFERENCES `studies` (`nct_id`) INVERSEOF `rel_studies_facilities` ) INHERITS (`thing`) DESCRIPTION 'Name, address and recruiting status of the facilities participating in the study.';
CREATE OR REPLACE CONCEPT `eligibilities` (`criteria` string, `gender_based` boolean, `gender_description` string, `