CREATE OR REPLACE PROPERTY `identifier` string;
CREATE OR REPLACE PROPERTY `lastoccurence` string;
CREATE OR REPLACE PROPERTY `recorder` string;
CREATE OR REPLACE PROPERTY `display` string;
CREATE OR REPLACE PROPERTY `substance` string;
CREATE OR REPLACE PROPERTY `criticality` string;
CREATE OR REPLACE PROPERTY `link` string;
CREATE OR REPLACE PROPERTY `reporter` string;
CREATE OR REPLACE PROPERTY `type` string;
CREATE OR REPLACE PROPERTY `coding` string;
CREATE OR REPLACE PROPERTY `patient` string;
CREATE OR REPLACE PROPERTY `recordeddate` string;
CREATE OR REPLACE PROPERTY `resource_id` string;
CREATE OR REPLACE PROPERTY `comment` string;
CREATE OR REPLACE PROPERTY `id` string;
CREATE OR REPLACE PROPERTY `text` string;
CREATE OR REPLACE PROPERTY `category` string;
CREATE OR REPLACE PROPERTY `event` string;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE CONCEPT `vocabulary` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bootstrap');
CREATE OR REPLACE CONCEPT `unconfirmed` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-question-circle');
CREATE OR REPLACE CONCEPT `resourcecontainer` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-archive');
CREATE OR REPLACE CONCEPT `resource` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-cloud-arrow-up');
CREATE OR REPLACE CONCEPT `resolved` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-lock');
CREATE OR REPLACE CONCEPT `refuted` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-link-slash');
CREATE OR REPLACE CONCEPT `inline` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-link');
CREATE OR REPLACE CONCEPT `inactive` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-pause-circle');
CREATE OR REPLACE CONCEPT `element` (`resource_id` string, `id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-square');
CREATE OR REPLACE CONCEPT `confirmed` (`resource_id` string) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-check-circle');
CREATE OR REPLACE CONCEPT `valuesets`  INHERITS (`vocabulary`);
CREATE OR REPLACE CONCEPT `testindividuals`  INHERITS (`vocabulary`);
CREATE OR REPLACE CONCEPT `concepts`  INHERITS (`vocabulary`);
CREATE OR REPLACE CONCEPT `substance_coded`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `substance_codeb`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `search_entry_mode`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `quantity_comparator`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `narrative_status`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `medication_order_status`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `identifieruse`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `http_verb`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `criticality`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `bundle_type`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `allergy_intolerance_type`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `allergy_intolerance_status`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `allergy_intolerance_criticality`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `allergy_intolerance_category`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `allergyintolerance_substance_code`  INHERITS (`valuesets`);
CREATE OR REPLACE CONCEPT `generated`  INHERITS (`narrative_status`);
CREATE OR REPLACE CONCEPT `extensions`  INHERITS (`narrative_status`);
CREATE OR REPLACE CONCEPT `empty`  INHERITS (`narrative_status`);
CREATE OR REPLACE CONCEPT `additional`  INHERITS (`narrative_status`);
CREATE OR REPLACE CONCEPT `usual`  INHERITS (`identifieruse`);
CREATE OR REPLACE CONCEPT `secondary`  INHERITS (`identifieruse`);
CREATE OR REPLACE CONCEPT `official`  INHERITS (`identifieruse`);
CREATE OR REPLACE CONCEPT `medium`  INHERITS (`criticality`);
CREATE OR REPLACE CONCEPT `low`  INHERITS (`concept`, `criticality`);
CREATE OR REPLACE CONCEPT `high`  INHERITS (`concept`, `criticality`);
CREATE OR REPLACE CONCEPT `fatal`  INHERITS (`criticality`);
CREATE OR REPLACE CONCEPT `concept`  INHERITS (`concepts`);
CREATE OR REPLACE CONCEPT `unassessible`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `superseded`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `stopped`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `on_hold`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `non_immune`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `medication`  INHERITS (`domainresource`, `concept`);
CREATE OR REPLACE CONCEPT `low`  INHERITS (`concept`, `criticality`);
CREATE OR REPLACE CONCEPT `immune`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `high`  INHERITS (`concept`, `criticality`);
CREATE OR REPLACE CONCEPT `environment`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `entered_in_error`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `draft`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `completed`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `active`  INHERITS (`concept`);
CREATE OR REPLACE CONCEPT `domainresource` (`text` string) INHERITS (`resource`);
CREATE OR REPLACE CONCEPT `bundle`  INHERITS (`resource`);
CREATE OR REPLACE CONCEPT `relatedperson`  INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `practitioner`  INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `patient`  INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `observation`  INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `medicationorder` (`patient` string, CONSTRAINT `patient` FOREIGN KEY (`patient`) REFERENCES `reference` (`resource_id`) INVERSEOF `~patient` ) INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `medication`  INHERITS (`domainresource`, `concept`);
CREATE OR REPLACE CONCEPT `encounter`  INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `condition`  INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `allergyintolerance` (`lastoccurence` string, `category` string, `type` string, `criticality` string, `identifier` string, `coding` string, `comment` string, `recorder` string, `link` string, `event` string, `substance` string, `status` string, `patient` string, `reporter` string, `recordeddate` string, CONSTRAINT `has_recorder` FOREIGN KEY (`recorder`) REFERENCES `reference` (`resource_id`) INVERSEOF `of_recorder` , CONSTRAINT `has_reporter` FOREIGN KEY (`reporter`) REFERENCES `reference` (`resource_id`) INVERSEOF `is_reporter` , CONSTRAINT `has_status` FOREIGN KEY (`status`) REFERENCES `allergy_intolerance_status` (`resource_id`) INVERSEOF `with_status` , CONSTRAINT `has_patient` FOREIGN KEY (`patient`) REFERENCES `reference` (`resource_id`) INVERSEOF `is_patient` ) INHERITS (`domainresource`);
CREATE OR REPLACE CONCEPT `signature`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `reference` (`display` string) INHERITS (`element`);
CREATE OR REPLACE CONCEPT `observationstatus`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `humanname`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `flag_item`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `extension`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `contact`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `conformanceresourcestatus`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `backboneelement`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `attachment`  INHERITS (`element`);
CREATE OR REPLACE CONCEPT `transactionresponse`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `transaction`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `substitution`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `search`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `request`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `link`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `filter`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `expansion`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `evidence`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `event`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `entry`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `dosageinstructions`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `dispense`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `define`  INHERITS (`backboneelement`);
CREATE OR REPLACE CONCEPT `compose`  INHERITS (`backboneelement`);