CREATE OR REPLACE PROPERTY `connectedto_chargingstation` string;
CREATE OR REPLACE PROPERTY `qfixed` float;
CREATE OR REPLACE PROPERTY `inductance` float;
CREATE OR REPLACE PROPERTY `generationcontrolvalue` string;
CREATE OR REPLACE PROPERTY `minoperatingp` float;
CREATE OR REPLACE PROPERTY `maximumallowablespinningreserve` float;
CREATE OR REPLACE PROPERTY `gch` float;
CREATE OR REPLACE PROPERTY `chargeratemin` float;
CREATE OR REPLACE PROPERTY `iscoincidenttrigger` boolean;
CREATE OR REPLACE PROPERTY `chargetargettimestamp` timestamp;
CREATE OR REPLACE PROPERTY `auxiliaryequipment` string;
CREATE OR REPLACE PROPERTY `highsideminoperatingu` double;
CREATE OR REPLACE PROPERTY `hydroplantstoragetype` string;
CREATE OR REPLACE PROPERTY `connectioncategory` string;
CREATE OR REPLACE PROPERTY `converterdcsides` string;
CREATE OR REPLACE PROPERTY `ipmax` float;
CREATE OR REPLACE PROPERTY `capacitance` float;
CREATE OR REPLACE PROPERTY `eqloadname` string;
CREATE OR REPLACE PROPERTY `phasecodes` string;
CREATE OR REPLACE PROPERTY `solargeneratingunits` string;
CREATE OR REPLACE PROPERTY `issdp` boolean;
CREATE OR REPLACE PROPERTY `shortname` string;
CREATE OR REPLACE PROPERTY `terminals` string;
CREATE OR REPLACE PROPERTY `resistance` float;
CREATE OR REPLACE PROPERTY `minimalusageexpected` boolean;
CREATE OR REPLACE PROPERTY `physicalconnectioncapacity` float;
CREATE OR REPLACE PROPERTY `ispartofgeneratorunit` double;
CREATE OR REPLACE PROPERTY `powerfactor` float;
CREATE OR REPLACE PROPERTY `meterreading` string;
CREATE OR REPLACE PROPERTY `connectivitynode` string;
CREATE OR REPLACE PROPERTY `estimatedload` float;
CREATE OR REPLACE PROPERTY `bayenergymeasflag` boolean;
CREATE OR REPLACE PROPERTY `storagekind` string;
CREATE OR REPLACE PROPERTY `memberofsubstation` string;
CREATE OR REPLACE PROPERTY `batterytypename` string;
CREATE OR REPLACE PROPERTY `windpowerplant` string;
CREATE OR REPLACE PROPERTY `maxoperatingp` float;
CREATE OR REPLACE PROPERTY `amibillingready` string;
CREATE OR REPLACE PROPERTY `windgeneratingunits` string;
CREATE OR REPLACE PROPERTY `startupcost` float;
CREATE OR REPLACE PROPERTY `grosstonetactivepowercurves` string;
CREATE OR REPLACE PROPERTY `shortpf` float;
CREATE OR REPLACE PROPERTY `bch` float;
CREATE OR REPLACE PROPERTY `dischargeratemax` float;
CREATE OR REPLACE PROPERTY `phasecode` string;
CREATE OR REPLACE PROPERTY `grounded` boolean;
CREATE OR REPLACE PROPERTY `turbinetype` string;
CREATE OR REPLACE PROPERTY `capacity` float;
CREATE OR REPLACE PROPERTY `servicepriority` string;
CREATE OR REPLACE PROPERTY `assignedbasevoltage` string;
CREATE OR REPLACE PROPERTY `controlareageneratingunit` string;
CREATE OR REPLACE PROPERTY `startuptime` float;
CREATE OR REPLACE PROPERTY `solarpowerplant` string;
CREATE OR REPLACE PROPERTY `fossilfuels` string;
CREATE OR REPLACE PROPERTY `generatingunit` string;
CREATE OR REPLACE PROPERTY `outageregion` string;
CREATE OR REPLACE PROPERTY `phases` string;
CREATE OR REPLACE PROPERTY `ratedcurrent` float;
CREATE OR REPLACE PROPERTY `chargeratemax` float;
CREATE OR REPLACE PROPERTY `busbarconfiguration` string;
CREATE OR REPLACE PROPERTY `caesplant` string;
CREATE OR REPLACE PROPERTY `dropheight` float;
CREATE OR REPLACE PROPERTY `hydroenergyconversionkind` string;
CREATE OR REPLACE PROPERTY `lowvoltagelimit` float;
CREATE OR REPLACE PROPERTY `beforeshcircuithighestoperatingcurrent` double;
CREATE OR REPLACE PROPERTY `cogenerationplant` string;
CREATE OR REPLACE PROPERTY `conductor` string;
CREATE OR REPLACE PROPERTY `minp` float;
CREATE OR REPLACE PROPERTY `conductingequipment` string;
CREATE OR REPLACE PROPERTY `hydropumps` string;
CREATE OR REPLACE PROPERTY `rotatingmachine` string;
CREATE OR REPLACE PROPERTY `memberof_substation` string;
CREATE OR REPLACE PROPERTY `p` float;
CREATE OR REPLACE PROPERTY `equipments` string;
CREATE OR REPLACE PROPERTY `q` float;
CREATE OR REPLACE PROPERTY `r` float;
CREATE OR REPLACE PROPERTY `ratede` float;
CREATE OR REPLACE PROPERTY `memberof_equipmentcontainer` string;
CREATE OR REPLACE PROPERTY `x` float;
CREATE OR REPLACE PROPERTY `ratednetmaxp` float;
CREATE OR REPLACE PROPERTY `hydrogeneratingunits` string;
CREATE OR REPLACE PROPERTY `energyidentcodeeic` string;
CREATE OR REPLACE PROPERTY `customercount` integer;
CREATE OR REPLACE PROPERTY `tieflow` string;
CREATE OR REPLACE PROPERTY `ratedpower` float;
CREATE OR REPLACE PROPERTY `nominalp` float;
CREATE OR REPLACE PROPERTY `variablecost` float;
CREATE OR REPLACE PROPERTY `normalopen` float;
CREATE OR REPLACE PROPERTY `powertransformerends` string;
CREATE OR REPLACE PROPERTY `combinedcycleplant` string;
CREATE OR REPLACE PROPERTY `highvoltagelimit` float;
CREATE OR REPLACE PROPERTY `relatedequipment` string;
CREATE OR REPLACE PROPERTY `chargemin` float;
CREATE OR REPLACE PROPERTY `chargetarget` float;
CREATE OR REPLACE PROPERTY `switchschedules` string;
CREATE OR REPLACE PROPERTY `storede` float;
CREATE OR REPLACE PROPERTY `equipmentcontainer` string;
CREATE OR REPLACE PROPERTY `formnumber` string;
CREATE OR REPLACE PROPERTY `beforeshcircuithighestoperatingvoltage` double;
CREATE OR REPLACE PROPERTY `voltagelevel` string;
CREATE OR REPLACE PROPERTY `isvirtual` boolean;
CREATE OR REPLACE PROPERTY `chargemax` float;
CREATE OR REPLACE PROPERTY `ratedgrossminp` float;
CREATE OR REPLACE PROPERTY `totalefficiency` float;
CREATE OR REPLACE PROPERTY `locatedat` string;
CREATE OR REPLACE PROPERTY `beforeshortcircuitanglepf` double;
CREATE OR REPLACE PROPERTY `windgenunittype` string;
CREATE OR REPLACE PROPERTY `mrid` string;
CREATE OR REPLACE PROPERTY `breakerconfiguration` string;
CREATE OR REPLACE PROPERTY `substationtype` string;
CREATE OR REPLACE PROPERTY `bays` string;
CREATE OR REPLACE PROPERTY `evname` string;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `dischargeratemin` float;
CREATE OR REPLACE PROPERTY `operationalvaluesconsidered` double;
CREATE OR REPLACE PROPERTY `operational_limit_set_id` integer;
CREATE OR REPLACE PROPERTY `regulatingcontrol` string;
CREATE OR REPLACE PROPERTY `dcconverterunit` string;
CREATE OR REPLACE PROPERTY `transformerend` string;
CREATE OR REPLACE PROPERTY `maxp` float;
CREATE OR REPLACE PROPERTY `disconnectionmethod` string;
CREATE OR REPLACE PROPERTY `energyconversioncapability` string;
CREATE OR REPLACE PROPERTY `windgenunitkind` string;
CREATE OR REPLACE PROPERTY `powertransformerend` double;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `servicedeliveryremark` string;
CREATE OR REPLACE PROPERTY `basevoltage` string;
CREATE OR REPLACE PROPERTY `baypowermeasflag` boolean;
CREATE OR REPLACE PROPERTY `connectionstate` string;
CREATE OR REPLACE PROPERTY `readcycle` string;
CREATE OR REPLACE PROPERTY `aggregate` float;
CREATE OR REPLACE PROPERTY `voltagelevels` string;
CREATE OR REPLACE PROPERTY `governorscd` float;
CREATE OR REPLACE PROPERTY `customerloadname` string;
CREATE OR REPLACE PROPERTY `readroute` string;
CREATE OR REPLACE PROPERTY `phasecount` integer;
CREATE OR REPLACE PROPERTY `powerelectronicsconnection` string;
CREATE OR REPLACE PROPERTY `memberof_equipmentcontainervl` string;
CREATE OR REPLACE PROPERTY `substationname` string;
CREATE OR REPLACE PROPERTY `length` float;
CREATE OR REPLACE PROPERTY `valuesinterval` timestamp;
CREATE OR REPLACE PROPERTY `hydropowerplant` string;
CREATE OR REPLACE PROPERTY `longpf` float;
CREATE OR REPLACE PROPERTY `pfixed` float;
CREATE OR REPLACE PROPERTY `substations` string;
CREATE OR REPLACE PROPERTY `checkbilling` boolean;
CREATE OR REPLACE PROPERTY `operationallimitset` string;
CREATE OR REPLACE PROPERTY `batterystate` string;
CREATE OR REPLACE PROPERTY `gencontrolsource` string;
CREATE OR REPLACE PROPERTY `retained` float;
CREATE OR REPLACE PROPERTY `nominalservicevoltage` float;
CREATE OR REPLACE PROPERTY `ratedgrossmaxp` float;
CREATE OR REPLACE PROPERTY `normallyinservice` float;
CREATE OR REPLACE CONCEPT `identifiedobject` (`description` string, `shortname` string, `mrid` string, `energyidentcodeeic` string, `name` string, PRIMARY KEY (`mrid`)) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `windgenunitkind` (`windgenunitkind` string) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `usagepoint` (`phasecode` string, `checkbilling` boolean, `servicepriority` string, `isvirtual` boolean, `readroute` string, `minimalusageexpected` boolean, `phasecount` integer, `readcycle` string, `estimatedload` float, `grounded` boolean, `relatedequipment` string, `amibillingready` string, `ratedcurrent` float, `physicalconnectioncapacity` float, `issdp` boolean, `connectioncategory` string, `disconnectionmethod` string, `nominalservicevoltage` float, `ratedpower` float, `connectionstate` string, `servicedeliveryremark` string, `outageregion` string, CONSTRAINT `relatedequipment` FOREIGN KEY (`relatedequipment`) REFERENCES `equipment` (`name`) INVERSEOF `usagepoint` ) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `switchschedule`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `powersystemresource`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `operationallimitset` (`operational_limit_set_id` integer) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `meterreading` (`iscoincidenttrigger` boolean, `valuesinterval` timestamp) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `meter` (`formnumber` string, `meterreading` string, `connectioncategory` string, CONSTRAINT `meterreading` FOREIGN KEY (`meterreading`) REFERENCES `meterreading` (`name`) INVERSEOF `meter` ) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `location`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `hydroturbinekind`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `hydroplantstoragekind` (`storagekind` string) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `hydroenergyconversionkind` (`hydroenergyconversionkind` string) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `generatorcontrolsource` (`generationcontrolvalue` string) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `fossilfuel`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `equivalentload` (`customercount` integer, `p` float, `qfixed` float, `memberof_equipmentcontainer` string, `q` float, `powerfactor` float, `eqloadname` string, `pfixed` float, CONSTRAINT `memberof_equipmentcontainer` FOREIGN KEY (`memberof_equipmentcontainer`) REFERENCES `equipmentcontainer` (`name`) INVERSEOF `equivalentload` ) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `customerload` (`p` float, `customerloadname` string, `qfixed` float, `q` float, `powerfactor` float, `memberof_equipmentcontainervl` string, `pfixed` float, CONSTRAINT `memberof_equipmentcontainervl` FOREIGN KEY (`memberof_equipmentcontainervl`) REFERENCES `voltagelevel` (`name`) INVERSEOF `customerload` ) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `curve`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `controlareageneratingunit`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `connectivitynodecontainer`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `connectivitynode` (`terminals` string) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `battery` (`chargemin` float, `batterytypename` string, `chargeratemax` float, `dischargeratemin` float, `chargetarget` float, `capacity` float, `chargemax` float, `chargeratemin` float, `dischargeratemax` float) INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `basevoltage`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `acdcterminal`  INHERITS (`identifiedobject`);
CREATE OR REPLACE CONCEPT `windpowerplant` (`windgeneratingunits` string) INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `solarpowerplant` (`solargeneratingunits` string) INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `hydropowerplant` (`hydropumps` string, `hydrogeneratingunits` string, `hydroplantstoragetype` string, CONSTRAINT `hydroplantstoragetype` FOREIGN KEY (`hydroplantstoragetype`) REFERENCES `hydroplantstoragekind` (`mrid`) INVERSEOF `~hydroplantstoragetype` ) INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `equipment` (`aggregate` float, `normallyinservice` float, `operationallimitset` string, `equipmentcontainer` string, CONSTRAINT `equipmentcontainer` FOREIGN KEY (`equipmentcontainer`) REFERENCES `equipmentcontainer` (`mrid`) INVERSEOF `equipments` ) INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `combinedcycleplant`  INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `cogenerationplant`  INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `caesplant`  INHERITS (`powersystemresource`);
CREATE OR REPLACE CONCEPT `powertransformerend`  INHERITS (`equipment`);
CREATE OR REPLACE CONCEPT `powerelectronicsunit` (`powerelectronicsconnection` string, `minp` float, `maxp` float, CONSTRAINT `powerelectronicsconnection` FOREIGN KEY (`powerelectronicsconnection`) REFERENCES `powerelectronicsconnection` (`mrid`) INVERSEOF `~powerelectronicsconnection` ) INHERITS (`equipment`);
CREATE OR REPLACE CONCEPT `generatingunit` (`nominalp` float, `controlareageneratingunit` string, `variablecost` float, `ratedgrossminp` float, `startuptime` float, `ratedgrossmaxp` float, `minoperatingp` float, `ratednetmaxp` float, `gencontrolsource` string, `maximumallowablespinningreserve` float, `rotatingmachine` string, `startupcost` float, `shortpf` float, `maxoperatingp` float, `grosstonetactivepowercurves` string, `governorscd` float, `totalefficiency` float, `longpf` float, CONSTRAINT `grosstonetactivepowercurves` FOREIGN KEY (`grosstonetactivepowercurves`) REFERENCES `grosstonetactivepowercurve` (`mrid`) INVERSEOF `generatingunit` , CONSTRAINT `controlareageneratingunit` FOREIGN KEY (`controlareageneratingunit`) REFERENCES `controlareageneratingunit` (`mrid`) INVERSEOF `~controlareageneratingunit` , CONSTRAINT `gencontrolsource` FOREIGN KEY (`gencontrolsource`) REFERENCES `generatorcontrolsource` (`mrid`) INVERSEOF `generatingunit` ) INHERITS (`equipment`);
CREATE OR REPLACE CONCEPT `conductingequipment` (`terminals` string, `basevoltage` string, CONSTRAINT `basevoltage` FOREIGN KEY (`basevoltage`) REFERENCES `basevoltage` (`mrid`) INVERSEOF `conductingequipment` ) INHERITS (`equipment`);
CREATE OR REPLACE CONCEPT `powerelectronicswindunit`  INHERITS (`powerelectronicsunit`);
CREATE OR REPLACE CONCEPT `photovoltaicunit`  INHERITS (`powerelectronicsunit`);
CREATE OR REPLACE CONCEPT `batteryunit` (`storede` float, `ratede` float, `batterystate` string) INHERITS (`powerelectronicsunit`);
CREATE OR REPLACE CONCEPT `windgeneratingunit` (`windgenunittype` string, `windpowerplant` string, CONSTRAINT `windgenunittype` FOREIGN KEY (`windgenunittype`) REFERENCES `windgenunitkind` (`mrid`) INVERSEOF `~windgenunittype` , CONSTRAINT `windpowerplant` FOREIGN KEY (`windpowerplant`) REFERENCES `windpowerplant` (`mrid`) INVERSEOF `windgeneratingunits` ) INHERITS (`generatingunit`);
CREATE OR REPLACE CONCEPT `thermalgeneratingunit` (`fossilfuels` string, `combinedcycleplant` string, `caesplant` string, `cogenerationplant` string, CONSTRAINT `caesplant` FOREIGN KEY (`caesplant`) REFERENCES `caesplant` (`mrid`) INVERSEOF `~caesplant` , CONSTRAINT `combinedcycleplant` FOREIGN KEY (`combinedcycleplant`) REFERENCES `combinedcycleplant` (`mrid`) INVERSEOF `~combinedcycleplant` , CONSTRAINT `fossilfuels` FOREIGN KEY (`fossilfuels`) REFERENCES `fossilfuel` (`mrid`) INVERSEOF `~fossilfuels` , CONSTRAINT `cogenerationplant` FOREIGN KEY (`cogenerationplant`) REFERENCES `cogenerationplant` (`mrid`) INVERSEOF `~cogenerationplant` ) INHERITS (`generatingunit`);
CREATE OR REPLACE CONCEPT `solargeneratingunit` (`solarpowerplant` string, CONSTRAINT `solarpowerplant` FOREIGN KEY (`solarpowerplant`) REFERENCES `solarpowerplant` (`mrid`) INVERSEOF `solargeneratingunits` ) INHERITS (`generatingunit`);
CREATE OR REPLACE CONCEPT `nucleargeneratingunit`  INHERITS (`generatingunit`);
CREATE OR REPLACE CONCEPT `hydrogeneratingunit` (`energyconversioncapability` string, `turbinetype` string, `dropheight` float, `hydropowerplant` string, CONSTRAINT `hydropowerplant` FOREIGN KEY (`hydropowerplant`) REFERENCES `hydropowerplant` (`mrid`) INVERSEOF `hydrogeneratingunits` , CONSTRAINT `turbinetype` FOREIGN KEY (`turbinetype`) REFERENCES `hydroturbinekind` (`mrid`) INVERSEOF `~turbinetype` , CONSTRAINT `energyconversioncapability` FOREIGN KEY (`energyconversioncapability`) REFERENCES `hydroenergyconversionkind` (`mrid`) INVERSEOF `~energyconversioncapability` ) INHERITS (`generatingunit`);
CREATE OR REPLACE CONCEPT `switch` (`normalopen` float, `ratedcurrent` float, `switchschedules` string, `retained` float, CONSTRAINT `switchschedules` FOREIGN KEY (`switchschedules`) REFERENCES `switchschedule` (`name`) INVERSEOF `switch` ) INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `protectedswitch`  INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `powertransformer` (`ispartofgeneratorunit` double, `beforeshcircuithighestoperatingvoltage` double, `powertransformerends` string, `memberof_substation` string, `operationalvaluesconsidered` double, `beforeshcircuithighestoperatingcurrent` double, `highsideminoperatingu` double, `beforeshortcircuitanglepf` double, `powertransformerend` double, CONSTRAINT `powertransformerends` FOREIGN KEY (`powertransformerends`) REFERENCES `powertransformerend` (`name`) INVERSEOF `powertransformer` , CONSTRAINT `memberof_substation` FOREIGN KEY (`memberof_substation`) REFERENCES `substation` (`name`) INVERSEOF `powertransformer` ) INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `powerelectronicsconnection`  INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `hydropump` (`rotatingmachine` string, `hydropowerplant` string, CONSTRAINT `hydropowerplant` FOREIGN KEY (`hydropowerplant`) REFERENCES `hydropowerplant` (`mrid`) INVERSEOF `hydropumps` ) INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `energyconnection`  INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `dcconverterunit`  INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `dcconductingequipment`  INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `connector`  INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `conductor` (`length` float) INHERITS (`conductingequipment`);
CREATE OR REPLACE CONCEPT `breaker`  INHERITS (`protectedswitch`);
CREATE OR REPLACE CONCEPT `dclinesegment` (`length` float, `inductance` float, `capacitance` float, `resistance` float) INHERITS (`dcconductingequipment`);
CREATE OR REPLACE CONCEPT `busbarsection` (`ipmax` float) INHERITS (`connector`);
CREATE OR REPLACE CONCEPT `aclinesegment` (`gch` float, `bch` float, `r` float, `x` float, `conductor` string, CONSTRAINT `conductor` FOREIGN KEY (`conductor`) REFERENCES `conductor` (`name`) INVERSEOF `aclinesegment` ) INHERITS (`conductor`);
CREATE OR REPLACE CONCEPT `geographicalregion`  INHERITS (`location`);
CREATE OR REPLACE CONCEPT `subgeographicalregion` (`substations` string) INHERITS (`geographicalregion`);
CREATE OR REPLACE CONCEPT `grosstonetactivepowercurve` (`generatingunit` string) INHERITS (`curve`);
CREATE OR REPLACE CONCEPT `equipmentcontainer` (`equipments` string) INHERITS (`connectivitynodecontainer`);
CREATE OR REPLACE CONCEPT `voltagelevel` (`highvoltagelimit` float, `memberof_substation` string, `lowvoltagelimit` float, `bays` string, `assignedbasevoltage` string, CONSTRAINT `assignedbasevoltage` FOREIGN KEY (`assignedbasevoltage`) REFERENCES `basevoltage` (`mrid`) INVERSEOF `~assignedbasevoltage` , CONSTRAINT `memberof_substation` FOREIGN KEY (`memberof_substation`) REFERENCES `substation` (`mrid`) INVERSEOF `voltagelevels` ) INHERITS (`equipmentcontainer`);
CREATE OR REPLACE CONCEPT `substation` (`substationtype` string, `dcconverterunit` string, `bays` string, `substationname` string, `locatedat` string, `voltagelevels` string, CONSTRAINT `locatedat` FOREIGN KEY (`locatedat`) REFERENCES `subgeographicalregion` (`mrid`) INVERSEOF `substations` , CONSTRAINT `dcconverterunit` FOREIGN KEY (`dcconverterunit`) REFERENCES `dcconverterunit` (`mrid`) INVERSEOF `~dcconverterunit` ) INHERITS (`equipmentcontainer`);
CREATE OR REPLACE CONCEPT `bay` (`voltagelevel` string, `busbarconfiguration` string, `memberofsubstation` string, `breakerconfiguration` string, `baypowermeasflag` boolean, `bayenergymeasflag` boolean, CONSTRAINT `memberofsubstation` FOREIGN KEY (`memberofsubstation`) REFERENCES `substation` (`mrid`) INVERSEOF `bays` , CONSTRAINT `voltagelevel` FOREIGN KEY (`voltagelevel`) REFERENCES `voltagelevel` (`mrid`) INVERSEOF `bays` ) INHERITS (`equipmentcontainer`);
CREATE OR REPLACE CONCEPT `electricvehicle` (`evname` string, `chargetargettimestamp` timestamp, `connectedto_chargingstation` string) INHERITS (`battery`);
CREATE OR REPLACE CONCEPT `terminal` (`phasecodes` string, `phases` string, `transformerend` string, `converterdcsides` string, `regulatingcontrol` string, `conductingequipment` string, `connectivitynode` string, `tieflow` string, `auxiliaryequipment` string, CONSTRAINT `connectivitynode` FOREIGN KEY (`connectivitynode`) REFERENCES `connectivitynode` (`mrid`) INVERSEOF `terminals` , CONSTRAINT `conductingequipment` FOREIGN KEY (`conductingequipment`) REFERENCES `conductingequipment` (`mrid`) INVERSEOF `terminals` ) INHERITS (`acdcterminal`);