CREATE OR REPLACE PROPERTY `issuing_country_id` integer;
CREATE OR REPLACE PROPERTY `owner_id` integer;
CREATE OR REPLACE PROPERTY `security_description` string;
CREATE OR REPLACE PROPERTY `value_of_shares_sold` bigint;
CREATE OR REPLACE PROPERTY `class_id` string;
CREATE OR REPLACE PROPERTY `adr_ord_ratio` float;
CREATE OR REPLACE PROPERTY `asset_id` string;
CREATE OR REPLACE PROPERTY `ric` string;
CREATE OR REPLACE PROPERTY `take_date_time` string;
CREATE OR REPLACE PROPERTY `percent_of_shares_outstanding` float;
CREATE OR REPLACE PROPERTY `related_official_name` string;
CREATE OR REPLACE PROPERTY `related_entity_type_description` string;
CREATE OR REPLACE PROPERTY `relationship_type` string;
CREATE OR REPLACE PROPERTY `metro_area_id` integer;
CREATE OR REPLACE PROPERTY `cusip_check_digit` integer;
CREATE OR REPLACE PROPERTY `action` string;
CREATE OR REPLACE PROPERTY `id` string;
CREATE OR REPLACE PROPERTY `fax` string;
CREATE OR REPLACE PROPERTY `prior_report_date` integer;
CREATE OR REPLACE PROPERTY `security_id` integer;
CREATE OR REPLACE PROPERTY `number_of_sellers` integer;
CREATE OR REPLACE PROPERTY `related_orgid` string;
CREATE OR REPLACE PROPERTY `exchange_description` string;
CREATE OR REPLACE PROPERTY `issuer_permid` string;
CREATE OR REPLACE PROPERTY `zip` string;
CREATE OR REPLACE PROPERTY `immediate_parent_official_name` string;
CREATE OR REPLACE PROPERTY `parent_style_id` integer;
CREATE OR REPLACE PROPERTY `price_date` integer;
CREATE OR REPLACE PROPERTY `quote_id` string;
CREATE OR REPLACE PROPERTY `region_id` integer;
CREATE OR REPLACE PROPERTY `sedol` string;
CREATE OR REPLACE PROPERTY `adr_ord_security_id` integer;
CREATE OR REPLACE PROPERTY `issue_name` string;
CREATE OR REPLACE PROPERTY `asset_code` integer;
CREATE OR REPLACE PROPERTY `phone` string;
CREATE OR REPLACE PROPERTY `issue_permid` string;
CREATE OR REPLACE PROPERTY `trbc_industry_group_name` string;
CREATE OR REPLACE PROPERTY `short_name` string;
CREATE OR REPLACE PROPERTY `country_id` integer;
CREATE OR REPLACE PROPERTY `new_position` string;
CREATE OR REPLACE PROPERTY `ticker_symbol` string;
CREATE OR REPLACE PROPERTY `node_level` string;
CREATE OR REPLACE PROPERTY `city` string;
CREATE OR REPLACE PROPERTY `related_rics` string;
CREATE OR REPLACE PROPERTY `trbc_industry_code` string;
CREATE OR REPLACE PROPERTY `company_common_name` string;
CREATE OR REPLACE PROPERTY `parent_owner_type_id` integer;
CREATE OR REPLACE PROPERTY `products` string;
CREATE OR REPLACE PROPERTY `issuer_orgid` string;
CREATE OR REPLACE PROPERTY `issue_date` integer;
CREATE OR REPLACE PROPERTY `security_class` string;
CREATE OR REPLACE PROPERTY `id_type` integer;
CREATE OR REPLACE PROPERTY `headline` string;
CREATE OR REPLACE PROPERTY `number_of_buyers` integer;
CREATE OR REPLACE PROPERTY `organization_permid` string;
CREATE OR REPLACE PROPERTY `value_held_by_all_owners` bigint;
CREATE OR REPLACE PROPERTY `shares_held` bigint;
CREATE OR REPLACE PROPERTY `owner_type_id` integer;
CREATE OR REPLACE PROPERTY `topics` string;
CREATE OR REPLACE PROPERTY `value_held_by_institutions` bigint;
CREATE OR REPLACE PROPERTY `macro_sector_id` integer;
CREATE OR REPLACE PROPERTY `environment_pillar_score_grade` string;
CREATE OR REPLACE PROPERTY `value_of_shares_bought` bigint;
CREATE OR REPLACE PROPERTY `instrument_id` string;
CREATE OR REPLACE PROPERTY `asset_region_code` integer;
CREATE OR REPLACE PROPERTY `url` string;
CREATE OR REPLACE PROPERTY `issuer_name` string;
CREATE OR REPLACE PROPERTY `lower_range` integer;
CREATE OR REPLACE PROPERTY `issuer_id` integer;
CREATE OR REPLACE PROPERTY `ownership_phrase_description` string;
CREATE OR REPLACE PROPERTY `old_name` string;
CREATE OR REPLACE PROPERTY `province_id` integer;
CREATE OR REPLACE PROPERTY `sector_id` integer;
CREATE OR REPLACE PROPERTY `number_of_securities_held` integer;
CREATE OR REPLACE PROPERTY `total_shares_held_by_institutions` bigint;
CREATE OR REPLACE PROPERTY `us_region_id` integer;
CREATE OR REPLACE PROPERTY `source_id` integer;
CREATE OR REPLACE PROPERTY `style_id` integer;
CREATE OR REPLACE PROPERTY `ownership_percentage` string;
CREATE OR REPLACE PROPERTY `cusip` string;
CREATE OR REPLACE PROPERTY `cins` string;
CREATE OR REPLACE PROPERTY `address_1` string;
CREATE OR REPLACE PROPERTY `old_owner_id` integer;
CREATE OR REPLACE PROPERTY `value_held` bigint;
CREATE OR REPLACE PROPERTY `address_2` string;
CREATE OR REPLACE PROPERTY `address_3` string;
CREATE OR REPLACE PROPERTY `country_of_exchange` string;
CREATE OR REPLACE PROPERTY `shares_outstanding` bigint;
CREATE OR REPLACE PROPERTY `language` string;
CREATE OR REPLACE PROPERTY `source` integer;
CREATE OR REPLACE PROPERTY `story_date_time` string;
CREATE OR REPLACE PROPERTY `immediate_parent_perm_id` string;
CREATE OR REPLACE PROPERTY `turnover_rating` integer;
CREATE OR REPLACE PROPERTY `change_sign` string;
CREATE OR REPLACE PROPERTY `governance_pillar_score_grade` string;
CREATE OR REPLACE PROPERTY `prior_source` integer;
CREATE OR REPLACE PROPERTY `trbc_business_sector_code` string;
CREATE OR REPLACE PROPERTY `pnac` string;
CREATE OR REPLACE PROPERTY `parent_owner_id` integer;
CREATE OR REPLACE PROPERTY `shares_bought` bigint;
CREATE OR REPLACE PROPERTY `naics_industry_group_code` string;
CREATE OR REPLACE PROPERTY `report_date` integer;
CREATE OR REPLACE PROPERTY `story_body` string;
CREATE OR REPLACE PROPERTY `trbc_industry_name` string;
CREATE OR REPLACE PROPERTY `number_of_securities_sold` integer;
CREATE OR REPLACE PROPERTY `naics_sector_code` string;
CREATE OR REPLACE PROPERTY `number_of_securities_bought` integer;
CREATE OR REPLACE PROPERTY `ultimate_parent_orgid` string;
CREATE OR REPLACE PROPERTY `unique_story_index` string;
CREATE OR REPLACE PROPERTY `ultimate_parent_official_name` string;
CREATE OR REPLACE PROPERTY `asset_flag` string;
CREATE OR REPLACE PROPERTY `social_pillar_score` string;
CREATE OR REPLACE PROPERTY `organization_id` string;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `latest_holding_date` integer;
CREATE OR REPLACE PROPERTY `state_code` string;
CREATE OR REPLACE PROPERTY `shares_changed` bigint;
CREATE OR REPLACE PROPERTY `official_name` string;
CREATE OR REPLACE PROPERTY `total_equity_assets` bigint;
CREATE OR REPLACE PROPERTY `industry_id` integer;
CREATE OR REPLACE PROPERTY `code` string;
CREATE OR REPLACE PROPERTY `cik` bigint;
CREATE OR REPLACE PROPERTY `naics_sector_name` string;
CREATE OR REPLACE PROPERTY `turnover_value` float;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `related_entity_type` string;
CREATE OR REPLACE PROPERTY `social_pillar_score_grade` string;
CREATE OR REPLACE PROPERTY `governance_pillar_score` string;
CREATE OR REPLACE PROPERTY `_c2` string;
CREATE OR REPLACE PROPERTY `exchange_id` string;
CREATE OR REPLACE PROPERTY `fund_ticker_symbol` string;
CREATE OR REPLACE PROPERTY `immediate_parent_orgid` string;
CREATE OR REPLACE PROPERTY `primary_security_id` integer;
CREATE OR REPLACE PROPERTY `market_cap` bigint;
CREATE OR REPLACE PROPERTY `country_name` string;
CREATE OR REPLACE PROPERTY `ultimate_parent_perm_id` string;
CREATE OR REPLACE PROPERTY `quote_permid` string;
CREATE OR REPLACE PROPERTY `exchange_code` string;
CREATE OR REPLACE PROPERTY `trbc_industry_group_code` string;
CREATE OR REPLACE PROPERTY `new_name` string;
CREATE OR REPLACE PROPERTY `new_owner_id` integer;
CREATE OR REPLACE PROPERTY `total_shares_held_by_all_owners` bigint;
CREATE OR REPLACE PROPERTY `trbc_economic_sector_code` string;
CREATE OR REPLACE PROPERTY `orientation` string;
CREATE OR REPLACE PROPERTY `environment_pillar_score` string;
CREATE OR REPLACE PROPERTY `upper_range` integer;
CREATE OR REPLACE PROPERTY `trbc_activity_code` string;
CREATE OR REPLACE PROPERTY `value_of_shares_changed` bigint;
CREATE OR REPLACE PROPERTY `search_id` string;
CREATE OR REPLACE PROPERTY `number_of_holders` integer;
CREATE OR REPLACE PROPERTY `trading_country_id` integer;
CREATE OR REPLACE PROPERTY `sedol_check_digit` integer;
CREATE OR REPLACE PROPERTY `shares_sold` bigint;
CREATE OR REPLACE PROPERTY `ownership_characterization` string;
CREATE OR REPLACE PROPERTY `legal_entity_orgid` string;
CREATE OR REPLACE PROPERTY `naics_industry_group_name` string;
CREATE OR REPLACE PROPERTY `isin` string;
CREATE OR REPLACE PROPERTY `share_price` float;
CREATE OR REPLACE CONCEPT `us_region` (`description` string, `_c2` string, `us_region_id` integer, PRIMARY KEY (`us_region_id`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-chart-area');
CREATE OR REPLACE CONCEPT `states` (`description` string, `state_code` string, PRIMARY KEY (`state_code`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-flag-usa');
CREATE OR REPLACE CONCEPT `security_stats` (`value_of_shares_sold` bigint, `security_id` integer, `shares_bought` bigint, `value_held_by_all_owners` bigint, `value_of_shares_bought` bigint, `shares_sold` bigint, `number_of_sellers` integer, `number_of_holders` integer, `total_shares_held_by_institutions` bigint, `number_of_buyers` integer, `total_shares_held_by_all_owners` bigint, `value_held_by_institutions` bigint, PRIMARY KEY (`security_id`), LABEL (`security_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tasks-alt');
CREATE OR REPLACE CONCEPT `security_ids` (`security_id` integer, `search_id` string, `id_type` integer, PRIMARY KEY (`security_id`), LABEL (`security_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-fingerprint');
CREATE OR REPLACE CONCEPT `security_class` (`description` string, `class_id` string, PRIMARY KEY (`class_id`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-suitcase');
CREATE OR REPLACE CONCEPT `security` (`security_id` integer, `adr_ord_security_id` integer, `issuer_id` integer, `ticker_symbol` string, `shares_outstanding` bigint, `issuing_country_id` integer, `adr_ord_ratio` float, `isin` string, `latest_holding_date` integer, `sedol` string, `issue_date` integer, `cins` string, `issue_name` string, `primary_security_id` integer, `industry_id` integer, `cusip_check_digit` integer, `exchange_id` string, `trading_country_id` integer, `market_cap` bigint, `security_class` string, `security_description` string, `cusip` string, `price_date` integer, `share_price` float, `sedol_check_digit` integer, PRIMARY KEY (`security_id`), LABEL (`security_description`), CONSTRAINT `in_industry` FOREIGN KEY (`industry_id`) REFERENCES `industry` (`industry_id`) INVERSEOF `has_security` , CONSTRAINT `of_class` FOREIGN KEY (`security_class`) REFERENCES `security_class` (`class_id`) INVERSEOF `of_security` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-shield');
CREATE OR REPLACE CONCEPT `sector` (`description` string, `sector_id` integer, `macro_sector_id` integer, PRIMARY KEY (`sector_id`), LABEL (`description`), CONSTRAINT `in_macro_sector` FOREIGN KEY (`macro_sector_id`) REFERENCES `macro_sector` (`macro_sector_id`) INVERSEOF `in_sector` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-people-group');
CREATE OR REPLACE CONCEPT `region_country` (`country_id` integer, `region_id` integer, PRIMARY KEY (`region_id`), LABEL (`region_id`), CONSTRAINT `of_issuer` FOREIGN KEY (`country_id`) REFERENCES `issuer` (`country_id`) INVERSEOF `_in_region` , CONSTRAINT `of_owner_` FOREIGN KEY (`country_id`) REFERENCES `owner` (`country_id`) INVERSEOF `in_region_` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-globe');
CREATE OR REPLACE CONCEPT `province` (`description` string, `province_id` integer, `country_id` integer, PRIMARY KEY (`province_id`), LABEL (`description`), CONSTRAINT `of_owner_` FOREIGN KEY (`country_id`) REFERENCES `owner` (`country_id`) INVERSEOF `in_province_` , CONSTRAINT `of_the_same_country` FOREIGN KEY (`country_id`) REFERENCES `region_country` (`country_id`) INVERSEOF `of_the_same_country_` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-map-pin');
CREATE OR REPLACE CONCEPT `owner_metro_area` (`metro_area_id` integer, `owner_id` integer, PRIMARY KEY (`owner_id`), LABEL (`metro_area_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-house-signal');
CREATE OR REPLACE CONCEPT `owner_issue_map` (`isin` string, `security_id` integer, `owner_id` integer, PRIMARY KEY (`owner_id`), LABEL (`owner_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-house-medical-flag');
CREATE OR REPLACE CONCEPT `owner_id_change` (`old_name` string, `action` string, `new_name` string, `old_owner_id` integer, `new_owner_id` integer, PRIMARY KEY (`new_owner_id`), LABEL (`new_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-plus');
CREATE OR REPLACE CONCEPT `ownership_type` (`description` string, `code` string, `owner_type_id` integer, `parent_owner_type_id` integer, PRIMARY KEY (`owner_type_id`), LABEL (`description`), CONSTRAINT `parent_owner_type` FOREIGN KEY (`parent_owner_type_id`) REFERENCES `ownership_type` (`owner_type_id`) INVERSEOF `child_owner_type` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-file-circle-check');
CREATE OR REPLACE CONCEPT `ownership` (`social_pillar_score_grade` string, `ultimate_parent_perm_id` string, `ownership_phrase_description` string, `naics_industry_group_code` string, `ownership_characterization` string, `official_name` string, `ultimate_parent_orgid` string, `ultimate_parent_official_name` string, `immediate_parent_official_name` string, `governance_pillar_score` string, `immediate_parent_orgid` string, `trbc_industry_name` string, `legal_entity_orgid` string, `naics_sector_name` string, `naics_industry_group_name` string, `related_entity_type` string, `relationship_type` string, `ownership_percentage` string, `id` string, `environment_pillar_score_grade` string, `related_entity_type_description` string, `naics_sector_code` string, `environment_pillar_score` string, `node_level` string, `related_orgid` string, `social_pillar_score` string, `related_official_name` string, `governance_pillar_score_grade` string, `immediate_parent_perm_id` string, PRIMARY KEY (`id`), LABEL (`relationship_type`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-shop-lock');
CREATE OR REPLACE CONCEPT `owner` (`total_equity_assets` bigint, `owner_type_id` integer, `province_id` integer, `orientation` string, `report_date` integer, `country_id` integer, `city` string, `name` string, `asset_flag` string, `us_region_id` integer, `style_id` integer, `state_code` string, `number_of_securities_bought` integer, `parent_owner_id` integer, `number_of_securities_sold` integer, `asset_region_code` integer, `url` string, `address_3` string, `zip` string, `owner_id` integer, `turnover_value` float, `turnover_rating` integer, `phone` string, `number_of_securities_held` integer, `address_2` string, `prior_report_date` integer, `fax` string, `address_1` string, PRIMARY KEY (`owner_id`), LABEL (`name`), CONSTRAINT `has_asset_in_region` MULTIREFERENCE `asset_region` INVERSEOF `belongs_to` , CONSTRAINT `owns` FOREIGN KEY (`parent_owner_id`) REFERENCES `owner` (`owner_id`) INVERSEOF `owned_by`  TRANSITIVE, CONSTRAINT `has_style` FOREIGN KEY (`style_id`) REFERENCES `investment_style` (`style_id`) INVERSEOF `of_owner_` , CONSTRAINT `owner_type` FOREIGN KEY (`owner_type_id`) REFERENCES `ownership_type` (`owner_type_id`) INVERSEOF `of_owner` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-lock');
CREATE OR REPLACE CONCEPT `news` (`unique_story_index` string, `take_date_time` string, `issuer_permid` string, `products` string, `story_body` string, `trbc_economic_sector_code` string, `trbc_industry_group_code` string, `asset_id` string, `topics` string, `headline` string, `language` string, `trbc_business_sector_code` string, `ric` string, `quote_permid` string, `pnac` string, `trbc_industry_code` string, `story_date_time` string, `issue_permid` string, `quote_id` string, `exchange_description` string, `issuer_orgid` string, `exchange_code` string, `trbc_activity_code` string, `related_rics` string, `instrument_id` string, PRIMARY KEY (`unique_story_index`), LABEL (`headline`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-newspaper');
CREATE OR REPLACE CONCEPT `macro_sector` (`description` string, `macro_sector_id` integer, PRIMARY KEY (`macro_sector_id`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-pie-chart');
CREATE OR REPLACE CONCEPT `joint_venture` (`social_pillar_score_grade` string, `ultimate_parent_perm_id` string, `ownership_phrase_description` string, `naics_industry_group_code` string, `ownership_characterization` string, `official_name` string, `ultimate_parent_orgid` string, `ultimate_parent_official_name` string, `immediate_parent_official_name` string, `governance_pillar_score` string, `immediate_parent_orgid` string, `trbc_industry_name` string, `legal_entity_orgid` string, `naics_sector_name` string, `naics_industry_group_name` string, `related_entity_type` string, `relationship_type` string, `ownership_percentage` string, `id` string, `environment_pillar_score_grade` string, `related_entity_type_description` string, `naics_sector_code` string, `environment_pillar_score` string, `node_level` string, `related_orgid` string, `social_pillar_score` string, `related_official_name` string, `governance_pillar_score_grade` string, `immediate_parent_perm_id` string, PRIMARY KEY (`id`), LABEL (`official_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-handshake');
CREATE OR REPLACE CONCEPT `issuer` (`issuer_id` integer, `issuer_name` string, `industry_id` integer, `country_id` integer, PRIMARY KEY (`issuer_id`), LABEL (`issuer_name`), CONSTRAINT `works_with` FOREIGN KEY (`country_id`) REFERENCES `owner` (`country_id`) INVERSEOF `works_with_` , CONSTRAINT `has_security` FOREIGN KEY (`industry_id`) REFERENCES `security` (`industry_id`) INVERSEOF `of_issuer` , CONSTRAINT `in_province` FOREIGN KEY (`country_id`) REFERENCES `province` (`country_id`) INVERSEOF `of_issuer` , CONSTRAINT `issued_in` FOREIGN KEY (`country_id`) REFERENCES `country` (`country_id`) INVERSEOF `has_issues` , CONSTRAINT `of_industry` FOREIGN KEY (`industry_id`) REFERENCES `industry` (`industry_id`) INVERSEOF `has_issuer` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-stamp');
CREATE OR REPLACE CONCEPT `investment_style` (`description` string, `style_id` integer, `parent_style_id` integer, PRIMARY KEY (`style_id`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-coins');
CREATE OR REPLACE CONCEPT `industry` (`description` string, `sector_id` integer, `industry_id` integer, PRIMARY KEY (`industry_id`), LABEL (`description`), CONSTRAINT `in_sector` FOREIGN KEY (`sector_id`) REFERENCES `sector` (`sector_id`) INVERSEOF `in_industry` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-industry');
CREATE OR REPLACE CONCEPT `holding_source` (`description` string, `source_id` integer, PRIMARY KEY (`source_id`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-funnel-dollar');
CREATE OR REPLACE CONCEPT `holdings` (`security_id` integer, `shares_held` bigint, `report_date` integer, `shares_changed` bigint, `value_held` bigint, `owner_id` integer, `value_of_shares_changed` bigint, `source` integer, `percent_of_shares_outstanding` float, `prior_report_date` integer, `prior_source` integer, `change_sign` string, `new_position` string, PRIMARY KEY (`owner_id`, `security_id`), LABEL (`value_held`), CONSTRAINT `owned_by` FOREIGN KEY (`owner_id`) REFERENCES `owner` (`owner_id`) INVERSEOF `has_holdings`  TRANSITIVE, CONSTRAINT `of_security` FOREIGN KEY (`security_id`) REFERENCES `security` (`security_id`) INVERSEOF `has_holdings` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-folder');
CREATE OR REPLACE CONCEPT `global_region` (`region_id` integer, `name` string, `short_name` string, PRIMARY KEY (`region_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-globe-europe');
CREATE OR REPLACE CONCEPT `fund_ticker` (`fund_ticker_symbol` string, `owner_id` integer, PRIMARY KEY (`owner_id`), LABEL (`fund_ticker_symbol`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-dollar-sign');
CREATE OR REPLACE CONCEPT `exchange` (`description` string, `exchange_id` string, `country_id` integer, PRIMARY KEY (`exchange_id`), LABEL (`description`), CONSTRAINT `in_country` FOREIGN KEY (`country_id`) REFERENCES `country` (`country_id`) INVERSEOF `has_exchanges` , CONSTRAINT `of_region` FOREIGN KEY (`country_id`) REFERENCES `region_country` (`country_id`) INVERSEOF `_has_exchange` , CONSTRAINT `of_issuer_country` FOREIGN KEY (`country_id`) REFERENCES `issuer` (`country_id`) INVERSEOF `exchange_in_country` , CONSTRAINT `of_owner_country` FOREIGN KEY (`country_id`) REFERENCES `owner` (`country_id`) INVERSEOF `has_exchange_` , CONSTRAINT `of_province` FOREIGN KEY (`country_id`) REFERENCES `province` (`country_id`) INVERSEOF `has_exchange` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-exchange');
CREATE OR REPLACE CONCEPT `country` (`country_name` string, `country_id` integer, PRIMARY KEY (`country_id`), LABEL (`country_name`), CONSTRAINT `of_owner` FOREIGN KEY (`country_id`) REFERENCES `owner` (`country_id`) INVERSEOF `_in_country` , CONSTRAINT `has_province` FOREIGN KEY (`country_id`) REFERENCES `province` (`country_id`) INVERSEOF `in_country` , CONSTRAINT `has_region` FOREIGN KEY (`country_id`) REFERENCES `region_country` (`country_id`) INVERSEOF `in_country_` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-flag');
CREATE OR REPLACE CONCEPT `company2` (`trbc_industry_group_name` string, `ric` string, `country_of_exchange` string, `trbc_industry_name` string, `company_common_name` string, `organization_id` string, `environment_pillar_score_grade` string, PRIMARY KEY (`organization_id`), LABEL (`company_common_name`), CONSTRAINT `in_joint_venture` MULTIREFERENCE `company2` INVERSEOF `has_joint_venture_with`  TRANSITIVE, CONSTRAINT `has_affiliate_` MULTIREFERENCE `company2` INVERSEOF `is_affiliated_with`  TRANSITIVE, CONSTRAINT `owns_company_` MULTIREFERENCE `company2` INVERSEOF `owned_by_company_`  TRANSITIVE) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-building-flag');
CREATE OR REPLACE CONCEPT `company` (`trbc_industry_group_name` string, `ric` string, `country_of_exchange` string, `trbc_industry_name` string, `organization_permid` string, `id` string, `company_common_name` string, `environment_pillar_score_grade` string, PRIMARY KEY (`organization_permid`), LABEL (`company_common_name`), CONSTRAINT `owned_by_company` MULTIREFERENCE `company` INVERSEOF `owns_company`  TRANSITIVE(3), CONSTRAINT `has_joint_venture` MULTIREFERENCE `joint_venture` INVERSEOF `of_company_` , CONSTRAINT `has_affiliate` MULTIREFERENCE `affiliate` INVERSEOF `of_company`  TRANSITIVE(20), CONSTRAINT `has_ownership` MULTIREFERENCE `ownership` INVERSEOF `has_owner`  TRANSITIVE(20), CONSTRAINT `joint_venture_company` MULTIREFERENCE `company` INVERSEOF `joint_venture_company2`  TRANSITIVE(3), CONSTRAINT `affiliate_company` MULTIREFERENCE `company` INVERSEOF `affiliate_company2`  TRANSITIVE(3)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-building');
CREATE OR REPLACE CONCEPT `cik` (`cik` bigint, `report_date` integer, `owner_id` integer, PRIMARY KEY (`owner_id`), LABEL (`cik`)) INHERITS (`thing`) DESCRIPTION 'Mapping of OP owner id to CIK (central index key). Includes mutual funds and 13F institutions. Note that there will be funds and institutions in the owner file for which a CIK is not available.' WITH TAGS (`icon` = 'fa-key');
CREATE OR REPLACE CONCEPT `asset_region` (`description` string, `asset_region_code` integer, PRIMARY KEY (`asset_region_code`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-map-marked-alt');
CREATE OR REPLACE CONCEPT `asset_codes` (`description` string, `asset_code` integer, `lower_range` integer, `upper_range` integer, PRIMARY KEY (`asset_code`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-barcode');
CREATE OR REPLACE CONCEPT `affiliate` (`social_pillar_score_grade` string, `ultimate_parent_perm_id` string, `ownership_phrase_description` string, `naics_industry_group_code` string, `ownership_characterization` string, `official_name` string, `ultimate_parent_orgid` string, `ultimate_parent_official_name` string, `immediate_parent_official_name` string, `governance_pillar_score` string, `immediate_parent_orgid` string, `trbc_industry_name` string, `legal_entity_orgid` string, `naics_sector_name` string, `naics_industry_group_name` string, `related_entity_type` string, `relationship_type` string, `ownership_percentage` string, `id` string, `environment_pillar_score_grade` string, `related_entity_type_description` string, `naics_sector_code` string, `environment_pillar_score` string, `node_level` string, `related_orgid` string, `social_pillar_score` string, `related_official_name` string, `governance_pillar_score_grade` string, `immediate_parent_perm_id` string, PRIMARY KEY (`id`), LABEL (`official_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-repeat');
CREATE OR REPLACE CONCEPT `venture_capital_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'venture capital';
CREATE OR REPLACE CONCEPT `tier_1_financial_type`  INHERITS (`ownership_type`);
CREATE OR REPLACE CONCEPT `strategic_entities_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'strategic entities';
CREATE OR REPLACE CONCEPT `sovereign_wealth_fund_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'sovereign wealth fund';
CREATE OR REPLACE CONCEPT `research_firm_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'research firm';
CREATE OR REPLACE CONCEPT `private_equity_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'private equity';
CREATE OR REPLACE CONCEPT `pension_fund_portfolio_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'pension fund portfolio';
CREATE OR REPLACE CONCEPT `pension_fund_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'pension fund';
CREATE OR REPLACE CONCEPT `mutual_fund_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'mutual fund';
CREATE OR REPLACE CONCEPT `investment_managers_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'investment managers';
CREATE OR REPLACE CONCEPT `investment_advisor_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'investment advisor';
CREATE OR REPLACE CONCEPT `investment_advisor_hedge_fund_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'investment advisor/hedge fund';
CREATE OR REPLACE CONCEPT `insurance_company_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'insurance company';
CREATE OR REPLACE CONCEPT `individual_investor_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'individual investor';
CREATE OR REPLACE CONCEPT `independent_research_firm_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'independent research firm';
CREATE OR REPLACE CONCEPT `holding_company_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'holding company';
CREATE OR REPLACE CONCEPT `hedge_fund_portfolio_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'hedge fund portfolio';
CREATE OR REPLACE CONCEPT `hedge_fund_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'hedge fund';
CREATE OR REPLACE CONCEPT `government_agency_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'government agency';
CREATE OR REPLACE CONCEPT `funds_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'funds';
CREATE OR REPLACE CONCEPT `foundation_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'foundation';
CREATE OR REPLACE CONCEPT `endowment_fund_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'endowment fund';
CREATE OR REPLACE CONCEPT `corporation_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'corporation';
CREATE OR REPLACE CONCEPT `brokerage_firms_ownership_type`  INHERITS (`ownership_type`) FROM timbr.`ownership_type` WHERE `description` = 'brokerage firms';
CREATE OR REPLACE CONCEPT `finance_company_ownership_type`  INHERITS (`tier_1_financial_type`);
CREATE OR REPLACE CONCEPT `bank_and_trust_ownership_type`  INHERITS (`tier_1_financial_type`);
CREATE OR REPLACE CONCEPT `utilities`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'utilities';
CREATE OR REPLACE CONCEPT `telecommunication_services`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'telecommunication services';
CREATE OR REPLACE CONCEPT `technology`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'technology';
CREATE OR REPLACE CONCEPT `materials`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'materials';
CREATE OR REPLACE CONCEPT `industrials`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'industrials';
CREATE OR REPLACE CONCEPT `healthcare`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'health care';
CREATE OR REPLACE CONCEPT `financials`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'financials';
CREATE OR REPLACE CONCEPT `energy`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'Energy';
CREATE OR REPLACE CONCEPT `diversified`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'diversified';
CREATE OR REPLACE CONCEPT `consumer_staples`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'consumer staples';
CREATE OR REPLACE CONCEPT `consumer_discretionary`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'consumer discretionary';
CREATE OR REPLACE CONCEPT `clean_technology`  INHERITS (`macro_sector`) FROM timbr.`macro_sector` WHERE `description` = 'clean technology';
CREATE OR REPLACE CONCEPT `low_env_pillar_score_company`  INHERITS (`company2`) DESCRIPTION 'Companies with environmental pillar score grade less than A-' FROM timbr.`company2` WHERE `environment_pillar_score_grade` NOT LIKE 'A%';
CREATE OR REPLACE CONCEPT `high_env_pillar_score_company`  INHERITS (`company2`) DESCRIPTION 'Companies with environmental pillar score grade A+, A, or A-' FROM timbr.`company2` WHERE `environment_pillar_score_grade` = 'A+' OR `environment_pillar_score_grade` = 'A' OR `environment_pillar_score_grade` = 'A-';
CREATE OR REPLACE CONCEPT `low_environment_pillar_score_company`  INHERITS (`company`) FROM timbr.`company` WHERE `environment_pillar_score_grade` NOT LIKE 'A%';
CREATE OR REPLACE CONCEPT `high_environment_pillar_score_company`  INHERITS (`company`) FROM timbr.`company` WHERE `environment_pillar_score_grade` = 'A' OR `environment_pillar_score_grade` = 'A+' OR `environment_pillar_score_grade` = 'A-';