CREATE OR REPLACE PROPERTY `prefix` string;
CREATE OR REPLACE PROPERTY `use` string;
CREATE OR REPLACE PROPERTY `birth_date` string;
CREATE OR REPLACE PROPERTY `hospitalization_end_date` string;
CREATE OR REPLACE PROPERTY `language` string;
CREATE OR REPLACE PROPERTY `div` string;
CREATE OR REPLACE PROPERTY `reference` string;
CREATE OR REPLACE PROPERTY `effective_date` string;
CREATE OR REPLACE PROPERTY `provider_practitioner_id` string;
CREATE OR REPLACE PROPERTY `authored_on` string;
CREATE OR REPLACE PROPERTY `id` integer;
CREATE OR REPLACE PROPERTY `text` string;
CREATE OR REPLACE PROPERTY `create_date` string;
CREATE OR REPLACE PROPERTY `issued` timestamp;
CREATE OR REPLACE PROPERTY `plan_definition_id` string;
CREATE OR REPLACE PROPERTY `given` string;
CREATE OR REPLACE PROPERTY `method` string;
CREATE OR REPLACE PROPERTY `medication_request_category` string;
CREATE OR REPLACE PROPERTY `priority` string;
CREATE OR REPLACE PROPERTY `requester_organization_id` string;
CREATE OR REPLACE PROPERTY `interpretation` string;
CREATE OR REPLACE PROPERTY `observation_id` string;
CREATE OR REPLACE PROPERTY `meta` string;
CREATE OR REPLACE PROPERTY `patient_id` string;
CREATE OR REPLACE PROPERTY `organization_id` string;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `birth_place_city` string;
CREATE OR REPLACE PROPERTY `diagnostic_report_category` string;
CREATE OR REPLACE PROPERTY `encounter_type` string;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE PROPERTY `end_date` string;
CREATE OR REPLACE PROPERTY `clinical_status` string;
CREATE OR REPLACE PROPERTY `gender` string;
CREATE OR REPLACE PROPERTY `asserted_date` string;
CREATE OR REPLACE PROPERTY `hospitalization_start_date` string;
CREATE OR REPLACE PROPERTY `address_state` string;
CREATE OR REPLACE PROPERTY `claim_id` string;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `medication_request_id` string;
CREATE OR REPLACE PROPERTY `conclusion` string;
CREATE OR REPLACE PROPERTY `address_use` string;
CREATE OR REPLACE PROPERTY `versionid` string;
CREATE OR REPLACE PROPERTY `care_plan_category` string;
CREATE OR REPLACE PROPERTY `care_team_id` string;
CREATE OR REPLACE PROPERTY `encounter_id` string;
CREATE OR REPLACE PROPERTY `value` string;
CREATE OR REPLACE PROPERTY `insurer_organization_id` string;
CREATE OR REPLACE PROPERTY `start_date` string;
CREATE OR REPLACE PROPERTY `claim_net_value` float;
CREATE OR REPLACE PROPERTY `address_postal_code` string;
CREATE OR REPLACE PROPERTY `address_country` string;
CREATE OR REPLACE PROPERTY `birth_place_state` string;
CREATE OR REPLACE PROPERTY `practitioner_id` string;
CREATE OR REPLACE PROPERTY `diagnostic_report_id` string;
CREATE OR REPLACE PROPERTY `display` string;
CREATE OR REPLACE PROPERTY `birth_place_country` string;
CREATE OR REPLACE PROPERTY `condition_category` string;
CREATE OR REPLACE PROPERTY `care_plan_id` string;
CREATE OR REPLACE PROPERTY `intent` string;
CREATE OR REPLACE PROPERTY `resourcetype` string;
CREATE OR REPLACE PROPERTY `condition_id` string;
CREATE OR REPLACE PROPERTY `address_city` string;
CREATE OR REPLACE PROPERTY `comment` string;
CREATE OR REPLACE PROPERTY `family` string;
CREATE OR REPLACE CONCEPT `practitioner` (`gender` string, `reference` string, `display` string, `address_country` string, `practitioner_id` string, `birth_date` string, `name` string, `address_city` string, `address_postal_code` string, `address_state` string, `language` string, PRIMARY KEY (`practitioner_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-doctor');
CREATE OR REPLACE CONCEPT `patient` (`text` string, `address_country` string, `resourcetype` string, `family` string, `name` string, `address_city` string, `div` string, `address_state` string, `versionid` string, `gender` string, `meta` string, `use` string, `given` string, `patient_id` string, `birth_place_city` string, `birth_place_state` string, `birth_date` string, `birth_place_country` string, `address_use` string, `value` string, `prefix` string, `address_postal_code` string, PRIMARY KEY (`patient_id`), LABEL (`name`), CONSTRAINT `recieved` FOREIGN KEY (`patient_id`) REFERENCES `diagnostic_report` (`patient_id`) INVERSEOF `for` , CONSTRAINT `has_a` FOREIGN KEY (`patient_id`) REFERENCES `medication_request` (`patient_id`) INVERSEOF `of_a` , CONSTRAINT `attended` FOREIGN KEY (`patient_id`) REFERENCES `encounter` (`patient_id`) INVERSEOF `with` , CONSTRAINT `has` FOREIGN KEY (`patient_id`) REFERENCES `care_plan` (`patient_id`) INVERSEOF `belongs_to` , CONSTRAINT `got` FOREIGN KEY (`patient_id`) REFERENCES `observation` (`patient_id`) INVERSEOF `for_a` , CONSTRAINT `issues` FOREIGN KEY (`patient_id`) REFERENCES `claim` (`patient_id`) INVERSEOF `belong_to` , CONSTRAINT `is_in_a` FOREIGN KEY (`patient_id`) REFERENCES `condition` (`patient_id`) INVERSEOF `of` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user');
CREATE OR REPLACE CONCEPT `observation` (`method` string, `status` string, `patient_id` string, `observation_id` string, `effective_date` string, `comment` string, `issued` timestamp, `interpretation` string, PRIMARY KEY (`observation_id`), LABEL (`comment`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-magnifying-glass');
CREATE OR REPLACE CONCEPT `medication_request` (`status` string, `patient_id` string, `intent` string, `authored_on` string, `practitioner_id` string, `medication_request_id` string, `medication_request_category` string, `requester_organization_id` string, PRIMARY KEY (`medication_request_id`), LABEL (`medication_request_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-pills');
CREATE OR REPLACE CONCEPT `encounter` (`start_date` string, `status` string, `patient_id` string, `end_date` string, `encounter_id` string, `practitioner_id` string, `encounter_type` string, PRIMARY KEY (`encounter_id`), LABEL (`encounter_type`), CONSTRAINT `made_by` FOREIGN KEY (`practitioner_id`) REFERENCES `practitioner` (`practitioner_id`) INVERSEOF `participated` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-calendar-check');
CREATE OR REPLACE CONCEPT `diagnostic_report` (`status` string, `conclusion` string, `patient_id` string, `diagnostic_report_category` string, `effective_date` string, `diagnostic_report_id` string, `issued` timestamp, PRIMARY KEY (`diagnostic_report_id`), LABEL (`conclusion`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-stethoscope');
CREATE OR REPLACE CONCEPT `condition` (`gender` string, `patient_id` string, `condition_category` string, `practitioner_id` string, `clinical_status` string, `asserted_date` string, `condition_id` string, PRIMARY KEY (`condition_id`), LABEL (`clinical_status`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-heartbeat');
CREATE OR REPLACE CONCEPT `claim` (`claim_id` string, `priority` string, `create_date` string, `claim_net_value` float, `status` string, `patient_id` string, `insurer_organization_id` string, `hospitalization_start_date` string, `provider_practitioner_id` string, `hospitalization_end_date` string, PRIMARY KEY (`claim_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-money-check-dollar');
CREATE OR REPLACE CONCEPT `care_plan` (`description` string, `care_plan_category` string, `id` integer, `start_date` string, `status` string, `plan_definition_id` string, `patient_id` string, `end_date` string, `care_team_id` string, `care_plan_id` string, `practitioner_id` string, `organization_id` string, PRIMARY KEY (`care_plan_id`), LABEL (`care_plan_category`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-clipboard-user');
CREATE OR REPLACE CONCEPT `patient_initiated_encounter`  INHERITS (`encounter`) FROM timbr.`encounter` WHERE `encounter_type` = 'Patient-initiated encounter';
CREATE OR REPLACE CONCEPT `office_visit`  INHERITS (`encounter`) FROM timbr.`encounter` WHERE `encounter_type` = 'Office Visit';
CREATE OR REPLACE CONCEPT `follow_up_encounter`  INHERITS (`encounter`) FROM timbr.`encounter` WHERE `encounter_type` = 'Follow-up encounter';