CREATE OR REPLACE PROPERTY `isextendablebyholder` boolean;
CREATE OR REPLACE PROPERTY `hasdirector` string;
CREATE OR REPLACE PROPERTY `hasextendableperiod` string;
CREATE OR REPLACE PROPERTY `isowedto` string;
CREATE OR REPLACE PROPERTY `isseasoned` boolean;
CREATE OR REPLACE PROPERTY `isownedby` string;
CREATE OR REPLACE PROPERTY `hassignificantcontrollinginterestparty` string;
CREATE OR REPLACE PROPERTY `hasdebtranking` string;
CREATE OR REPLACE PROPERTY `hassubsidiary` string;
CREATE OR REPLACE PROPERTY `hasfirstputprice` string;
CREATE OR REPLACE PROPERTY `topconceptof` string;
CREATE OR REPLACE PROPERTY `haspartialredemptionallocationconvention` string;
CREATE OR REPLACE PROPERTY `hasbasemoneyunit` string;
CREATE OR REPLACE PROPERTY `maybetradedin` string;
CREATE OR REPLACE PROPERTY `hasresponsibility` string;
CREATE OR REPLACE PROPERTY `iscollateralizationof` string;
CREATE OR REPLACE PROPERTY `reflects` string;
CREATE OR REPLACE PROPERTY `isinstrumentof` string;
CREATE OR REPLACE PROPERTY `memberlist` string;
CREATE OR REPLACE PROPERTY `definestermsfor` string;
CREATE OR REPLACE PROPERTY `hasapplicabledateperiod` string;
CREATE OR REPLACE PROPERTY `hasextraordinaryredemptionprovision` string;
CREATE OR REPLACE PROPERTY `hasredemptionamount` string;
CREATE OR REPLACE PROPERTY `isowedby` string;
CREATE OR REPLACE PROPERTY `isredeemableatissueroption` boolean;
CREATE OR REPLACE PROPERTY `actsin` string;
CREATE OR REPLACE PROPERTY `haslockoutperiod` string;
CREATE OR REPLACE PROPERTY `isversionof` string;
CREATE OR REPLACE PROPERTY `hasfirstname` string;
CREATE OR REPLACE PROPERTY `hasmunicipaltrustee` string;
CREATE OR REPLACE PROPERTY `istradedon` string;
CREATE OR REPLACE PROPERTY `hasdistributionmethod` string;
CREATE OR REPLACE PROPERTY `hasfirstputdate` string;
CREATE OR REPLACE PROPERTY `shortname` string;
CREATE OR REPLACE PROPERTY `hasleg` string;
CREATE OR REPLACE PROPERTY `haslastname` string;
CREATE OR REPLACE PROPERTY `hascallprice` string;
CREATE OR REPLACE PROPERTY `hasfundstype` string;
CREATE OR REPLACE PROPERTY `hasconstituent` string;
CREATE OR REPLACE PROPERTY `isincorporatedin` string;
CREATE OR REPLACE PROPERTY `hasregistryname` string;
CREATE OR REPLACE PROPERTY `hascapacity` string;
CREATE OR REPLACE PROPERTY `islifecycleof` string;
CREATE OR REPLACE PROPERTY `hasvestedinit` string;
CREATE OR REPLACE PROPERTY `hasrighttoretain` boolean;
CREATE OR REPLACE PROPERTY `hasexerciseterms` string;
CREATE OR REPLACE PROPERTY `islinkedtoaccount` string;
CREATE OR REPLACE PROPERTY `hasgeneralpartner` string;
CREATE OR REPLACE PROPERTY `hasownedentity` string;
CREATE OR REPLACE PROPERTY `hasoperand` string;
CREATE OR REPLACE PROPERTY `haspoolnumber` integer;
CREATE OR REPLACE PROPERTY `hassubtrahend` string;
CREATE OR REPLACE PROPERTY `confersnumberofvotespershare` decimal;
CREATE OR REPLACE PROPERTY `hasdefaultthresholdamount` string;
CREATE OR REPLACE PROPERTY `prop3_del` integer;
CREATE OR REPLACE PROPERTY `isbankqualified` boolean;
CREATE OR REPLACE PROPERTY `hasfulllegalname` string;
CREATE OR REPLACE PROPERTY `hasfixeddividendrate` string;
CREATE OR REPLACE PROPERTY `isestimate` boolean;
CREATE OR REPLACE PROPERTY `isseniorto` string;
CREATE OR REPLACE PROPERTY `representsaninterestin` string;
CREATE OR REPLACE PROPERTY `hasmaidenname` string;
CREATE OR REPLACE PROPERTY `isregisteredwith` string;
CREATE OR REPLACE PROPERTY `isapartyto` string;
CREATE OR REPLACE PROPERTY `authorizesthrough` string;
CREATE OR REPLACE PROPERTY `hasvotingrestriction` string;
CREATE OR REPLACE PROPERTY `haspostdirectionalsymbol` string;
CREATE OR REPLACE PROPERTY `isindexto` string;
CREATE OR REPLACE PROPERTY `hasreach` string;
CREATE OR REPLACE PROPERTY `licenses` string;
CREATE OR REPLACE PROPERTY `regulatessupplyof` string;
CREATE OR REPLACE PROPERTY `hasadjustabledividendrate` string;
CREATE OR REPLACE PROPERTY `regulates` string;
CREATE OR REPLACE PROPERTY `holdssomemeansof` string;
CREATE OR REPLACE PROPERTY `sellsto` string;
CREATE OR REPLACE PROPERTY `isintereston` string;
CREATE OR REPLACE PROPERTY `istriggeredby` string;
CREATE OR REPLACE PROPERTY `hassurname` string;
CREATE OR REPLACE PROPERTY `hasearlierform` string;
CREATE OR REPLACE PROPERTY `hasdimension` string;
CREATE OR REPLACE PROPERTY `hascontrollingaffiliate` string;
CREATE OR REPLACE PROPERTY `usesadministrativelanguage` string;
CREATE OR REPLACE PROPERTY `buys` string;
CREATE OR REPLACE PROPERTY `hasexchangename` string;
CREATE OR REPLACE PROPERTY `hasremarketingagent` string;
CREATE OR REPLACE PROPERTY `isaffiliateof` string;
CREATE OR REPLACE PROPERTY `hasdividendgraceperiod` string;
CREATE OR REPLACE PROPERTY `hassharesoutstanding` integer;
CREATE OR REPLACE PROPERTY `allowspaymentinkind` boolean;
CREATE OR REPLACE PROPERTY `producesratingsfor` string;
CREATE OR REPLACE PROPERTY `haspremium` string;
CREATE OR REPLACE PROPERTY `hasfinalmaturitydate` string;
CREATE OR REPLACE PROPERTY `hasobligation` string;
CREATE OR REPLACE PROPERTY `isredeemableatshareholderoption` boolean;
CREATE OR REPLACE PROPERTY `haslimitedpartner` string;
CREATE OR REPLACE PROPERTY `isvalueof` string;
CREATE OR REPLACE PROPERTY `hasstreetsuffix` string;
CREATE OR REPLACE PROPERTY `hascounterparty` string;
CREATE OR REPLACE PROPERTY `hasoperatingaddress` string;
CREATE OR REPLACE PROPERTY `owes` string;
CREATE OR REPLACE PROPERTY `hasexchangeacronym` string;
CREATE OR REPLACE PROPERTY `hasmerchantcategorydescription` string;
CREATE OR REPLACE PROPERTY `haspremiumamount` string;
CREATE OR REPLACE PROPERTY `isauthorizedby` string;
CREATE OR REPLACE PROPERTY `hasputfrequency` string;
CREATE OR REPLACE PROPERTY `exemplifies` string;
CREATE OR REPLACE PROPERTY `undergoes` string;
CREATE OR REPLACE PROPERTY `issubsidiaryof` string;
CREATE OR REPLACE PROPERTY `hastransactiondescription` string;
CREATE OR REPLACE PROPERTY `haspublisher` string;
CREATE OR REPLACE PROPERTY `ispublishedby` string;
CREATE OR REPLACE PROPERTY `haspredirectionalsymbol` string;
CREATE OR REPLACE PROPERTY `hasfirstparcalldate` string;
CREATE OR REPLACE PROPERTY `hasprincipalrepaymentdate` string;
CREATE OR REPLACE PROPERTY `hasindexname` string;
CREATE OR REPLACE PROPERTY `hasquotelotsize` integer;
CREATE OR REPLACE PROPERTY `hasfirstcallprice` string;
CREATE OR REPLACE PROPERTY `elects` string;
CREATE OR REPLACE PROPERTY `isidentifiedby` string;
CREATE OR REPLACE PROPERTY `isparentcompanyof` string;
CREATE OR REPLACE PROPERTY `hasregisteredaddress` string;
CREATE OR REPLACE PROPERTY `hasindividualpostcode` string;
CREATE OR REPLACE PROPERTY `hassovereigntyover` string;
CREATE OR REPLACE PROPERTY `isconstitutedby` string;
CREATE OR REPLACE PROPERTY `hasdividenddeclarationdate` string;
CREATE OR REPLACE PROPERTY `hasgender` string;
CREATE OR REPLACE PROPERTY `isassignable` boolean;
CREATE OR REPLACE PROPERTY `isownedthinginrole` string;
CREATE OR REPLACE PROPERTY `hasresetdateoffset` string;
CREATE OR REPLACE PROPERTY `hasfirstpremiumcalldate` string;
CREATE OR REPLACE PROPERTY `hasestateordeathputfeature` boolean;
CREATE OR REPLACE PROPERTY `hasvalueexpressedin` string;
CREATE OR REPLACE PROPERTY `hasprioritylevel` string;
CREATE OR REPLACE PROPERTY `hasregistryentry` string;
CREATE OR REPLACE PROPERTY `hascontractparty` string;
CREATE OR REPLACE PROPERTY `hasminuend` string;
CREATE OR REPLACE PROPERTY `hassecondaryunit` string;
CREATE OR REPLACE PROPERTY `hasearliestredemptiondate` string;
CREATE OR REPLACE PROPERTY `hasinvestmentownership` string;
CREATE OR REPLACE PROPERTY `hasspreadrange` string;
CREATE OR REPLACE PROPERTY `hasbookdepth` integer;
CREATE OR REPLACE PROPERTY `hasdescription` string;
CREATE OR REPLACE PROPERTY `hasguarantor` string;
CREATE OR REPLACE PROPERTY `iscontrolledtosomedegreeby` string;
CREATE OR REPLACE PROPERTY `hasstreetaddress` string;
CREATE OR REPLACE PROPERTY `verifiesaddress` string;
CREATE OR REPLACE PROPERTY `hasfirstcouponpaymentdate` string;
CREATE OR REPLACE PROPERTY `hasresponsibleparty` string;
CREATE OR REPLACE PROPERTY `hastradingdatetime` string;
CREATE OR REPLACE PROPERTY `prop2_del` string;
CREATE OR REPLACE PROPERTY `hasawarddate` string;
CREATE OR REPLACE PROPERTY `hasclosingpricedeterminationmethod` string;
CREATE OR REPLACE PROPERTY `hasdateddate` string;
CREATE OR REPLACE PROPERTY `haslegaladdress` string;
CREATE OR REPLACE PROPERTY `hasnatureofcontrol` string;
CREATE OR REPLACE PROPERTY `isdirectorof` string;
CREATE OR REPLACE PROPERTY `hasunderlier` string;
CREATE OR REPLACE PROPERTY `hasdebtamount` string;
CREATE OR REPLACE PROPERTY `hassharepaymentstatus` string;
CREATE OR REPLACE PROPERTY `islegalopinionavailable` boolean;
CREATE OR REPLACE PROPERTY `isexemplifiedby` string;
CREATE OR REPLACE PROPERTY `hastreasuryshares` integer;
CREATE OR REPLACE PROPERTY `hasgoverningjurisdiction` string;
CREATE OR REPLACE PROPERTY `hasminimumredemptionprice` string;
CREATE OR REPLACE PROPERTY `hasoperatingorsegmentindicator` string;
CREATE OR REPLACE PROPERTY `pays` string;
CREATE OR REPLACE PROPERTY `hasdegreeofcontrol` string;
CREATE OR REPLACE PROPERTY `hascontractualelement` string;
CREATE OR REPLACE PROPERTY `hasprimaryaccountholder` string;
CREATE OR REPLACE PROPERTY `istenderin` string;
CREATE OR REPLACE PROPERTY `verifiesplaceofbirth` string;
CREATE OR REPLACE PROPERTY `isowed` string;
CREATE OR REPLACE PROPERTY `hasdateofbirth` string;
CREATE OR REPLACE PROPERTY `haslastcouponpaymentdate` string;
CREATE OR REPLACE PROPERTY `hasnonbindingterms` string;
CREATE OR REPLACE PROPERTY `isauthorizedthrough` string;
CREATE OR REPLACE PROPERTY `hasdenomination` string;
CREATE OR REPLACE PROPERTY `hasconvertibledate` string;
CREATE OR REPLACE PROPERTY `haspartyincontrol` string;
CREATE OR REPLACE PROPERTY `issupersinker` boolean;
CREATE OR REPLACE PROPERTY `characterizes` string;
CREATE OR REPLACE PROPERTY `hasauthorizedparty` string;
CREATE OR REPLACE PROPERTY `supplies` string;
CREATE OR REPLACE PROPERTY `hasfloatingshares` integer;
CREATE OR REPLACE PROPERTY `hasgeneratingentityidentifier` string;
CREATE OR REPLACE PROPERTY `isofficerof` string;
CREATE OR REPLACE PROPERTY `allowsautoreinvestment` boolean;
CREATE OR REPLACE PROPERTY `hascitizenship` string;
CREATE OR REPLACE PROPERTY `isissuedinform` string;
CREATE OR REPLACE PROPERTY `hasdelistingdate` string;
CREATE OR REPLACE PROPERTY `iscapacityof` string;
CREATE OR REPLACE PROPERTY `isreflectedin` string;
CREATE OR REPLACE PROPERTY `authorizes` string;
CREATE OR REPLACE PROPERTY `hasdurationofprotection` string;
CREATE OR REPLACE PROPERTY `hasquotationblockamountbasis` string;
CREATE OR REPLACE PROPERTY `hasplaceofbirth` string;
CREATE OR REPLACE PROPERTY `indicatesnumberofshares` decimal;
CREATE OR REPLACE PROPERTY `reportson` string;
CREATE OR REPLACE PROPERTY `involvesmultipleevents` boolean;
CREATE OR REPLACE PROPERTY `hasendingbalance` string;
CREATE OR REPLACE PROPERTY `provisions` string;
CREATE OR REPLACE PROPERTY `hascommencementdate` string;
CREATE OR REPLACE PROPERTY `hasworstmeasure` decimal;
CREATE OR REPLACE PROPERTY `hasfirstparcallprice` string;
CREATE OR REPLACE PROPERTY `hassubregion` string;
CREATE OR REPLACE PROPERTY `hasprimaryaddressnumber` string;
CREATE OR REPLACE PROPERTY `hasmailrouting` string;
CREATE OR REPLACE PROPERTY `hasownedthing` string;
CREATE OR REPLACE PROPERTY `isextendablebyissuer` boolean;
CREATE OR REPLACE PROPERTY `hasstartingbalance` string;
CREATE OR REPLACE PROPERTY `hasgivenname` string;
CREATE OR REPLACE PROPERTY `hasticksize` string;
CREATE OR REPLACE PROPERTY `issubregionof` string;
CREATE OR REPLACE PROPERTY `hasmiddlenameorinitial` string;
CREATE OR REPLACE PROPERTY `hasguaranteedamount` string;
CREATE OR REPLACE PROPERTY `isguaranteedby` string;
CREATE OR REPLACE PROPERTY `verifiesdateofbirth` string;
CREATE OR REPLACE PROPERTY `isregistrationauthorityfor` string;
CREATE OR REPLACE PROPERTY `supersedes` string;
CREATE OR REPLACE PROPERTY `haspaymentamount` string;
CREATE OR REPLACE PROPERTY `operatesincountry` string;
CREATE OR REPLACE PROPERTY `hasspecificationversion` string;
CREATE OR REPLACE PROPERTY `iscontrollingaffiliateof` string;
CREATE OR REPLACE PROPERTY `islimitedpartnerof` string;
CREATE OR REPLACE PROPERTY `hasowningparty` string;
CREATE OR REPLACE PROPERTY `hasprimaryfederalregulator` string;
CREATE OR REPLACE PROPERTY `member` string;
CREATE OR REPLACE PROPERTY `ispremiumon` string;
CREATE OR REPLACE PROPERTY `hascorporateofficer` string;
CREATE OR REPLACE PROPERTY `hasquotationsettlementbasis` string;
CREATE OR REPLACE PROPERTY `issuppliedby` string;
CREATE OR REPLACE PROPERTY `usesratingparty` string;
CREATE OR REPLACE PROPERTY `islistedvia` string;
CREATE OR REPLACE PROPERTY `haspostalcode` string;
CREATE OR REPLACE PROPERTY `governspaymentof` string;
CREATE OR REPLACE PROPERTY `hasextensionprovision` string;
CREATE OR REPLACE PROPERTY `isnotclearedin` string;
CREATE OR REPLACE PROPERTY `islegallyrecordedin` string;
CREATE OR REPLACE PROPERTY `hasoverallperiod` string;
CREATE OR REPLACE PROPERTY `semanticrelation` string;
CREATE OR REPLACE PROPERTY `hassigningauthorityfor` string;
CREATE OR REPLACE PROPERTY `isvolatilityof` string;
CREATE OR REPLACE PROPERTY `hassubunit` string;
CREATE OR REPLACE PROPERTY `hasaffiliate` string;
CREATE OR REPLACE PROPERTY `haslegalform` string;
CREATE OR REPLACE PROPERTY `hasrelatedpartyinrole` string;
CREATE OR REPLACE PROPERTY `isplayedby` string;
CREATE OR REPLACE PROPERTY `hasprincipalexecutiveofficeaddress` string;
CREATE OR REPLACE PROPERTY `hasfloor` decimal;
CREATE OR REPLACE PROPERTY `maybesubordinatedto` string;
CREATE OR REPLACE PROPERTY `hasstreetname` string;
CREATE OR REPLACE PROPERTY `resource_id` string;
CREATE OR REPLACE PROPERTY `constrains` string;
CREATE OR REPLACE PROPERTY `hasexdividenddate` string;
CREATE OR REPLACE PROPERTY `specifiesconversioninto` string;
CREATE OR REPLACE PROPERTY `hasissuereference` string;
CREATE OR REPLACE PROPERTY `hasredemptionpremium` string;
CREATE OR REPLACE PROPERTY `hasrecorddate` string;
CREATE OR REPLACE PROPERTY `confersownershipof` string;
CREATE OR REPLACE PROPERTY `hasrole` string;
CREATE OR REPLACE PROPERTY `hasequity` string;
CREATE OR REPLACE PROPERTY `hasundergoer` string;
CREATE OR REPLACE PROPERTY `isincontrolofthing` string;
CREATE OR REPLACE PROPERTY `isdomiciledin` string;
CREATE OR REPLACE PROPERTY `hasaddressline1` string;
CREATE OR REPLACE PROPERTY `hasfundingsource` string;
CREATE OR REPLACE PROPERTY `isinforcein` string;
CREATE OR REPLACE PROPERTY `owns` string;
CREATE OR REPLACE PROPERTY `hasoriginalnotionalvalue` string;
CREATE OR REPLACE PROPERTY `hasaddressline3` string;
CREATE OR REPLACE PROPERTY `hasoriginalissuediscountamount` string;
CREATE OR REPLACE PROPERTY `hasaddressline2` string;
CREATE OR REPLACE PROPERTY `hasceiling` decimal;
CREATE OR REPLACE PROPERTY `hasprincipalparty` string;
CREATE OR REPLACE PROPERTY `hasdurationvalue` string;
CREATE OR REPLACE PROPERTY `isamortizationof` string;
CREATE OR REPLACE PROPERTY `iscontrollingpartyinrole` string;
CREATE OR REPLACE PROPERTY `haspricingsource` string;
CREATE OR REPLACE PROPERTY `hascontrollinginterestparty` string;
CREATE OR REPLACE PROPERTY `haspenultimatecouponpaymentdate` string;
CREATE OR REPLACE PROPERTY `iswhollyownedby` string;
CREATE OR REPLACE PROPERTY `hasdelegatedcontrolof` string;
CREATE OR REPLACE PROPERTY `isprincipalof` string;
CREATE OR REPLACE PROPERTY `lists` string;
CREATE OR REPLACE PROPERTY `publishes` string;
CREATE OR REPLACE PROPERTY `hasdividend` string;
CREATE OR REPLACE PROPERTY `buysfrom` string;
CREATE OR REPLACE PROPERTY `ownsandcontrols` string;
CREATE OR REPLACE PROPERTY `hasputdate` string;
CREATE OR REPLACE PROPERTY `haspersonname` string;
CREATE OR REPLACE PROPERTY `hassharesissued` integer;
CREATE OR REPLACE PROPERTY `hasthirdparty` string;
CREATE OR REPLACE PROPERTY `isofferingof` string;
CREATE OR REPLACE PROPERTY `hassecondaryaccountholder` string;
CREATE OR REPLACE PROPERTY `hasdesignation` string;
CREATE OR REPLACE PROPERTY `hastag` string;
CREATE OR REPLACE PROPERTY `specifiesconversiondate` string;
CREATE OR REPLACE PROPERTY `hasupfrontfee` string;
CREATE OR REPLACE PROPERTY `hasstructureorcomplexname` string;
CREATE OR REPLACE PROPERTY `isconstrainedby` string;
CREATE OR REPLACE PROPERTY `hasauthorizingparty` string;
CREATE OR REPLACE PROPERTY `hasfirstpremiumcallprice` string;
CREATE OR REPLACE PROPERTY `issubunitof` string;
CREATE OR REPLACE PROPERTY `hasstub` string;
CREATE OR REPLACE PROPERTY `hasmajoritycontrollingparty` string;
CREATE OR REPLACE PROPERTY `isjurisdictionof` string;
CREATE OR REPLACE PROPERTY `iscontrolledthinginrole` string;
CREATE OR REPLACE PROPERTY `isorganizedin` string;
CREATE OR REPLACE PROPERTY `isindependent` boolean;
CREATE OR REPLACE PROPERTY `fulfillsobligation` string;
CREATE OR REPLACE PROPERTY `hasnotificationprovision` string;
CREATE OR REPLACE PROPERTY `isbasedoninvestmentequity` string;
CREATE OR REPLACE PROPERTY `hastopconcept` string;
CREATE OR REPLACE PROPERTY `hasremarks` string;
CREATE OR REPLACE PROPERTY `hasactor` string;
CREATE OR REPLACE PROPERTY `isnegotiable` boolean;
CREATE OR REPLACE PROPERTY `isprorated` boolean;
CREATE OR REPLACE PROPERTY `hascallratebasis` string;
CREATE OR REPLACE PROPERTY `prop_del` string;
CREATE OR REPLACE PROPERTY `sells` string;
CREATE OR REPLACE PROPERTY `hasbestmeasure` decimal;
CREATE OR REPLACE PROPERTY `hasowningentity` string;
CREATE OR REPLACE PROPERTY `hasexercisetype` string;
CREATE OR REPLACE PROPERTY `hasfamilyname` string;
CREATE OR REPLACE PROPERTY `hassecondaryfederalregulator` string;
CREATE OR REPLACE PROPERTY `rates` string;
CREATE OR REPLACE PROPERTY `nominates` string;
CREATE OR REPLACE PROPERTY `haspercentagecontrol` decimal;
CREATE OR REPLACE PROPERTY `isunderwrittenby` string;
CREATE OR REPLACE PROPERTY `hasmeasurewithinscale` decimal;
CREATE OR REPLACE PROPERTY `hasexpression` string;
CREATE OR REPLACE PROPERTY `submits` string;
CREATE OR REPLACE PROPERTY `iscalculatedviamethodology` string;
CREATE OR REPLACE PROPERTY `hasratingscore` string;
CREATE OR REPLACE PROPERTY `hasdatespecification` string;
CREATE OR REPLACE PROPERTY `excludesenergyandfood` boolean;
CREATE OR REPLACE PROPERTY `hasattentionline` string;
CREATE OR REPLACE PROPERTY `isowningpartyinrole` string;
CREATE OR REPLACE PROPERTY `underwrites` string;
CREATE OR REPLACE PROPERTY `isgeneralpartnerof` string;
CREATE OR REPLACE PROPERTY `hasrateofreturn` string;
CREATE OR REPLACE PROPERTY `haslasttradingdatetime` string;
CREATE OR REPLACE CONCEPT `transliteration` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `transcription` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `timeinterval` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `timeinstant` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `timedirection` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `thinginrole` (`resource_id` string, `isplayedby` string, `hasrole` string, CONSTRAINT `hasrole` FOREIGN KEY (`hasrole`) REFERENCES `role` (`resource_id`) INVERSEOF `~hasrole` , CONSTRAINT `isplayedby` FOREIGN KEY (`isplayedby`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isplayedby` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `strategy` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `statisticalprogram` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `situation` (`hasundergoer` string, `resource_id` string, `hasactor` string, CONSTRAINT `hasactor` FOREIGN KEY (`hasactor`) REFERENCES `actor` (`resource_id`) INVERSEOF `~hasactor` , CONSTRAINT `hasundergoer` FOREIGN KEY (`hasundergoer`) REFERENCES `undergoer` (`resource_id`) INVERSEOF `~hasundergoer` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `service` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `role` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `referent` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `reference` (`resource_id` string, `hasoperand` string, `hasexpression` string, CONSTRAINT `hasexpression` FOREIGN KEY (`hasexpression`) REFERENCES `expression` (`resource_id`) INVERSEOF `~hasexpression` , CONSTRAINT `hasoperand` FOREIGN KEY (`hasoperand`) REFERENCES `referent` (`resource_id`) INVERSEOF `~hasoperand` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `quantityvalue` (`isvalueof` string, `resource_id` string, CONSTRAINT `isvalueof` FOREIGN KEY (`isvalueof`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isvalueof` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `qa_26_9` (`prop2_del` string, `prop3_del` integer, `prop_del` string, PRIMARY KEY (`prop_del`), LABEL (`prop2_del`)) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `product` (`resource_id` string, `issuppliedby` string, CONSTRAINT `issuppliedby` FOREIGN KEY (`issuppliedby`) REFERENCES `supplier` (`resource_id`) INVERSEOF `~issuppliedby` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `principal` (`resource_id` string, `isprincipalof` string, CONSTRAINT `isprincipalof` FOREIGN KEY (`isprincipalof`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isprincipalof` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `policy` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `ownershipandcontrol` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `opinion` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `offering` (`isofferingof` string, `resource_id` string, CONSTRAINT `isofferingof` FOREIGN KEY (`isofferingof`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isofferingof` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `occurrence` (`resource_id` string, `exemplifies` string, CONSTRAINT `exemplifies` FOREIGN KEY (`exemplifies`) REFERENCES `occurrencekind` (`resource_id`) INVERSEOF `~exemplifies` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `objective` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `location` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `licensedocument` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `legalconstruct` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `law` (`resource_id` string, `isinforcein` string, `constrains` string, CONSTRAINT `isinforcein` FOREIGN KEY (`isinforcein`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isinforcein` , CONSTRAINT `constrains` FOREIGN KEY (`constrains`) REFERENCES `autonomousagent` (`resource_id`) INVERSEOF `~constrains` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `languagevariation` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `language` (`resource_id` string, `hasearlierform` string, CONSTRAINT `hasearlierform` FOREIGN KEY (`hasearlierform`) REFERENCES `language` (`resource_id`) INVERSEOF `~hasearlierform` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `jurisdiction` (`resource_id` string, `isjurisdictionof` string, `hasreach` string, CONSTRAINT `hasreach` FOREIGN KEY (`hasreach`) REFERENCES `geographicregion` (`resource_id`) INVERSEOF `~hasreach` , CONSTRAINT `isjurisdictionof` FOREIGN KEY (`isjurisdictionof`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isjurisdictionof` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `income` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `good` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `goal` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `exposure` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `equity` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `document` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `currency` (`resource_id` string, `istenderin` string, CONSTRAINT `istenderin` FOREIGN KEY (`istenderin`) REFERENCES `jurisdiction` (`resource_id`) INVERSEOF `~istenderin` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `convention` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `controllingcapacity` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `contractualelement` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `constitution` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `conceptscheme` (`resource_id` string, `hastopconcept` string, CONSTRAINT `hastopconcept` FOREIGN KEY (`hastopconcept`) REFERENCES `concept` (`resource_id`) INVERSEOF `~hastopconcept` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `concept` (`resource_id` string, `semanticrelation` string, `topconceptof` string, CONSTRAINT `topconceptof` FOREIGN KEY (`topconceptof`) REFERENCES `conceptscheme` (`resource_id`) INVERSEOF `~topconceptof` , CONSTRAINT `semanticrelation` FOREIGN KEY (`semanticrelation`) REFERENCES `concept` (`resource_id`) INVERSEOF `~semanticrelation` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `commitment` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `collectionconstituent` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `collection` (`hasconstituent` string, `resource_id` string, `member` string, CONSTRAINT `member` FOREIGN KEY (`member`) REFERENCES `thing` (`resource_id`) INVERSEOF `~member` , CONSTRAINT `hasconstituent` FOREIGN KEY (`hasconstituent`) REFERENCES `thing` (`resource_id`) INVERSEOF `~hasconstituent` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `codeelement` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `capital` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `capability` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `autonomousagent` (`hascapacity` string, `isconstrainedby` string, `resource_id` string, `hasdesignation` string, CONSTRAINT `hascapacity` FOREIGN KEY (`hascapacity`) REFERENCES `legalcapacity` (`resource_id`) INVERSEOF `~hascapacity` , CONSTRAINT `isconstrainedby` FOREIGN KEY (`isconstrainedby`) REFERENCES `law` (`resource_id`) INVERSEOF `~isconstrainedby` , CONSTRAINT `hasdesignation` FOREIGN KEY (`hasdesignation`) REFERENCES `thing` (`resource_id`) INVERSEOF `~hasdesignation` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `aspect` (`resource_id` string, `characterizes` string, CONSTRAINT `characterizes` FOREIGN KEY (`characterizes`) REFERENCES `thing` (`resource_id`) INVERSEOF `~characterizes` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `arrangement` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `agreement` (`resource_id` string, `hasnonbindingterms` string, `hascontractualelement` string, CONSTRAINT `hasnonbindingterms` FOREIGN KEY (`hasnonbindingterms`) REFERENCES `nonbindingterms` (`resource_id`) INVERSEOF `~hasnonbindingterms` , CONSTRAINT `hascontractualelement` FOREIGN KEY (`hascontractualelement`) REFERENCES `contractualelement` (`resource_id`) INVERSEOF `~hascontractualelement` ) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `account` (`resource_id` string) INHERITS (`thing`);
CREATE OR REPLACE CONCEPT `recurrenceinterval`  INHERITS (`timeinterval`);
CREATE OR REPLACE CONCEPT `duration` (`hasdurationvalue` string) INHERITS (`timeinterval`);
CREATE OR REPLACE CONCEPT `dateperiod`  INHERITS (`timeinterval`);
CREATE OR REPLACE CONCEPT `calendarperiod`  INHERITS (`timeinterval`);
CREATE OR REPLACE CONCEPT `notionalstepperiodlength`  INHERITS (`recurrenceinterval`);
CREATE OR REPLACE CONCEPT `explicitrecurrenceinterval`  INHERITS (`recurrenceinterval`);
CREATE OR REPLACE CONCEPT `calendarspecifiedinterval`  INHERITS (`recurrenceinterval`);
CREATE OR REPLACE CONCEPT `businessrecurrenceinterval`  INHERITS (`recurrenceinterval`);
CREATE OR REPLACE CONCEPT `endofmonth`  INHERITS (`businessrecurrenceinterval`);
CREATE OR REPLACE CONCEPT `dayofweek`  INHERITS (`businessrecurrenceinterval`);
CREATE OR REPLACE CONCEPT `dayofmonth`  INHERITS (`businessrecurrenceinterval`);
CREATE OR REPLACE CONCEPT `explicitduration`  INHERITS (`duration`);
CREATE OR REPLACE CONCEPT `calculationperiodlength`  INHERITS (`explicitduration`);
CREATE OR REPLACE CONCEPT `putwindow`  INHERITS (`dateperiod`);
CREATE OR REPLACE CONCEPT `explicitdateperiod`  INHERITS (`dateperiod`);
CREATE OR REPLACE CONCEPT `callwindow`  INHERITS (`dateperiod`);
CREATE OR REPLACE CONCEPT `calculationperiod`  INHERITS (`dateperiod`);
CREATE OR REPLACE CONCEPT `timeofday`  INHERITS (`timeinstant`);
CREATE OR REPLACE CONCEPT `datetimestamp`  INHERITS (`timeinstant`);
CREATE OR REPLACE CONCEPT `datetime`  INHERITS (`timeinstant`);
CREATE OR REPLACE CONCEPT `date`  INHERITS (`timeinstant`);
CREATE OR REPLACE CONCEPT `rateresettimeofday`  INHERITS (`timeofday`);
CREATE OR REPLACE CONCEPT `periodicscheduledeventdate`  INHERITS (`date`);
CREATE OR REPLACE CONCEPT `explicitdate`  INHERITS (`date`);
CREATE OR REPLACE CONCEPT `calculateddate`  INHERITS (`date`);
CREATE OR REPLACE CONCEPT `transactiondate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `postingdate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `paymentduedate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `opendate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `nonrollingdate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `lastregularcoupondate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `firstregularcoupondate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `closedate`  INHERITS (`explicitdate`);
CREATE OR REPLACE CONCEPT `ustreasurybilldate`  INHERITS (`calculateddate`);
CREATE OR REPLACE CONCEPT `specifieddate` (`hasdatespecification` string) INHERITS (`calculateddate`);
CREATE OR REPLACE CONCEPT `ruledetermineddate`  INHERITS (`calculateddate`);
CREATE OR REPLACE CONCEPT `relativedate`  INHERITS (`calculateddate`);
CREATE OR REPLACE CONCEPT `occurrencebaseddate` (`istriggeredby` string, CONSTRAINT `istriggeredby` FOREIGN KEY (`istriggeredby`) REFERENCES `occurrencekind` (`resource_id`) INVERSEOF `~istriggeredby` ) INHERITS (`calculateddate`);
CREATE OR REPLACE CONCEPT `floatingratenotedate`  INHERITS (`calculateddate`);
CREATE OR REPLACE CONCEPT `datereturnedbytradingdaterule`  INHERITS (`ruledetermineddate`);
CREATE OR REPLACE CONCEPT `datereturnedbysettlementdaterule`  INHERITS (`ruledetermineddate`);
CREATE OR REPLACE CONCEPT `swapstreaminterestsettingrelativedate`  INHERITS (`relativedate`);
CREATE OR REPLACE CONCEPT `swapstreamcalculationrelativedate`  INHERITS (`relativedate`);
CREATE OR REPLACE CONCEPT `underlier`  INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `undergoer` (`undergoes` string, CONSTRAINT `undergoes` FOREIGN KEY (`undergoes`) REFERENCES `situation` (`resource_id`) INVERSEOF `~undergoes` ) INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `site`  INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `functionalentity`  INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `facility`  INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `amortization` (`isamortizationof` string, CONSTRAINT `isamortizationof` FOREIGN KEY (`isamortizationof`) REFERENCES `thing` (`resource_id`) INVERSEOF `~isamortizationof` ) INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `agentinrole`  INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `accrual`  INHERITS (`thinginrole`);
CREATE OR REPLACE CONCEPT `nonphysicalunderlier`  INHERITS (`underlier`);
CREATE OR REPLACE CONCEPT `ratebasedobservable`  INHERITS (`observablevalue`, `nonphysicalunderlier`);
CREATE OR REPLACE CONCEPT `interestrateobservable`  INHERITS (`ratebasedobservable`);
CREATE OR REPLACE CONCEPT `economicrateobservable`  INHERITS (`ratebasedobservable`);
CREATE OR REPLACE CONCEPT `controlledthing` (`iscontrolledthinginrole` string, CONSTRAINT `iscontrolledthinginrole` FOREIGN KEY (`iscontrolledthinginrole`) REFERENCES `control` (`resource_id`) INVERSEOF `~iscontrolledthinginrole` ) INHERITS (`undergoer`);
CREATE OR REPLACE CONCEPT `asset` (`isownedthinginrole` string, `isownedby` string, CONSTRAINT `isownedthinginrole` FOREIGN KEY (`isownedthinginrole`) REFERENCES `ownership` (`resource_id`) INVERSEOF `~isownedthinginrole` , CONSTRAINT `isownedby` FOREIGN KEY (`isownedby`) REFERENCES `owner` (`resource_id`) INVERSEOF `~isownedby` ) INHERITS (`undergoer`);
CREATE OR REPLACE CONCEPT `controlledparty` (`hascorporateofficer` string, `hasdirector` string, CONSTRAINT `hascorporateofficer` FOREIGN KEY (`hascorporateofficer`) REFERENCES `corporateofficer` (`resource_id`) INVERSEOF `~hascorporateofficer` , CONSTRAINT `hasdirector` FOREIGN KEY (`hasdirector`) REFERENCES `boardmember` (`resource_id`) INVERSEOF `~hasdirector` ) INHERITS (`partyinrole`, `controlledthing`);
CREATE OR REPLACE CONCEPT `cont