CREATE OR REPLACE PROPERTY `end_date` date;
CREATE OR REPLACE PROPERTY `notes` string;
CREATE OR REPLACE PROPERTY `minor` string;
CREATE OR REPLACE PROPERTY `occupancy` integer;
CREATE OR REPLACE PROPERTY `year` integer;
CREATE OR REPLACE PROPERTY `advisement_date` date;
CREATE OR REPLACE PROPERTY `lead_faculty_id` integer;
CREATE OR REPLACE PROPERTY `project_name` string;
CREATE OR REPLACE PROPERTY `title` string;
CREATE OR REPLACE PROPERTY `building` string;
CREATE OR REPLACE PROPERTY `capacity` integer;
CREATE OR REPLACE PROPERTY `enrollment_id` integer;
CREATE OR REPLACE PROPERTY `major` string;
CREATE OR REPLACE PROPERTY `credits` integer;
CREATE OR REPLACE PROPERTY `project_id` integer;
CREATE OR REPLACE PROPERTY `alumni_id` integer;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `email` string;
CREATE OR REPLACE PROPERTY `budget` decimal;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `graduation_date` date;
CREATE OR REPLACE PROPERTY `course_id` integer;
CREATE OR REPLACE PROPERTY `funding` decimal;
CREATE OR REPLACE PROPERTY `course_name` string;
CREATE OR REPLACE PROPERTY `department_id` integer;
CREATE OR REPLACE PROPERTY `level` string;
CREATE OR REPLACE PROPERTY `graduation_year` integer;
CREATE OR REPLACE PROPERTY `department_name` string;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `student_id` integer;
CREATE OR REPLACE PROPERTY `hire_date` date;
CREATE OR REPLACE PROPERTY `advisor_id` integer;
CREATE OR REPLACE PROPERTY `faculty_id` integer;
CREATE OR REPLACE PROPERTY `current_employer` string;
CREATE OR REPLACE PROPERTY `grade` string;
CREATE OR REPLACE PROPERTY `advisement_id` integer;
CREATE OR REPLACE PROPERTY `location` string;
CREATE OR REPLACE PROPERTY `phone_number` string;
CREATE OR REPLACE PROPERTY `semester` string;
CREATE OR REPLACE PROPERTY `position` string;
CREATE OR REPLACE PROPERTY `enrollment_date` date;
CREATE OR REPLACE PROPERTY `housing_id` integer;
CREATE OR REPLACE CONCEPT `student` (`minor` string, `student_id` integer, `phone_number` string, `enrollment_date` date, `graduation_date` date, `last_name` string, `email` string, `major` string, `first_name` string, PRIMARY KEY (`student_id`), LABEL (`first_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-tie');
CREATE OR REPLACE CONCEPT `research_project` (`end_date` date, `lead_faculty_id` integer, `project_name` string, `funding` decimal, `start_date` date, `project_id` integer, PRIMARY KEY (`project_id`), LABEL (`project_name`), CONSTRAINT `project_lead_faculty` FOREIGN KEY (`lead_faculty_id`) REFERENCES `faculty` (`faculty_id`) INVERSEOF `~project_lead_faculty` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-microscope');
CREATE OR REPLACE CONCEPT `housing` (`housing_id` integer, `capacity` integer, `occupancy` integer, `location` string, PRIMARY KEY (`housing_id`), LABEL (`location`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bed');
CREATE OR REPLACE CONCEPT `faculty` (`phone_number` string, `department_id` integer, `last_name` string, `title` string, `email` string, `faculty_id` integer, `hire_date` date, `first_name` string, PRIMARY KEY (`faculty_id`), LABEL (`first_name`), CONSTRAINT `faculty_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~faculty_department` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-chalkboard-teacher');
CREATE OR REPLACE CONCEPT `enrollment` (`year` integer, `student_id` integer, `semester` string, `course_id` integer, `enrollment_id` integer, `grade` string, PRIMARY KEY (`enrollment_id`), LABEL (`enrollment_id`), CONSTRAINT `enrollment_student` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) INVERSEOF `~enrollment_student` , CONSTRAINT `enrollment_course` FOREIGN KEY (`course_id`) REFERENCES `course` (`course_id`) INVERSEOF `~enrollment_course` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-list-check');
CREATE OR REPLACE CONCEPT `department` (`building` string, `department_id` integer, `budget` decimal, `department_name` string, PRIMARY KEY (`department_id`), LABEL (`department_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-building-un');
CREATE OR REPLACE CONCEPT `course` (`credits` integer, `department_id` integer, `course_id` integer, `course_name` string, `level` string, PRIMARY KEY (`course_id`), LABEL (`course_name`), CONSTRAINT `course_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~course_department` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-book-bookmark');
CREATE OR REPLACE CONCEPT `alumni` (`student_id` integer, `current_employer` string, `graduation_year` integer, `alumni_id` integer, `position` string, PRIMARY KEY (`alumni_id`), LABEL (`alumni_id`), CONSTRAINT `alumni_student` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) INVERSEOF `~alumni_student` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-graduation-cap');
CREATE OR REPLACE CONCEPT `advisement` (`student_id` integer, `notes` string, `advisement_date` date, `advisement_id` integer, `advisor_id` integer, PRIMARY KEY (`advisement_id`), LABEL (`advisement_date`), CONSTRAINT `advisement_advisor` FOREIGN KEY (`advisor_id`) REFERENCES `faculty` (`faculty_id`) INVERSEOF `~advisement_advisor` , CONSTRAINT `advisement_student` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) INVERSEOF `~advisement_student` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-compass');