CREATE OR REPLACE PROPERTY `asset_id` integer;
CREATE OR REPLACE PROPERTY `contact_info` string;
CREATE OR REPLACE PROPERTY `repair_cost` decimal;
CREATE OR REPLACE PROPERTY `scheduled_date` date;
CREATE OR REPLACE PROPERTY `inventory_name` string;
CREATE OR REPLACE PROPERTY `location_id` integer;
CREATE OR REPLACE PROPERTY `asset_name` string;
CREATE OR REPLACE PROPERTY `depreciation_rate` decimal;
CREATE OR REPLACE PROPERTY `asset_type` string;
CREATE OR REPLACE PROPERTY `part_id` integer;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `maintenance_details` string;
CREATE OR REPLACE PROPERTY `reported_date` date;
CREATE OR REPLACE PROPERTY `issue_description` string;
CREATE OR REPLACE PROPERTY `address` string;
CREATE OR REPLACE PROPERTY `cost` decimal;
CREATE OR REPLACE PROPERTY `reorder_level` integer;
CREATE OR REPLACE PROPERTY `inventory_id` integer;
CREATE OR REPLACE PROPERTY `stock_level` integer;
CREATE OR REPLACE PROPERTY `maintenance_type` string;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `technician_id` integer;
CREATE OR REPLACE PROPERTY `vendor_name` string;
CREATE OR REPLACE PROPERTY `resolution_status` string;
CREATE OR REPLACE PROPERTY `serial_number` string;
CREATE OR REPLACE PROPERTY `warranty_expiry` date;
CREATE OR REPLACE PROPERTY `contact_number` string;
CREATE OR REPLACE PROPERTY `condition` string;
CREATE OR REPLACE PROPERTY `location_name` string;
CREATE OR REPLACE PROPERTY `vendor_id` integer;
CREATE OR REPLACE PROPERTY `part_number` string;
CREATE OR REPLACE PROPERTY `specialization` string;
CREATE OR REPLACE PROPERTY `purchase_date` date;
CREATE OR REPLACE PROPERTY `order_id` integer;
CREATE OR REPLACE PROPERTY `schedule_id` integer;
CREATE OR REPLACE PROPERTY `part_name` string;
CREATE OR REPLACE PROPERTY `maintenance_cost` decimal;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE CONCEPT `work_order` (`asset_id` integer, `issue_description` string, `order_id` integer, `repair_cost` decimal, `reported_date` date, `resolution_status` string, PRIMARY KEY (`order_id`), LABEL (`order_id`), CONSTRAINT `work_order_for_asset` FOREIGN KEY (`asset_id`) REFERENCES `asset` (`asset_id`) INVERSEOF `asset_work_orders` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-clipboard-check');
CREATE OR REPLACE CONCEPT `vendor` (`vendor_id` integer, `vendor_name` string, `contact_info` string, PRIMARY KEY (`vendor_id`), LABEL (`vendor_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-store');
CREATE OR REPLACE CONCEPT `technician` (`contact_number` string, `last_name` string, `technician_id` integer, `specialization` string, `first_name` string, PRIMARY KEY (`technician_id`), LABEL (`first_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-gear');
CREATE OR REPLACE CONCEPT `part` (`vendor_id` integer, `reorder_level` integer, `part_name` string, `stock_level` integer, `part_number` string, `part_id` integer, PRIMARY KEY (`part_id`), LABEL (`part_name`), CONSTRAINT `part_stock` FOREIGN KEY (`stock_level`) REFERENCES `inventory` (`inventory_id`) INVERSEOF `inventory_parts` , CONSTRAINT `part_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendor` (`vendor_id`) INVERSEOF `vendor_parts` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-gear');
CREATE OR REPLACE CONCEPT `maintenance_schedule` (`asset_id` integer, `schedule_id` integer, `maintenance_details` string, `status` string, `technician_id` integer, `maintenance_cost` decimal, `maintenance_type` string, `scheduled_date` date, PRIMARY KEY (`schedule_id`), LABEL (`maintenance_type`), CONSTRAINT `maintenance_by_technician` FOREIGN KEY (`technician_id`) REFERENCES `technician` (`technician_id`) INVERSEOF `technician_maintenance` , CONSTRAINT `maintenance_for_asset` FOREIGN KEY (`asset_id`) REFERENCES `asset` (`asset_id`) INVERSEOF `asset_maintenance` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tools');
CREATE OR REPLACE CONCEPT `location` (`address` string, `location_name` string, `location_id` integer, PRIMARY KEY (`location_id`), LABEL (`location_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-location-dot');
CREATE OR REPLACE CONCEPT `inventory` (`inventory_name` string, `inventory_id` integer, `location_id` integer, PRIMARY KEY (`inventory_id`), LABEL (`inventory_name`), CONSTRAINT `inventory_location` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`) INVERSEOF `location_inventory` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-cubes');
CREATE OR REPLACE CONCEPT `asset` (`vendor_id` integer, `asset_id` integer, `asset_name` string, `serial_number` string, `cost` decimal, `condition` string, `purchase_date` date, `asset_type` string, `depreciation_rate` decimal, `location_id` integer, `warranty_expiry` date, PRIMARY KEY (`asset_id`), LABEL (`asset_name`), CONSTRAINT `asset_location` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`) INVERSEOF `location_assets` , CONSTRAINT `asset_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendor` (`vendor_id`) INVERSEOF `vendor_assets` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-briefcase');