CREATE OR REPLACE PROPERTY `birthday` timestamp;
CREATE OR REPLACE PROPERTY `browser_used` string;
CREATE OR REPLACE PROPERTY `gender` string;
CREATE OR REPLACE PROPERTY `language` MULTIVALUE string;
CREATE OR REPLACE PROPERTY `title` string;
CREATE OR REPLACE PROPERTY `content` string;
CREATE OR REPLACE PROPERTY `forum_id` bigint;
CREATE OR REPLACE PROPERTY `location_id` integer;
CREATE OR REPLACE PROPERTY `sub_class_of_tag_class_id` bigint;
CREATE OR REPLACE PROPERTY `organization_place_id` bigint;
CREATE OR REPLACE PROPERTY `tc_tagclassid` bigint;
CREATE OR REPLACE PROPERTY `moderator_id` bigint;
CREATE OR REPLACE PROPERTY `place_type` string;
CREATE OR REPLACE PROPERTY `ps_language` string;
CREATE OR REPLACE PROPERTY `tag_class_id` bigint;
CREATE OR REPLACE PROPERTY `tag_id` bigint;
CREATE OR REPLACE PROPERTY `location_ip` string;
CREATE OR REPLACE PROPERTY `tag_class_name` string;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `email` MULTIVALUE string;
CREATE OR REPLACE PROPERTY `place_id` bigint;
CREATE OR REPLACE PROPERTY `person_id` bigint;
CREATE OR REPLACE PROPERTY `place_url` string;
CREATE OR REPLACE PROPERTY `organization_url` string;
CREATE OR REPLACE PROPERTY `place_name` string;
CREATE OR REPLACE PROPERTY `ps_image_file` string;
CREATE OR REPLACE PROPERTY `c_replyof` integer;
CREATE OR REPLACE PROPERTY `tag_name` string;
CREATE OR REPLACE PROPERTY `tag_class_url` string;
CREATE OR REPLACE PROPERTY `length` integer;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `message_id` integer;
CREATE OR REPLACE PROPERTY `creation_date` timestamp;
CREATE OR REPLACE PROPERTY `organization_name` string;
CREATE OR REPLACE PROPERTY `organization_id` bigint;
CREATE OR REPLACE PROPERTY `creator_id` bigint;
CREATE OR REPLACE PROPERTY `container_place_id` bigint;
CREATE OR REPLACE PROPERTY `organization_type` string;
CREATE OR REPLACE PROPERTY `tag_url` string;
CREATE OR REPLACE CONCEPT `tag_class` (`tag_class_name` string, `tag_class_url` string, `tc_tagclassid` bigint, `sub_class_of_tag_class_id` bigint, `tag_class_id` bigint, PRIMARY KEY (`tag_class_id`), LABEL (`tag_class_name`), CONSTRAINT `has_subclass` FOREIGN KEY (`tag_class_id`) REFERENCES `tag_class` (`sub_class_of_tag_class_id`) INVERSEOF `subclass_of`  TRANSITIVE(4)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tags');
CREATE OR REPLACE CONCEPT `tag` (`message_id` integer, `tag_id` bigint, `person_id` bigint, `tag_name` string, `tag_url` string, `tag_class_id` bigint, PRIMARY KEY (`tag_id`), LABEL (`tag_name`), CONSTRAINT `interesting` MULTIREFERENCE `person` INVERSEOF `has_interest` , CONSTRAINT `has_type` FOREIGN KEY (`tag_class_id`) REFERENCES `tag_class` (`tag_class_id`) INVERSEOF `has_tag` , CONSTRAINT `in_message` MULTIREFERENCE `message` INVERSEOF `message_tag` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tag');
CREATE OR REPLACE CONCEPT `place` (`place_url` string, `container_place_id` bigint, `place_type` string, `place_id` bigint, `place_name` string, PRIMARY KEY (`place_id`), LABEL (`place_name`), CONSTRAINT `of_message` FOREIGN KEY (`place_id`) REFERENCES `message` (`location_id`) INVERSEOF `has_location` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-map-marker');
CREATE OR REPLACE CONCEPT `person` (`birthday` timestamp, `creation_date` timestamp, `gender` string, `browser_used` string, `place_id` bigint, `person_id` bigint, `last_name` string, `location_ip` string, `first_name` string, PRIMARY KEY (`person_id`), LABEL (`first_name`), CONSTRAINT `language` MULTIVALUE string, CONSTRAINT `knows` MULTIREFERENCE `person` INVERSEOF `known` , CONSTRAINT `live_in` FOREIGN KEY (`place_id`) REFERENCES `place` (`place_id`) INVERSEOF `of` , CONSTRAINT `email` MULTIVALUE string, CONSTRAINT `sent` FOREIGN KEY (`person_id`) REFERENCES `message` (`creator_id`) INVERSEOF `created_by` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-person');
CREATE OR REPLACE CONCEPT `organization` (`organization_place_id` bigint, `organization_id` bigint, `person_id` bigint, `organization_url` string, `organization_name` string, `organization_type` string, PRIMARY KEY (`organization_id`), LABEL (`organization_name`), CONSTRAINT `in_place` FOREIGN KEY (`organization_place_id`) REFERENCES `place` (`place_id`) INVERSEOF `of_organization` , CONSTRAINT `employs_the` MULTIREFERENCE `person` INVERSEOF `works_at` , CONSTRAINT `contains_the` MULTIREFERENCE `person` INVERSEOF `study_at` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-building-un');
CREATE OR REPLACE CONCEPT `message` (`creation_date` timestamp, `person_id` bigint, `forum_id` bigint, `c_replyof` integer, `creator_id` bigint, `location_ip` string, `browser_used` string, `message_id` integer, `ps_language` string, `content` string, `ps_image_file` string, `length` integer, `location_id` integer, PRIMARY KEY (`message_id`), LABEL (`content`), CONSTRAINT `reply_of` FOREIGN KEY (`c_replyof`) REFERENCES `message` (`message_id`) INVERSEOF `has_reply` , CONSTRAINT `liked_by` MULTIREFERENCE `person` INVERSEOF `like` , CONSTRAINT `message_in` FOREIGN KEY (`forum_id`) REFERENCES `forum` (`forum_id`) INVERSEOF `has_message` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-envelope');
CREATE OR REPLACE CONCEPT `forum` (`creation_date` timestamp, `moderator_id` bigint, `title` string, `forum_id` bigint, PRIMARY KEY (`forum_id`), LABEL (`title`), CONSTRAINT `moderated_by` FOREIGN KEY (`moderator_id`) REFERENCES `person` (`person_id`) INVERSEOF `moderator_of` , CONSTRAINT `has_member` MULTIREFERENCE `person` INVERSEOF `member_of` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-message');
CREATE OR REPLACE CONCEPT `tag_class_thing`  INHERITS (`tag_class`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (0);
CREATE OR REPLACE CONCEPT `tag_class_work`  INHERITS (`tag_class_thing`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (188);
CREATE OR REPLACE CONCEPT `tag_class_place`  INHERITS (`tag_class_thing`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (303);
CREATE OR REPLACE CONCEPT `tag_class_agent`  INHERITS (`tag_class_thing`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (239);
CREATE OR REPLACE CONCEPT `tag_class_musicalwork`  INHERITS (`tag_class_work`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (123);
CREATE OR REPLACE CONCEPT `tag_class_film`  INHERITS (`tag_class_work`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (145);
CREATE OR REPLACE CONCEPT `tag_class_song`  INHERITS (`tag_class_musicalwork`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (180);
CREATE OR REPLACE CONCEPT `tag_class_single`  INHERITS (`tag_class_musicalwork`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (342);
CREATE OR REPLACE CONCEPT `tag_class_album`  INHERITS (`tag_class_musicalwork`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (182);
CREATE OR REPLACE CONCEPT `tag_class_eurovisionsongcontestentry`  INHERITS (`tag_class_song`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (233);
CREATE OR REPLACE CONCEPT `tag_class_populatedplace`  INHERITS (`tag_class_place`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (318);
CREATE OR REPLACE CONCEPT `tag_class_country`  INHERITS (`tag_class_populatedplace`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (62);
CREATE OR REPLACE CONCEPT `tag_class_person`  INHERITS (`tag_class_agent`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (211);
CREATE OR REPLACE CONCEPT `tag_class_organisation`  INHERITS (`tag_class_agent`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (301);
CREATE OR REPLACE CONCEPT `tag_class_soccermanager`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (94);
CREATE OR REPLACE CONCEPT `tag_class_scientist`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (279);
CREATE OR REPLACE CONCEPT `tag_class_royalty`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (155);
CREATE OR REPLACE CONCEPT `tag_class_politician`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (95);
CREATE OR REPLACE CONCEPT `tag_class_philosopher`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (82);
CREATE OR REPLACE CONCEPT `tag_class_organisationmember`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (67);
CREATE OR REPLACE CONCEPT `tag_class_officeholder`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (349);
CREATE OR REPLACE CONCEPT `tag_class_monarch`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (98);
CREATE OR REPLACE CONCEPT `tag_class_model`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (173);
CREATE OR REPLACE CONCEPT `tag_class_militaryperson`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (3);
CREATE OR REPLACE CONCEPT `tag_class_judge`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (226);
CREATE OR REPLACE CONCEPT `tag_class_fictionalcharacter`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (295);
CREATE OR REPLACE CONCEPT `tag_class_criminal`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (287);
CREATE OR REPLACE CONCEPT `tag_class_collegecoach`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (77);
CREATE OR REPLACE CONCEPT `tag_class_cleric`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (109);
CREATE OR REPLACE CONCEPT `tag_class_athlete`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (149);
CREATE OR REPLACE CONCEPT `tag_class_astronaut`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (339);
CREATE OR REPLACE CONCEPT `tag_class_artist`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (250);
CREATE OR REPLACE CONCEPT `tag_class_architect`  INHERITS (`tag_class_person`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (212);
CREATE OR REPLACE CONCEPT `tag_class_britishroyalty`  INHERITS (`tag_class_royalty`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (336);
CREATE OR REPLACE CONCEPT `tag_class_senator`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (219);
CREATE OR REPLACE CONCEPT `tag_class_primeminister`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (148);
CREATE OR REPLACE CONCEPT `tag_class_president`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (57);
CREATE OR REPLACE CONCEPT `tag_class_memberofparliament`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (330);
CREATE OR REPLACE CONCEPT `tag_class_governor`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (347);
CREATE OR REPLACE CONCEPT `tag_class_congressman`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (167);
CREATE OR REPLACE CONCEPT `tag_class_chancellor`  INHERITS (`tag_class_politician`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (355);
CREATE OR REPLACE CONCEPT `tag_class_sportsteammember`  INHERITS (`tag_class_organisationmember`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (242);
CREATE OR REPLACE CONCEPT `tag_class_comicscharacter`  INHERITS (`tag_class_fictionalcharacter`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (302);
CREATE OR REPLACE CONCEPT `tag_class_saint`  INHERITS (`tag_class_cleric`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (193);
CREATE OR REPLACE CONCEPT `tag_class_christianbishop`  INHERITS (`tag_class_cleric`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (332);
CREATE OR REPLACE CONCEPT `tag_class_wrestler`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (43);
CREATE OR REPLACE CONCEPT `tag_class_tennisplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (59);
CREATE OR REPLACE CONCEPT `tag_class_soccerplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (74);
CREATE OR REPLACE CONCEPT `tag_class_snookerplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (112);
CREATE OR REPLACE CONCEPT `tag_class_nascardriver`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (141);
CREATE OR REPLACE CONCEPT `tag_class_martialartist`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (230);
CREATE OR REPLACE CONCEPT `tag_class_icehockeyplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (13);
CREATE OR REPLACE CONCEPT `tag_class_gridironfootballplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (47);
CREATE OR REPLACE CONCEPT `tag_class_golfplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (191);
CREATE OR REPLACE CONCEPT `tag_class_formulaoneracer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (37);
CREATE OR REPLACE CONCEPT `tag_class_cyclist`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (319);
CREATE OR REPLACE CONCEPT `tag_class_cricketer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (24);
CREATE OR REPLACE CONCEPT `tag_class_boxer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (72);
CREATE OR REPLACE CONCEPT `tag_class_basketballplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (354);
CREATE OR REPLACE CONCEPT `tag_class_baseballplayer`  INHERITS (`tag_class_athlete`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (310);
CREATE OR REPLACE CONCEPT `tag_class_snookerchamp`  INHERITS (`tag_class_snookerplayer`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (152);
CREATE OR REPLACE CONCEPT `tag_class_americanfootballplayer`  INHERITS (`tag_class_gridironfootballplayer`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (104);
CREATE OR REPLACE CONCEPT `tag_class_writer`  INHERITS (`tag_class_artist`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (88);
CREATE OR REPLACE CONCEPT `tag_class_musicalartist`  INHERITS (`tag_class_artist`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (115);
CREATE OR REPLACE CONCEPT `tag_class_comicscreator`  INHERITS (`tag_class_artist`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (97);
CREATE OR REPLACE CONCEPT `tag_class_comedian`  INHERITS (`tag_class_artist`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (96);
CREATE OR REPLACE CONCEPT `tag_class_actor`  INHERITS (`tag_class_artist`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (200, 46);
CREATE OR REPLACE CONCEPT `tag_class_adultactor`  INHERITS (`tag_class_actor`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (46);
CREATE OR REPLACE CONCEPT `tag_class_militaryunit`  INHERITS (`tag_class_organisation`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (243);
CREATE OR REPLACE CONCEPT `tag_class_company`  INHERITS (`tag_class_organisation`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (41);
CREATE OR REPLACE CONCEPT `tag_class_band`  INHERITS (`tag_class_organisation`) FROM timbr.`tag_class` WHERE `tc_tagclassid` IN (61);
CREATE OR REPLACE CONCEPT `country` (`container_place_id` bigint, CONSTRAINT `in_continent` FOREIGN KEY (`container_place_id`) REFERENCES `continent` (`place_id`) INVERSEOF `contains_a_country` ) INHERITS (`place`) FROM timbr.`place` WHERE `place_type` = 'country';
CREATE OR REPLACE CONCEPT `continent`  INHERITS (`place`) FROM timbr.`place` WHERE `place_type` = 'continent';
CREATE OR REPLACE CONCEPT `city` (`container_place_id` bigint, CONSTRAINT `in_country` FOREIGN KEY (`container_place_id`) REFERENCES `country` (`place_id`) INVERSEOF `contains_a_city` ) INHERITS (`place`) FROM timbr.`place` WHERE `place_type` = 'city';
CREATE OR REPLACE CONCEPT `university`  INHERITS (`organization`) FROM timbr.`organization` WHERE `organization_type` = 'university';
CREATE OR REPLACE CONCEPT `company`  INHERITS (`organization`) FROM timbr.`organization` WHERE `organization_type` = 'company';
CREATE OR REPLACE CONCEPT `post`  INHERITS (`message`) FROM timbr.`message` WHERE `c_replyof` IS NULL;
CREATE OR REPLACE CONCEPT `comment`  INHERITS (`message`) FROM timbr.`message` WHERE `c_replyof` IS NOT NULL;