CREATE OR REPLACE PROPERTY `date` date;
CREATE OR REPLACE PROPERTY `email_id` integer;
CREATE OR REPLACE PROPERTY `end_date` date;
CREATE OR REPLACE PROPERTY `file_url` string;
CREATE OR REPLACE PROPERTY `data` string;
CREATE OR REPLACE PROPERTY `list_id` integer;
CREATE OR REPLACE PROPERTY `purpose` string;
CREATE OR REPLACE PROPERTY `criteria` string;
CREATE OR REPLACE PROPERTY `response_date` timestamp;
CREATE OR REPLACE PROPERTY `response_id` integer;
CREATE OR REPLACE PROPERTY `subject` string;
CREATE OR REPLACE PROPERTY `channel` string;
CREATE OR REPLACE PROPERTY `rating` integer;
CREATE OR REPLACE PROPERTY `industry` string;
CREATE OR REPLACE PROPERTY `asset_id` integer;
CREATE OR REPLACE PROPERTY `source` string;
CREATE OR REPLACE PROPERTY `body` string;
CREATE OR REPLACE PROPERTY `contact_id` integer;
CREATE OR REPLACE PROPERTY `type` string;
CREATE OR REPLACE PROPERTY `activity_id` integer;
CREATE OR REPLACE PROPERTY `segment_id` integer;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `campaign_id` integer;
CREATE OR REPLACE PROPERTY `email` string;
CREATE OR REPLACE PROPERTY `lead_id` integer;
CREATE OR REPLACE PROPERTY `budget` decimal;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `address` string;
CREATE OR REPLACE PROPERTY `activity_date` date;
CREATE OR REPLACE PROPERTY `sent_date` timestamp;
CREATE OR REPLACE PROPERTY `analytics_id` integer;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `account_id` integer;
CREATE OR REPLACE PROPERTY `event_id` integer;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `location` string;
CREATE OR REPLACE PROPERTY `phone_number` string;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE CONCEPT `marketing_list` (`list_id` integer, `purpose` string, `name` string, PRIMARY KEY (`list_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-list-check');
CREATE OR REPLACE CONCEPT `marketing_activity` (`type` string, `activity_date` date, `activity_id` integer, `campaign_id` integer, PRIMARY KEY (`activity_id`), LABEL (`type`), CONSTRAINT `activity_for_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `campaign` (`campaign_id`) INVERSEOF `includes_activity` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-cog');
CREATE OR REPLACE CONCEPT `lead` (`rating` integer, `contact_id` integer, `lead_id` integer, `status` string, `source` string, PRIMARY KEY (`lead_id`), LABEL (`source`), CONSTRAINT `has_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`contact_id`) INVERSEOF `is_contact_for` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bullseye');
CREATE OR REPLACE CONCEPT `event` (`location` string, `name` string, `date` date, `event_id` integer, PRIMARY KEY (`event_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-calendar-days');
CREATE OR REPLACE CONCEPT `email` (`body` string, `subject` string, `email_id` integer, `status` string, `sent_date` timestamp, `campaign_id` integer, PRIMARY KEY (`email_id`), LABEL (`subject`), CONSTRAINT `is_part_of_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `campaign` (`campaign_id`) INVERSEOF `has_email` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-at');
CREATE OR REPLACE CONCEPT `digital_asset` (`asset_id` integer, `type` string, `file_url` string, `campaign_id` integer, PRIMARY KEY (`asset_id`), LABEL (`type`), CONSTRAINT `asset_used_in_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `campaign` (`campaign_id`) INVERSEOF `uses_asset` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-digital-tachograph');
CREATE OR REPLACE CONCEPT `customer_segment` (`criteria` string, `segment_id` integer, `name` string, PRIMARY KEY (`segment_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-pie-chart');
CREATE OR REPLACE CONCEPT `contact` (`phone_number` string, `contact_id` integer, `last_name` string, `email` string, `account_id` integer, `first_name` string, PRIMARY KEY (`contact_id`), LABEL (`first_name`), CONSTRAINT `belongs_to_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) INVERSEOF `has_contact` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-contact-book');
CREATE OR REPLACE CONCEPT `campaign_response` (`type` string, `contact_id` integer, `response_date` timestamp, `response_id` integer, `campaign_id` integer, PRIMARY KEY (`response_id`), LABEL (`type`), CONSTRAINT `response_from_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`contact_id`) INVERSEOF `has_response` , CONSTRAINT `response_to_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `campaign` (`campaign_id`) INVERSEOF `has_response` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-reply');
CREATE OR REPLACE CONCEPT `campaign` (`status` string, `end_date` date, `channel` string, `budget` decimal, `name` string, `start_date` date, `campaign_id` integer, PRIMARY KEY (`campaign_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bullhorn');
CREATE OR REPLACE CONCEPT `analytics` (`data` string, `analytics_id` integer, `campaign_id` integer, PRIMARY KEY (`analytics_id`), LABEL (`data`), CONSTRAINT `analytics_for_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `campaign` (`campaign_id`) INVERSEOF `has_analytics` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-chart-simple');
CREATE OR REPLACE CONCEPT `account` (`address` string, `industry` string, `phone_number` string, `account_id` integer, `name` string, PRIMARY KEY (`account_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user');