CREATE OR REPLACE PROPERTY `reason` string;
CREATE OR REPLACE PROPERTY `operational_status` string;
CREATE OR REPLACE PROPERTY `response_teams` string;
CREATE OR REPLACE PROPERTY `agent_id` integer;
CREATE OR REPLACE PROPERTY `resolved_date` date;
CREATE OR REPLACE PROPERTY `enrollment_start_date` date;
CREATE OR REPLACE PROPERTY `findings` string;
CREATE OR REPLACE PROPERTY `usage` decimal;
CREATE OR REPLACE PROPERTY `new_rate` decimal;
CREATE OR REPLACE PROPERTY `account_status` string;
CREATE OR REPLACE PROPERTY `asset_id` integer;
CREATE OR REPLACE PROPERTY `project_name` string;
CREATE OR REPLACE PROPERTY `scheduled_date` date;
CREATE OR REPLACE PROPERTY `recommendations` string;
CREATE OR REPLACE PROPERTY `resolution` string;
CREATE OR REPLACE PROPERTY `compliance_level` string;
CREATE OR REPLACE PROPERTY `objective` string;
CREATE OR REPLACE PROPERTY `activation_conditions` string;
CREATE OR REPLACE PROPERTY `consumption_id` integer;
CREATE OR REPLACE PROPERTY `maintenance_id` integer;
CREATE OR REPLACE PROPERTY `project_id` integer;
CREATE OR REPLACE PROPERTY `resolution_id` integer;
CREATE OR REPLACE PROPERTY `funding_source` string;
CREATE OR REPLACE PROPERTY `initiative_id` integer;
CREATE OR REPLACE PROPERTY `effective_date` date;
CREATE OR REPLACE PROPERTY `technology_id` integer;
CREATE OR REPLACE PROPERTY `payment_date` date;
CREATE OR REPLACE PROPERTY `payment_method` string;
CREATE OR REPLACE PROPERTY `affected_area` string;
CREATE OR REPLACE PROPERTY `budget` decimal;
CREATE OR REPLACE PROPERTY `report_date` date;
CREATE OR REPLACE PROPERTY `old_rate` decimal;
CREATE OR REPLACE PROPERTY `last_updated` date;
CREATE OR REPLACE PROPERTY `bill_amount` decimal;
CREATE OR REPLACE PROPERTY `resolution_details` string;
CREATE OR REPLACE PROPERTY `issue` string;
CREATE OR REPLACE PROPERTY `maintenance_type` string;
CREATE OR REPLACE PROPERTY `satisfaction_rating` integer;
CREATE OR REPLACE PROPERTY `payment_amount` decimal;
CREATE OR REPLACE PROPERTY `meter_type` string;
CREATE OR REPLACE PROPERTY `read_date` date;
CREATE OR REPLACE PROPERTY `installation_date` date;
CREATE OR REPLACE PROPERTY `change_id` integer;
CREATE OR REPLACE PROPERTY `employee_id` integer;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `phone_number` string;
CREATE OR REPLACE PROPERTY `purchase_date` date;
CREATE OR REPLACE PROPERTY `compliance_id` integer;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE PROPERTY `benefits` string;
CREATE OR REPLACE PROPERTY `end_date` date;
CREATE OR REPLACE PROPERTY `service_start_date` date;
CREATE OR REPLACE PROPERTY `program_id` integer;
CREATE OR REPLACE PROPERTY `audit_date` date;
CREATE OR REPLACE PROPERTY `cause` string;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `title` string;
CREATE OR REPLACE PROPERTY `compliance_date` date;
CREATE OR REPLACE PROPERTY `audit_id` integer;
CREATE OR REPLACE PROPERTY `payment_id` integer;
CREATE OR REPLACE PROPERTY `asset_type` string;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `email` string;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `billing_cycle_id` integer;
CREATE OR REPLACE PROPERTY `outage_id` integer;
CREATE OR REPLACE PROPERTY `address` string;
CREATE OR REPLACE PROPERTY `service_end_date` date;
CREATE OR REPLACE PROPERTY `auditor` string;
CREATE OR REPLACE PROPERTY `expected_savings` decimal;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `interaction_id` integer;
CREATE OR REPLACE PROPERTY `account_id` integer;
CREATE OR REPLACE PROPERTY `regulation` string;
CREATE OR REPLACE PROPERTY `report_id` integer;
CREATE OR REPLACE PROPERTY `location` string;
CREATE OR REPLACE PROPERTY `customer_id` integer;
CREATE OR REPLACE PROPERTY `enrollment_end_date` date;
CREATE OR REPLACE PROPERTY `interaction_date` date;
CREATE OR REPLACE PROPERTY `meter_id` integer;
CREATE OR REPLACE PROPERTY `plan_id` integer;
CREATE OR REPLACE CONCEPT `smart_grid_technology` (`description` string, `operational_status` string, `technology_id` integer, `name` string, `installation_date` date, PRIMARY KEY (`technology_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tachograph-digital');
CREATE OR REPLACE CONCEPT `service_account` (`service_end_date` date, `customer_id` integer, `account_id` integer, `account_status` string, `service_start_date` date, PRIMARY KEY (`account_id`), LABEL (`account_id`), CONSTRAINT `account_belongs_to_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) INVERSEOF `~account_belongs_to_customer` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-file-contract');
CREATE OR REPLACE CONCEPT `renewable_energy_initiative` (`funding_source` string, `initiative_id` integer, `objective` string, `end_date` date, `title` string, `start_date` date, PRIMARY KEY (`initiative_id`), LABEL (`title`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tornado');
CREATE OR REPLACE CONCEPT `regulatory_compliance` (`compliance_id` integer, `compliance_date` date, `status` string, `regulation` string, PRIMARY KEY (`compliance_id`), LABEL (`regulation`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-check-square');
CREATE OR REPLACE CONCEPT `regulatory_audit` (`auditor` string, `compliance_level` string, `audit_id` integer, `audit_date` date, `findings` string, PRIMARY KEY (`audit_id`), LABEL (`findings`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-magnifying-glass-dollar');
CREATE OR REPLACE CONCEPT `rate_change` (`old_rate` decimal, `reason` string, `effective_date` date, `new_rate` decimal, `change_id` integer, PRIMARY KEY (`change_id`), LABEL (`reason`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-money-bill-trend-up');
CREATE OR REPLACE CONCEPT `payment` (`payment_amount` decimal, `payment_id` integer, `payment_method` string, `payment_date` date, `billing_cycle_id` integer, PRIMARY KEY (`payment_id`), LABEL (`payment_id`), CONSTRAINT `payment_for_billing` FOREIGN KEY (`billing_cycle_id`) REFERENCES `billing_cycle` (`billing_cycle_id`) INVERSEOF `~payment_for_billing` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-wallet');
CREATE OR REPLACE CONCEPT `outage` (`outage_id` integer, `end_date` date, `affected_area` string, `cause` string, `start_date` date, PRIMARY KEY (`outage_id`), LABEL (`outage_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-chain-broken');
CREATE OR REPLACE CONCEPT `meter` (`meter_id` integer, `status` string, `meter_type` string, `account_id` integer, `installation_date` date, PRIMARY KEY (`meter_id`), LABEL (`meter_id`), CONSTRAINT `meter_for_account` FOREIGN KEY (`account_id`) REFERENCES `service_account` (`account_id`) INVERSEOF `~meter_for_account` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tachometer-alt-average');
CREATE OR REPLACE CONCEPT `maintenance` (`asset_id` integer, `status` string, `maintenance_type` string, `scheduled_date` date, `maintenance_id` integer, PRIMARY KEY (`maintenance_id`), LABEL (`maintenance_type`), CONSTRAINT `maintenance_for_asset` FOREIGN KEY (`asset_id`) REFERENCES `asset` (`asset_id`) INVERSEOF `~maintenance_for_asset` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tools');
CREATE OR REPLACE CONCEPT `infrastructure_project` (`status` string, `end_date` date, `project_name` string, `budget` decimal, `start_date` date, `project_id` integer, PRIMARY KEY (`project_id`), LABEL (`project_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-person-digging');
CREATE OR REPLACE CONCEPT `environmental_impact_report` (`recommendations` string, `report_date` date, `report_id` integer, `findings` string, `project_id` integer, PRIMARY KEY (`report_id`), LABEL (`findings`), CONSTRAINT `impact_report_for_project` FOREIGN KEY (`project_id`) REFERENCES `infrastructure_project` (`project_id`) INVERSEOF `~impact_report_for_project` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-envira');
CREATE OR REPLACE CONCEPT `energy_efficiency_program` (`description` string, `expected_savings` decimal, `end_date` date, `program_id` integer, `title` string, `start_date` date, PRIMARY KEY (`program_id`), LABEL (`title`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-lightbulb');
CREATE OR REPLACE CONCEPT `employee` (`employee_id` integer) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-tie');
CREATE OR REPLACE CONCEPT `emergency_response_plan` (`description` string, `plan_id` integer, `response_teams` string, `activation_conditions` string, `last_updated` date, PRIMARY KEY (`plan_id`), LABEL (`description`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-ambulance');
CREATE OR REPLACE CONCEPT `customer_service_interaction` (`agent_id` integer, `interaction_date` date, `interaction_id` integer, `customer_id` integer, `issue` string, `resolution` string, PRIMARY KEY (`interaction_id`), LABEL (`issue`), CONSTRAINT `handled_by_agent` FOREIGN KEY (`agent_id`) REFERENCES `employee` (`employee_id`) INVERSEOF `~handled_by_agent` , CONSTRAINT `interaction_with_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) INVERSEOF `~interaction_with_customer` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-headset');
CREATE OR REPLACE CONCEPT `customer_loyalty_program` (`description` string, `enrollment_start_date` date, `program_id` integer, `benefits` string, `name` string, `enrollment_end_date` date, PRIMARY KEY (`program_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-heart-circle-check');
CREATE OR REPLACE CONCEPT `customer` (`address` string, `phone_number` string, `last_name` string, `customer_id` integer, `email` string, `first_name` string, PRIMARY KEY (`customer_id`), LABEL (`first_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-tag');
CREATE OR REPLACE CONCEPT `consumption` (`meter_id` integer, `read_date` date, `consumption_id` integer, `usage` decimal, PRIMARY KEY (`consumption_id`), LABEL (`consumption_id`), CONSTRAINT `consumption_recorded_by_meter` FOREIGN KEY (`meter_id`) REFERENCES `meter` (`meter_id`) INVERSEOF `~consumption_recorded_by_meter` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-droplet');
CREATE OR REPLACE CONCEPT `complaint_resolution` (`resolution_details` string, `satisfaction_rating` integer, `interaction_id` integer, `resolved_date` date, `resolution_id` integer, PRIMARY KEY (`resolution_id`), LABEL (`resolution_details`), CONSTRAINT `resolution_for_interaction` FOREIGN KEY (`interaction_id`) REFERENCES `customer_service_interaction` (`interaction_id`) INVERSEOF `~resolution_for_interaction` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-gavel');
CREATE OR REPLACE CONCEPT `billing_cycle` (`bill_amount` decimal, `end_date` date, `billing_cycle_id` integer, `account_id` integer, `start_date` date, PRIMARY KEY (`billing_cycle_id`), LABEL (`billing_cycle_id`), CONSTRAINT `billing_for_account` FOREIGN KEY (`account_id`) REFERENCES `service_account` (`account_id`) INVERSEOF `~billing_for_account` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-calendar-days');
CREATE OR REPLACE CONCEPT `asset` (`asset_id` integer, `location` string, `status` string, `purchase_date` date, `asset_type` string, PRIMARY KEY (`asset_id`), LABEL (`asset_type`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-briefcase');