CREATE OR REPLACE PROPERTY `process_id` integer;
CREATE OR REPLACE PROPERTY `role` string;
CREATE OR REPLACE PROPERTY `purpose` integer;
CREATE OR REPLACE PROPERTY `purpose_type` string;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `parent_purpose` integer;
CREATE OR REPLACE PROPERTY `purpose_id` integer;
CREATE OR REPLACE PROPERTY `process_name` string;
CREATE OR REPLACE PROPERTY `is_positional_actor` boolean;
CREATE OR REPLACE PROPERTY `facility_id` integer;
CREATE OR REPLACE PROPERTY `details` string;
CREATE OR REPLACE PROPERTY `operation_id` integer;
CREATE OR REPLACE PROPERTY `facility_type` string;
CREATE OR REPLACE PROPERTY `strategic_level` string;
CREATE OR REPLACE PROPERTY `organizational_unit` integer;
CREATE OR REPLACE PROPERTY `parent_facility` integer;
CREATE OR REPLACE PROPERTY `parent_object` integer;
CREATE OR REPLACE PROPERTY `object_type` string;
CREATE OR REPLACE PROPERTY `person_or_group` string;
CREATE OR REPLACE PROPERTY `parent_actor` integer;
CREATE OR REPLACE PROPERTY `organizational_unit_id` integer;
CREATE OR REPLACE PROPERTY `parent_process` integer;
CREATE OR REPLACE PROPERTY `facility_name` string;
CREATE OR REPLACE PROPERTY `object_id` integer;
CREATE OR REPLACE PROPERTY `prescription` string;
CREATE OR REPLACE PROPERTY `other_purpose_domain_information` string;
CREATE OR REPLACE PROPERTY `object_flow` integer;
CREATE OR REPLACE PROPERTY `location` string;
CREATE OR REPLACE PROPERTY `parent_unit` integer;
CREATE OR REPLACE PROPERTY `actor_id` integer;
CREATE OR REPLACE PROPERTY `time` string;
CREATE OR REPLACE PROPERTY `requirement_for_purpose` string;
CREATE OR REPLACE CONCEPT `purpose` (`description` string, `parent_purpose` integer, `purpose_id` integer, `requirement_for_purpose` string, `purpose` integer, `other_purpose_domain_information` string, `purpose_type` string, `strategic_level` string, PRIMARY KEY (`purpose_id`), LABEL (`purpose`), CONSTRAINT `has_parent_purpose` FOREIGN KEY (`parent_purpose`) REFERENCES `purpose` (`purpose_id`) INVERSEOF `parent_purpose` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bullseye');
CREATE OR REPLACE CONCEPT `process_involvements` (`actor_id` integer, `purpose` integer, `process_id` integer, PRIMARY KEY (`actor_id`, `process_id`, `purpose`), CONSTRAINT `involves_purpose` FOREIGN KEY (`purpose`) REFERENCES `purpose` (`purpose_id`) INVERSEOF `has_process_involvements` , CONSTRAINT `involves_process` FOREIGN KEY (`process_id`) REFERENCES `process` (`process_id`) INVERSEOF `has_process_involvements` , CONSTRAINT `involves_actor` FOREIGN KEY (`actor_id`) REFERENCES `actor` (`actor_id`) INVERSEOF `has_process_involvements` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-people-arrows');
CREATE OR REPLACE CONCEPT `process` (`description` string, `parent_process` integer, `process_name` string, `process_id` integer, `details` string, PRIMARY KEY (`process_id`), LABEL (`process_name`), CONSTRAINT `has_parent_process` FOREIGN KEY (`parent_process`) REFERENCES `process` (`process_id`) INVERSEOF `parent_process` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-recycle');
CREATE OR REPLACE CONCEPT `organizational_unit` (`description` string, `organizational_unit_id` integer, `parent_unit` integer, PRIMARY KEY (`organizational_unit_id`), LABEL (`description`), CONSTRAINT `has_parent_unit` FOREIGN KEY (`parent_unit`) REFERENCES `organizational_unit` (`organizational_unit_id`) INVERSEOF `parent_unit` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-building-un');
CREATE OR REPLACE CONCEPT `operations` (`purpose` integer, `operation_id` integer, `location` string, `facility_id` integer, `object_flow` integer, `process_id` integer, `time` string, PRIMARY KEY (`operation_id`), LABEL (`operation_id`), CONSTRAINT `involves_object_flow` FOREIGN KEY (`object_flow`) REFERENCES `object` (`object_id`) INVERSEOF `has_operations` , CONSTRAINT `belongs_to_facility` FOREIGN KEY (`facility_id`) REFERENCES `facility` (`facility_id`) INVERSEOF `has_operations` , CONSTRAINT `involves_process` FOREIGN KEY (`process_id`) REFERENCES `process` (`process_id`) INVERSEOF `has_operations` , CONSTRAINT `relates_to_purpose` FOREIGN KEY (`purpose`) REFERENCES `purpose` (`purpose_id`) INVERSEOF `has_operations` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-gear');
CREATE OR REPLACE CONCEPT `object` (`description` string, `object_type` string, `prescription` string, `object_id` integer, `parent_object` integer, PRIMARY KEY (`object_id`), LABEL (`object_type`), CONSTRAINT `has_parent_object` FOREIGN KEY (`parent_object`) REFERENCES `object` (`object_id`) INVERSEOF `parent_object` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-box-open');
CREATE OR REPLACE CONCEPT `facility` (`description` string, `facility_type` string, `parent_facility` integer, `facility_id` integer, `facility_name` string, `details` string, PRIMARY KEY (`facility_id`), LABEL (`facility_name`), CONSTRAINT `has_parent_facility` FOREIGN KEY (`parent_facility`) REFERENCES `facility` (`facility_id`) INVERSEOF `parent_facility` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-city');
CREATE OR REPLACE CONCEPT `actor` (`description` string, `actor_id` integer, `organizational_unit` integer, `parent_actor` integer, `role` string, `is_positional_actor` boolean, `person_or_group` string, PRIMARY KEY (`actor_id`), LABEL (`description`), CONSTRAINT `belongs_to_organizational_unit` FOREIGN KEY (`organizational_unit`) REFERENCES `organizational_unit` (`organizational_unit_id`) INVERSEOF `has_actor` , CONSTRAINT `has_parent_actor` FOREIGN KEY (`parent_actor`) REFERENCES `actor` (`actor_id`) INVERSEOF `parent_actor` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-masks-theater');
CREATE OR REPLACE CONCEPT `product_design_process`  INHERITS (`process`);
CREATE OR REPLACE CONCEPT `production_process`  INHERITS (`process`);
CREATE OR REPLACE CONCEPT `manufacturing_process`  INHERITS (`process`);
CREATE OR REPLACE CONCEPT `financial_process`  INHERITS (`process`);
CREATE OR REPLACE CONCEPT `inventory_process`  INHERITS (`production_process`);
CREATE OR REPLACE CONCEPT `distribution_process`  INHERITS (`production_process`);
CREATE OR REPLACE CONCEPT `scheduling_process`  INHERITS (`manufacturing_process`);
CREATE OR REPLACE CONCEPT `planning_process`  INHERITS (`manufacturing_process`);
CREATE OR REPLACE CONCEPT `manufacturing_information_process`  INHERITS (`manufacturing_process`);
CREATE OR REPLACE CONCEPT `fabrication_process`  INHERITS (`manufacturing_process`);
CREATE OR REPLACE CONCEPT `bom_process`  INHERITS (`manufacturing_process`);
CREATE OR REPLACE CONCEPT `purchasing_process`  INHERITS (`financial_process`);
CREATE OR REPLACE CONCEPT `invoicing_process`  INHERITS (`financial_process`);
CREATE OR REPLACE CONCEPT `person`  INHERITS (`actor`);
CREATE OR REPLACE CONCEPT `group`  INHERITS (`actor`);