CREATE OR REPLACE PROPERTY `date` date;
CREATE OR REPLACE PROPERTY `close_date` date;
CREATE OR REPLACE PROPERTY `asset_id` integer;
CREATE OR REPLACE PROPERTY `vote_id` integer;
CREATE OR REPLACE PROPERTY `document_id` integer;
CREATE OR REPLACE PROPERTY `project_name` string;
CREATE OR REPLACE PROPERTY `type` string;
CREATE OR REPLACE PROPERTY `fiscal_year` integer;
CREATE OR REPLACE PROPERTY `project_id` integer;
CREATE OR REPLACE PROPERTY `function` string;
CREATE OR REPLACE PROPERTY `case_id` integer;
CREATE OR REPLACE PROPERTY `effective_date` date;
CREATE OR REPLACE PROPERTY `election_id` integer;
CREATE OR REPLACE PROPERTY `budget` decimal;
CREATE OR REPLACE PROPERTY `open_date` date;
CREATE OR REPLACE PROPERTY `vote_date` date;
CREATE OR REPLACE PROPERTY `creation_date` date;
CREATE OR REPLACE PROPERTY `citizen_id` integer;
CREATE OR REPLACE PROPERTY `review_date` date;
CREATE OR REPLACE PROPERTY `employee_id` integer;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `phone_number` string;
CREATE OR REPLACE PROPERTY `position` string;
CREATE OR REPLACE PROPERTY `election_type` string;
CREATE OR REPLACE PROPERTY `purchase_date` date;
CREATE OR REPLACE PROPERTY `compliance_id` integer;
CREATE OR REPLACE PROPERTY `party` string;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE PROPERTY `end_date` date;
CREATE OR REPLACE PROPERTY `budget_id` integer;
CREATE OR REPLACE PROPERTY `date_of_birth` date;
CREATE OR REPLACE PROPERTY `response_id` integer;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `title` string;
CREATE OR REPLACE PROPERTY `content` string;
CREATE OR REPLACE PROPERTY `candidate_id` integer;
CREATE OR REPLACE PROPERTY `regulation_id` integer;
CREATE OR REPLACE PROPERTY `asset_type` string;
CREATE OR REPLACE PROPERTY `first_name` string;
CREATE OR REPLACE PROPERTY `value` decimal;
CREATE OR REPLACE PROPERTY `email` string;
CREATE OR REPLACE PROPERTY `compliance_status` string;
CREATE OR REPLACE PROPERTY `document_type` string;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `amount` decimal;
CREATE OR REPLACE PROPERTY `department_id` integer;
CREATE OR REPLACE PROPERTY `department_name` string;
CREATE OR REPLACE PROPERTY `case_type` string;
CREATE OR REPLACE PROPERTY `last_name` string;
CREATE OR REPLACE PROPERTY `hire_date` date;
CREATE OR REPLACE PROPERTY `funding_amount` decimal;
CREATE OR REPLACE PROPERTY `grant_id` integer;
CREATE OR REPLACE PROPERTY `request_date` date;
CREATE OR REPLACE PROPERTY `request_id` integer;
CREATE OR REPLACE CONCEPT `vote` (`vote_date` date, `candidate_id` integer, `vote_id` integer, `citizen_id` integer, `election_id` integer, PRIMARY KEY (`vote_id`), LABEL (`vote_id`), CONSTRAINT `vote_for_candidate` FOREIGN KEY (`candidate_id`) REFERENCES `candidate` (`candidate_id`) INVERSEOF `~vote_for_candidate` , CONSTRAINT `vote_by_citizen` FOREIGN KEY (`citizen_id`) REFERENCES `citizen` (`citizen_id`) INVERSEOF `~vote_by_citizen` , CONSTRAINT `vote_in_election` FOREIGN KEY (`election_id`) REFERENCES `election` (`election_id`) INVERSEOF `~vote_in_election` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-vote-yea');
CREATE OR REPLACE CONCEPT `service_request` (`description` string, `request_id` integer, `status` string, `citizen_id` integer, `request_date` date, PRIMARY KEY (`request_id`), LABEL (`description`), CONSTRAINT `request_by_citizen` FOREIGN KEY (`citizen_id`) REFERENCES `citizen` (`citizen_id`) INVERSEOF `~request_by_citizen` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-bell-concierge');
CREATE OR REPLACE CONCEPT `regulation` (`description` string, `effective_date` date, `title` string, `regulation_id` integer, PRIMARY KEY (`regulation_id`), LABEL (`title`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-book-bookmark');
CREATE OR REPLACE CONCEPT `public_works_project` (`description` string, `status` string, `end_date` date, `project_name` string, `budget` decimal, `start_date` date, `project_id` integer, PRIMARY KEY (`project_id`), LABEL (`project_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-digging');
CREATE OR REPLACE CONCEPT `grant` (`description` string, `end_date` date, `department_id` integer, `title` string, `funding_amount` decimal, `start_date` date, `grant_id` integer, PRIMARY KEY (`grant_id`), LABEL (`title`), CONSTRAINT `grant_managed_by_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~grant_managed_by_department` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-handshake');
CREATE OR REPLACE CONCEPT `employee` (`employee_id` integer, `department_id` integer, `last_name` string, `position` string, `hire_date` date, `first_name` string, PRIMARY KEY (`employee_id`), LABEL (`first_name`), CONSTRAINT `employee_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~employee_department` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-id-badge');
CREATE OR REPLACE CONCEPT `emergency_response` (`description` string, `type` string, `status` string, `end_date` date, `response_id` integer, `start_date` date, PRIMARY KEY (`response_id`), LABEL (`type`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-ambulance');
CREATE OR REPLACE CONCEPT `election` (`description` string, `election_type` string, `date` date, `election_id` integer, PRIMARY KEY (`election_id`), LABEL (`election_type`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-box-archive');
CREATE OR REPLACE CONCEPT `document` (`document_type` string, `case_id` integer, `creation_date` date, `content` string, `document_id` integer, PRIMARY KEY (`document_id`), LABEL (`document_type`), CONSTRAINT `document_for_case` FOREIGN KEY (`case_id`) REFERENCES `case` (`case_id`) INVERSEOF `~document_for_case` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-file-lines');
CREATE OR REPLACE CONCEPT `department` (`function` string, `department_id` integer, `department_name` string, PRIMARY KEY (`department_id`), LABEL (`department_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-building');
CREATE OR REPLACE CONCEPT `compliance` (`review_date` date, `compliance_id` integer, `compliance_status` string, `department_id` integer, `regulation_id` integer, PRIMARY KEY (`compliance_id`), LABEL (`compliance_status`), CONSTRAINT `compliance_with_regulation` FOREIGN KEY (`regulation_id`) REFERENCES `regulation` (`regulation_id`) INVERSEOF `~compliance_with_regulation` , CONSTRAINT `department_compliance` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~department_compliance` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-check-square');
CREATE OR REPLACE CONCEPT `citizen` (`phone_number` string, `last_name` string, `email` string, `date_of_birth` date, `citizen_id` integer, `first_name` string, PRIMARY KEY (`citizen_id`), LABEL (`first_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-person');
CREATE OR REPLACE CONCEPT `case` (`description` string, `open_date` date, `close_date` date, `case_id` integer, `status` string, `case_type` string, `citizen_id` integer, PRIMARY KEY (`case_id`), LABEL (`case_type`), CONSTRAINT `case_for_citizen` FOREIGN KEY (`citizen_id`) REFERENCES `citizen` (`citizen_id`) INVERSEOF `~case_for_citizen` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-folder-open');
CREATE OR REPLACE CONCEPT `candidate` (`party` string, `candidate_id` integer, `name` string, `election_id` integer, PRIMARY KEY (`candidate_id`), LABEL (`name`), CONSTRAINT `candidate_in_election` FOREIGN KEY (`election_id`) REFERENCES `election` (`election_id`) INVERSEOF `~candidate_in_election` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-tie');
CREATE OR REPLACE CONCEPT `budget` (`amount` decimal, `department_id` integer, `budget_id` integer, `fiscal_year` integer, PRIMARY KEY (`budget_id`), LABEL (`budget_id`), CONSTRAINT `budget_for_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~budget_for_department` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-dollar-sign');
CREATE OR REPLACE CONCEPT `asset` (`asset_id` integer, `value` decimal, `department_id` integer, `purchase_date` date, `asset_type` string, PRIMARY KEY (`asset_id`), LABEL (`asset_type`), CONSTRAINT `asset_for_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) INVERSEOF `~asset_for_department` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-briefcase');