CREATE OR REPLACE PROPERTY `date` date;
CREATE OR REPLACE PROPERTY `end_date` date;
CREATE OR REPLACE PROPERTY `assigned_resource_id` integer;
CREATE OR REPLACE PROPERTY `contract_id` integer;
CREATE OR REPLACE PROPERTY `skill_level` string;
CREATE OR REPLACE PROPERTY `description` string;
CREATE OR REPLACE PROPERTY `industry` string;
CREATE OR REPLACE PROPERTY `task_id` integer;
CREATE OR REPLACE PROPERTY `availability` string;
CREATE OR REPLACE PROPERTY `contact_info` string;
CREATE OR REPLACE PROPERTY `type` string;
CREATE OR REPLACE PROPERTY `procured_item` string;
CREATE OR REPLACE PROPERTY `approved` boolean;
CREATE OR REPLACE PROPERTY `issue_date` date;
CREATE OR REPLACE PROPERTY `procurement_id` integer;
CREATE OR REPLACE PROPERTY `project_id` integer;
CREATE OR REPLACE PROPERTY `terms` string;
CREATE OR REPLACE PROPERTY `scope` string;
CREATE OR REPLACE PROPERTY `invoice_id` integer;
CREATE OR REPLACE PROPERTY `value` decimal;
CREATE OR REPLACE PROPERTY `budget` decimal;
CREATE OR REPLACE PROPERTY `start_date` date;
CREATE OR REPLACE PROPERTY `amount` decimal;
CREATE OR REPLACE PROPERTY `quantity` integer;
CREATE OR REPLACE PROPERTY `billing_id` integer;
CREATE OR REPLACE PROPERTY `due_date` date;
CREATE OR REPLACE PROPERTY `billing_date` date;
CREATE OR REPLACE PROPERTY `priority` string;
CREATE OR REPLACE PROPERTY `unit_price` decimal;
CREATE OR REPLACE PROPERTY `risk_level` string;
CREATE OR REPLACE PROPERTY `review_date` date;
CREATE OR REPLACE PROPERTY `total_amount` decimal;
CREATE OR REPLACE PROPERTY `vendor_id` integer;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `paid` boolean;
CREATE OR REPLACE PROPERTY `resource_id` integer;
CREATE OR REPLACE PROPERTY `compliance_type` string;
CREATE OR REPLACE PROPERTY `cost_rate` decimal;
CREATE OR REPLACE PROPERTY `customer_id` integer;
CREATE OR REPLACE PROPERTY `region` string;
CREATE OR REPLACE PROPERTY `service_provided` string;
CREATE OR REPLACE PROPERTY `compliance_id` integer;
CREATE OR REPLACE PROPERTY `expense_id` integer;
CREATE OR REPLACE PROPERTY `status` string;
CREATE OR REPLACE CONCEPT `vendor` (`vendor_id` integer, `contact_info` string, `service_provided` string, `name` string, PRIMARY KEY (`vendor_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-store-alt');
CREATE OR REPLACE CONCEPT `task` (`description` string, `priority` string, `status` string, `assigned_resource_id` integer, `due_date` date, `task_id` integer, `name` string, `project_id` integer, PRIMARY KEY (`task_id`), LABEL (`name`), CONSTRAINT `task_for_project` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) INVERSEOF `~task_for_project` , CONSTRAINT `task_assigned_to_resource` FOREIGN KEY (`assigned_resource_id`) REFERENCES `resource` (`resource_id`) INVERSEOF `~task_assigned_to_resource` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-tasks');
CREATE OR REPLACE CONCEPT `resource` (`skill_level` string, `type` string, `availability` string, `resource_id` integer, `cost_rate` decimal, `name` string, PRIMARY KEY (`resource_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-gear');
CREATE OR REPLACE CONCEPT `project` (`status` string, `end_date` date, `scope` string, `customer_id` integer, `budget` decimal, `risk_level` string, `name` string, `start_date` date, `project_id` integer, PRIMARY KEY (`project_id`), LABEL (`name`), CONSTRAINT `belongs_to_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) INVERSEOF `~belongs_to_customer` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-clipboard-list');
CREATE OR REPLACE CONCEPT `procurement` (`vendor_id` integer, `procured_item` string, `quantity` integer, `unit_price` decimal, `procurement_id` integer, `date` date, `project_id` integer, PRIMARY KEY (`procurement_id`), LABEL (`procured_item`), CONSTRAINT `procurement_for_project` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) INVERSEOF `~procurement_for_project` , CONSTRAINT `procurement_from_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendor` (`vendor_id`) INVERSEOF `~procurement_from_vendor` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-cart-shopping');
CREATE OR REPLACE CONCEPT `invoice` (`invoice_id` integer, `contract_id` integer, `status` string, `paid` boolean, `total_amount` decimal, `issue_date` date, PRIMARY KEY (`invoice_id`), LABEL (`invoice_id`), CONSTRAINT `invoice_for_contract` FOREIGN KEY (`contract_id`) REFERENCES `contract` (`contract_id`) INVERSEOF `~invoice_for_contract` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-file-invoice-dollar');
CREATE OR REPLACE CONCEPT `expense` (`type` string, `amount` decimal, `approved` boolean, `date` date, `expense_id` integer, `project_id` integer, PRIMARY KEY (`expense_id`), LABEL (`type`), CONSTRAINT `expense_for_project` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) INVERSEOF `~expense_for_project` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-calculator');
CREATE OR REPLACE CONCEPT `customer` (`industry` string, `region` string, `customer_id` integer, `contact_info` string, `name` string, PRIMARY KEY (`customer_id`), LABEL (`name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user');
CREATE OR REPLACE CONCEPT `contract` (`terms` string, `contract_id` integer, `value` decimal, `end_date` date, `start_date` date, `project_id` integer, PRIMARY KEY (`contract_id`), LABEL (`contract_id`), CONSTRAINT `contract_for_project` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) INVERSEOF `~contract_for_project` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-file-contract');
CREATE OR REPLACE CONCEPT `compliance` (`review_date` date, `compliance_type` string, `compliance_id` integer, `status` string, `project_id` integer, PRIMARY KEY (`compliance_id`), LABEL (`compliance_type`), CONSTRAINT `compliance_for_project` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) INVERSEOF `~compliance_for_project` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-shield-halved');
CREATE OR REPLACE CONCEPT `billing` (`invoice_id` integer, `status` string, `amount` decimal, `billing_id` integer, `billing_date` date, PRIMARY KEY (`billing_id`), LABEL (`billing_id`), CONSTRAINT `billing_for_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `invoice` (`invoice_id`) INVERSEOF `~billing_for_invoice` ) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-wallet');