CREATE OR REPLACE PROPERTY `country` string;
CREATE OR REPLACE PROPERTY `creative_name` string;
CREATE OR REPLACE PROPERTY `item_revenue_in_usd` float;
CREATE OR REPLACE PROPERTY `shipping_value` float;
CREATE OR REPLACE PROPERTY `shipping_value_in_usd` float;
CREATE OR REPLACE PROPERTY `item_refund` float;
CREATE OR REPLACE PROPERTY `language` string;
CREATE OR REPLACE PROPERTY `property_value` string;
CREATE OR REPLACE PROPERTY `source` string;
CREATE OR REPLACE PROPERTY `purchase_revenue_in_usd` float;
CREATE OR REPLACE PROPERTY `item_category` string;
CREATE OR REPLACE PROPERTY `item_refund_in_usd` float;
CREATE OR REPLACE PROPERTY `location_id` string;
CREATE OR REPLACE PROPERTY `property_name` string;
CREATE OR REPLACE PROPERTY `creative_slot` string;
CREATE OR REPLACE PROPERTY `hostname` string;
CREATE OR REPLACE PROPERTY `revenue` float;
CREATE OR REPLACE PROPERTY `affiliation` string;
CREATE OR REPLACE PROPERTY `stream_id` string;
CREATE OR REPLACE PROPERTY `price` float;
CREATE OR REPLACE PROPERTY `event_date` string;
CREATE OR REPLACE PROPERTY `browser_version` string;
CREATE OR REPLACE PROPERTY `id` string;
CREATE OR REPLACE PROPERTY `item_variant` string;
CREATE OR REPLACE PROPERTY `transaction_id` string;
CREATE OR REPLACE PROPERTY `mobile_model_name` string;
CREATE OR REPLACE PROPERTY `advertising_id` string;
CREATE OR REPLACE PROPERTY `item_category4` string;
CREATE OR REPLACE PROPERTY `purchase_revenue` float;
CREATE OR REPLACE PROPERTY `item_category5` string;
CREATE OR REPLACE PROPERTY `item_category2` string;
CREATE OR REPLACE PROPERTY `refund_value_in_usd` float;
CREATE OR REPLACE PROPERTY `item_category3` string;
CREATE OR REPLACE PROPERTY `firebase_app_id` string;
CREATE OR REPLACE PROPERTY `mobile_brand_name` string;
CREATE OR REPLACE PROPERTY `version` string;
CREATE OR REPLACE PROPERTY `item_list_id` string;
CREATE OR REPLACE PROPERTY `refund_value` float;
CREATE OR REPLACE PROPERTY `user_id` string;
CREATE OR REPLACE PROPERTY `metro` string;
CREATE OR REPLACE PROPERTY `event_value_in_usd` float;
CREATE OR REPLACE PROPERTY `vendor_id` string;
CREATE OR REPLACE PROPERTY `name` string;
CREATE OR REPLACE PROPERTY `event_name` string;
CREATE OR REPLACE PROPERTY `sub_continent` string;
CREATE OR REPLACE PROPERTY `region` string;
CREATE OR REPLACE PROPERTY `continent` string;
CREATE OR REPLACE PROPERTY `event_server_timestamp_offset` bigint;
CREATE OR REPLACE PROPERTY `tax_value_in_usd` float;
CREATE OR REPLACE PROPERTY `city` string;
CREATE OR REPLACE PROPERTY `item_revenue` float;
CREATE OR REPLACE PROPERTY `promotion_id` string;
CREATE OR REPLACE PROPERTY `medium` string;
CREATE OR REPLACE PROPERTY `event_timestamp` bigint;
CREATE OR REPLACE PROPERTY `item_list_index` string;
CREATE OR REPLACE PROPERTY `platform` string;
CREATE OR REPLACE PROPERTY `operating_system_version` string;
CREATE OR REPLACE PROPERTY `promotion_name` string;
CREATE OR REPLACE PROPERTY `tax_value` float;
CREATE OR REPLACE PROPERTY `browser` string;
CREATE OR REPLACE PROPERTY `operating_system` string;
CREATE OR REPLACE PROPERTY `currency` string;
CREATE OR REPLACE PROPERTY `install_source` string;
CREATE OR REPLACE PROPERTY `user_first_touch_timestamp` bigint;
CREATE OR REPLACE PROPERTY `is_limited_ad_tracking` string;
CREATE OR REPLACE PROPERTY `quantity` bigint;
CREATE OR REPLACE PROPERTY `coupon` string;
CREATE OR REPLACE PROPERTY `item_id` string;
CREATE OR REPLACE PROPERTY `total_item_quantity` bigint;
CREATE OR REPLACE PROPERTY `item_name` string;
CREATE OR REPLACE PROPERTY `item_brand` string;
CREATE OR REPLACE PROPERTY `unique_items` bigint;
CREATE OR REPLACE PROPERTY `event_bundle_sequence_id` bigint;
CREATE OR REPLACE PROPERTY `mobile_os_hardware_model` string;
CREATE OR REPLACE PROPERTY `item_list_name` string;
CREATE OR REPLACE PROPERTY `install_store` string;
CREATE OR REPLACE PROPERTY `price_in_usd` float;
CREATE OR REPLACE PROPERTY `event_previous_timestamp` bigint;
CREATE OR REPLACE PROPERTY `user_pseudo_id` string;
CREATE OR REPLACE PROPERTY `mobile_marketing_name` string;
CREATE OR REPLACE PROPERTY `category` string;
CREATE OR REPLACE PROPERTY `time_zone_offset_seconds` bigint;
CREATE OR REPLACE CONCEPT `user_properties` (`user_id` string, `property_value` string, `property_name` string, PRIMARY KEY (`user_id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-user-cog');
CREATE OR REPLACE CONCEPT `user_lifetime_value` (`user_id` string, `event_timestamp` bigint, `revenue` float, `currency` string, PRIMARY KEY (`event_timestamp`, `user_id`), LABEL (`revenue`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-sack-dollar');
CREATE OR REPLACE CONCEPT `transaction` (`purchase_revenue_in_usd` float, `shipping_value` float, `purchase_revenue` float, `total_item_quantity` bigint, `event_timestamp` bigint, `unique_items` bigint, `shipping_value_in_usd` float, `user_id` string, `tax_value` float, `refund_value` float, `transaction_id` string, `refund_value_in_usd` float, `tax_value_in_usd` float, PRIMARY KEY (`transaction_id`, `event_timestamp`, `user_id`), LABEL (`purchase_revenue`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-cart-shopping');
CREATE OR REPLACE CONCEPT `traffic_source` (`user_id` string, `event_timestamp` bigint, `source` string, `name` string, `medium` string, PRIMARY KEY (`event_timestamp`, `user_id`, `name`), LABEL (`source`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-arrow-right-arrow-left');
CREATE OR REPLACE CONCEPT `item` (`promotion_id` string, `promotion_name` string, `price_in_usd` float, `affiliation` string, `item_refund_in_usd` float, `item_category` string, `item_category5` string, `location_id` string, `item_name` string, `quantity` bigint, `item_revenue_in_usd` float, `item_category3` string, `item_variant` string, `item_category4` string, `item_list_name` string, `item_category2` string, `event_timestamp` bigint, `creative_slot` string, `item_refund` float, `creative_name` string, `user_id` string, `item_brand` string, `item_list_index` string, `price` float, `item_id` string, `item_revenue` float, `coupon` string, `item_list_id` string, PRIMARY KEY (`item_id`, `event_timestamp`, `user_id`), LABEL (`item_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-box-open');
CREATE OR REPLACE CONCEPT `geo` (`user_id` string, `metro` string, `continent` string, `event_timestamp` bigint, `sub_continent` string, `region` string, `city` string, `country` string, PRIMARY KEY (`event_timestamp`, `user_id`), LABEL (`continent`, `country`, `city`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-globe-americas');
CREATE OR REPLACE CONCEPT `event_properties` (`user_id` string, `event_timestamp` bigint, `property_value` string, `property_name` string, PRIMARY KEY (`property_name`, `event_timestamp`, `user_id`), LABEL (`property_name`, `property_value`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-gears');
CREATE OR REPLACE CONCEPT `event` (`event_bundle_sequence_id` bigint, `user_id` string, `event_name` string, `platform` string, `user_pseudo_id` string, `event_timestamp` bigint, `event_server_timestamp_offset` bigint, `event_date` string, `stream_id` string, `user_first_touch_timestamp` bigint, `event_previous_timestamp` bigint, `event_value_in_usd` float, PRIMARY KEY (`event_timestamp`, `user_id`), LABEL (`event_name`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-calendar-days');
CREATE OR REPLACE CONCEPT `device` (`mobile_marketing_name` string, `event_timestamp` bigint, `category` string, `operating_system` string, `advertising_id` string, `vendor_id` string, `hostname` string, `browser` string, `mobile_os_hardware_model` string, `operating_system_version` string, `user_id` string, `mobile_model_name` string, `time_zone_offset_seconds` bigint, `is_limited_ad_tracking` string, `mobile_brand_name` string, `browser_version` string, `language` string, PRIMARY KEY (`user_id`, `event_timestamp`), LABEL (`category`, `operating_system`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-computer');
CREATE OR REPLACE CONCEPT `app_info` (`user_id` string, `install_store` string, `event_timestamp` bigint, `id` string, `install_source` string, `firebase_app_id` string, `version` string, PRIMARY KEY (`id`, `event_timestamp`, `user_id`), LABEL (`id`)) INHERITS (`thing`) WITH TAGS (`icon` = 'fa-info-circle');